src/T2DMap.cpp, src/TArea.cpp, src/TArea.h, src/TLuaInterpreter.cpp, src/TMap.cpp, src/TMap.h, src/TRoom.cpp, src/TRoom.h, src/TRoomDB.cpp, src/dlgRoomExits.cpp
The specification for this member is:
```
QMultiMap\<int, QPair\<int, int> > exits
```
and it is a record of the rooms that are on border on the TArea instance.
The outer QMultiMap key is the room id of the in_area room, and the value
pair is:
```
first=out_of_area room id
second=direction code
```
The original direction codes were defined at the start of the TArea.cpp
class file but there did not appear to be any logic to the values used:
N=12, NE=1, E=3, SE=4, S=6, SW=7, W=9, NW=10, UP=13, DOWN=14, IN=15,
OUT=16, OTHER=17.  Other than a lua function getAreaExits(areaId) which was
supposed to return just a list of unique keys via a TArea::getAreaExits()
method - i.e. a list of rooms in the given area which were exits to another
area, no other use was made of this data.  I propose to …
=> BugFix: Fix original coding errors creating data in TArea::exits member

src/dlgColorTrigger.cpp
Found these the hard way - in use - and it meant that one could not specify a colour trigger to fire on cyan or light white (grey ?) - one of which was just the colour I needed for a Mud that I had returned to after it had come back after being off-line for more than six months - I'd always wondered why I could never get my WoTMUD (back on-line now at game.wotmud.org:2224) room name trigger to work...!
Using gitk blame it transpires that this bug dates to 03/11/2009 and predates Mudlet version 1.0.1 !
Resolves [bug 1103645](https://bugs.launchpad.net/mudlet/+bug/1103645), the patch I published there duplicates this PR.
Ideally would be back-ported to 2.1 and put into 3.0.0-gamma ?
=> bugfix: typos in dlgColorTrigger messes up cyan and lWhite triggers

src/dlgTriggerEditor.cpp
This fixes the bug where moving through the searches will cause content to be overwritten.
=> Bug fix for editor content loss

src/TLuaInterpreter.cpp, src/TMap.cpp, src/TRoomDB.cpp, src/TRoomDB.h, src/dlgMapper.cpp
Some steps had previously been taken to enforce no duplicate area names
when importing an XML map or when adding a new name but other mechanisms
were left unchecked, specifically this was when renaming an existing area.
This commit adds a number of validation steps to many of the lua functions
that manipulate areas and their names.  This includes taking steps when
creating a new TArea instance to ensure a suitable area name is created and
added to the areaNamesMap which may be overwritten if a valid (non-empty,
non-duplicate) name is provided at the time or later.  This avoids problems
with the Area selection widget on the 2 or 3D Map Display and the lua
getAreaTable() function, neither of which will handle duplicate area names
and for the former, does not handle nameless areas well …
=> BugFix: Treat and prevent further duplicate or empty map area names (Alternative)

mudlet.svg
Got rid of the metadata tag after consultation with Thorsten Wilms - it was left over from a template used to help define the various sizes of the icon.
=> Fix license claim on mudlet.svg

src/TRoomDB.cpp
Found in practice that some situations cause the map file to be loaded
twice - whilst that is not ideal from a performance point of view it was
inducing problems with a recent Pull Request (#237) into the development
branch where every area was being detected as a duplicate.  It turns out
that that change assumed the areaNamesMap was empty when restoring a map
from a file, which was not the case.  This change fixes that - but the
fact that the map file is loaded twice still needs looking at.
=> Fix: Empty TRoomDB::areaNamesMap before (re)loading it from file

src/Host.cpp, src/Host.h, src/TBuffer.cpp, src/TConsole.cpp, src/TConsole.h, src/TTextEdit.cpp, src/XMLexport.cpp, src/XMLimport.cpp, src/dlgProfilePreferences.cpp, src/ui/profile_preferences.ui
HTLM Issues addressed:
* a stray, unopened \</span\> was being placed at start of body of HTML.
* use of XHTML \<br /\> instead of correct HTML \<br\> to force new lines
in produced HTML text.
* empty lines were not being reproduced when copying from clipboard to
HTML.
* previously produced HTML was being place all on one line, no line-feeds
in HTML source - by changing the CSS "white-space" arguments they are now
put into the produced HTML making it possible to edit it in a normal text
editor but it should still render correctly.
* the data "type='text/css'" was missing from HTML \<style\> tags - this is a
mandatory attribute for that type of tag under HTML 4.01 strict (although
not for later HTML 5).
* the \<title\>\</title\> tag-pair was missing from the \<head\> part of HTML
documents …
=> Fix: Revise HTML producing code to produce VALID html

src/T2DMap.cpp, src/TArea.cpp, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/TMap.cpp, src/TRoom.cpp, src/TRoom.h, src/TRoomDB.cpp, src/TRoomDB.h, src/dlgRoomExits.cpp
This is my way to address https://bugs.launchpad.net/mudlet/+bug/1413435. It's an updated version of #249 .
It's a fix for keeping reverse area exit map in sync with exit creation/modification, room adding, and deletion. It also uses the nomenclature of entraceMap as suggested by @SlySven because I forgot what reverseExitMap meant as well :).
=> Fix for exit map being out of sync

src/dlgColorTrigger.cpp
Found these the hard way - in use - and it meant that one could not specify
a colour trigger to fire on cyan or light white (grey ?) - one of which was
just the colour I needed for a Mud that I had returned to after it had come
back after being off-line for more than six months - I'd always wondered
why I could never get my WoTMUD (now at game.wotmud.org:2224) room name
trigger to work...!
Using gitk blame it transpires that this bug dates to 03/11/2009 and
predates Mudlet version 1.0.1 !
Resolves bug [1103645](https://bugs.launchpad.net/mudlet/+bug/1103645), the patch I published there duplicates this PR. This PR duplicates https://github.com/Mudlet/Mudlet/pull/235 but it wasn't clear how to (or whether I even should) apply the same commit to multiple branches without creating separate …
=> (release_30)bugfix: typos in dlgColorTrigger messes up cyan and lWhite triggers

src/TLuaInterpreter.cpp, src/TMap.cpp, src/TRoomDB.cpp, src/TRoomDB.h, src/dlgMapper.cpp
Some steps had previously been taken to enforce no duplicate area names
when importing an XML map or when adding a new name but other mechanisms
were left unchecked, specifically this was when renaming an existing area.
This commit adds a number of validation steps to many of the lua functions
that manipulate areas and their names.  This includes taking steps when
creating a new TArea instance to ensure a suitable area name is created and
added to the areaNamesMap which may be overwritten if a valid (non-empty,
non-duplicate) name is provided at the time or later.  This avoids problems
with the Area selection widget on the 2 or 3D Map Display and the lua
getAreaTable() function, neither of which will handle duplicate area names
and for the former, does not handle nameless areas well …
=> BugFix: Treat and prevent further duplicate or empty map area names

src/dlgConnectionProfiles.cpp, src/dlgConnectionProfiles.h, src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h
Connecting the (virtual, protected) update() signal to a slot that merely
calls the same thing makes any use of the update() method fatally
recursive.  This commit removes this misfeature from the two dialogs:
dlgConnectionProfile and dlgTriggerEditor that have it.
PR #258 does the same for the release_30 branch
=> logicBombFix: remove useless and fatally recursive slot_ function

src/dlgConnectionProfiles.cpp, src/dlgConnectionProfiles.h, src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h
Connecting the (virtual, protected) update() signal to a slot that merely
calls the same thing makes any use of the update() method fatally
recursive.  This commit removes this misfeature from the two dialogs:
dlgConnectionProfile and dlgTriggerEditor that have it.
PR #257 does the same for the development branch
=> (release_30)logicBombFix: remove useless and fatally recursive slot_ function

src/TLuaInterpreter.cpp, src/TMap.cpp, src/TRoomDB.cpp
Before some recent changes it was possible to create a new area name entry with TLuaInterpreter::setAreaName(...) by supplying an unused area ID and a name so that it was stored in TRoomDB::areaNamesMap WITHOUT an actual TArea instance to pair it with.  This fix restores that mode of operation and the ability to DELETE such an orphan area name which had also been
removed by either the same series of commits or some other recent one that neglected to continue to provide the latter.
=> (release_30)BugFix: Restore ability to create area name entry without a TArea instance

src/TLuaInterpreter.cpp, src/TMap.cpp, src/TRoomDB.cpp
Before some recent changes it was possible to create a new area name entry
with TLuaInterpreter::setAreaName(...) by supplying an unused area ID and
a name so that it was stored in TRoomDB::areaNamesMap WITHOUT an actual
TArea instance to pair it with.  This fix restores that mode of operation
and the ability to DELETE such an orphan area name which had also been
removed by either the same series of commits or some other recent one that
neglected to continue to provide the latter.
=> BugFix: Restore ability to create area name entry without a TArea instance

src/TRoomDB.cpp, src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h, src/src.pro
Fixes a couple of one-liner errors that I recently introduced into the
Development branch (and also the release_30 but that uses different
commit references):
In commit 10fefa0a "revise: deletion of more redundant methods in header"
which removed definition of the above signal I forgot to remove the call
to connect(...) that used the signal.
In commit 94b492c1 "BugFix: Treat and prevent further duplicate or empty
map area names" I neglected to properly escape (using double '\') a regular
expression used to detect a de-duplicated Area Name.
Also: adds a couple of missing header files to qmake project file - their
absence means that they were NOT included in the group of files considered
when using the Qt IDE find/replace parts of the code editor - which can cause
problems when looking for …
=> BugFix: remove dlgTriggerEditor::accept() usage/properly escape a RegExp

src/TRoomDB.cpp, src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h, src/src.pro
Fixes a couple of one-liner errors that I recently introduced into the
release_30 branch (and also the Development but that uses different
commit references):
In commit e6a8bcc5 "revise: deletion of more redundant methods in header"
which removed definition of the above signal I forgot to remove the call
to connect(...) that used the signal.
In commit 521fdc21 "BugFix: Treat and prevent further duplicate or empty
map area names" I neglected to properly escape (using double '\') a regular
expression used to detect a de-duplicated Area Name.
Also: adds a couple of missing header files to qmake project file - their
absence means that they were NOT included in the group of files considered
when using the Qt IDE find/replace parts of the code editor - which can
cause problems when looking for …
=> (release_30)BugFix: remove dlgTriggerEditor::accept() usage/properly escape a RegExp

src/TLuaInterpreter.cpp, src/ctelnet.h, src/dlgRoomExits.cpp, src/ui/room_exits.ui
The use of fixed strings as the keys for various QMaps associate with the exits is not optimal IMHO... this and https://github.com/Mudlet/Mudlet/pull/268 are necessary to fix a long standing error I made with the dlgRoomExit class in that when it is initialising the form the wrong fixed strings were used to populate the exits' weights for the XY-plane normal exits.  This has the result that they appear to be zero (meaning the weight of the destination room appears to be used) instead of reading the value that is actually stored in the map file/database.  Any changes then made are written out with the correct key in the TRoom::exitWeight member for the edited room - but it can mess up any settings made using a lua script.  This series of commits addresses the problem and also:
* improves …
=> Bug fix correct strings used as room exit weight keys

src/TLuaInterpreter.cpp, src/ctelnet.h, src/dlgRoomExits.cpp, src/ui/room_exits.ui
The use of fixed strings as the keys for various QMaps associate with the exits is not optimal IMHO... this and https://github.com/Mudlet/Mudlet/pull/267 (for the development branch) are necessary to fix a long standing error I made with the dlgRoomExit class in that when it is initialising the form the wrong fixed strings were used to populate the exits' weights for the XY-plane normal exits. This has the result that they appear to be zero (meaning the weight of the destination room appears to be used) instead of reading the value that is actually stored in the map file/database. Any changes then made are written out with the correct key in the TRoom::exitWeight member for the edited room - but it can mess up any settings made using a lua script. This series of commits addresses the …
=> (release 30)bug fix correct strings used as room exit weight keys

src/T2DMap.cpp, src/TArea.cpp, src/TArea.h, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/TMap.cpp, src/TRoom.cpp, src/TRoom.h, src/TRoomDB.cpp, src/TRoomDB.h, src/dlgRoomExits.cpp
This is a condensed copy of recent changes relating to what is now TRoomDB::entranceMap and bulk room deletion code (_that improves things by doing the relatively slow updating of the former only once when many rooms are being removed; and in debug builds only reports on the timings for every 1000 rooms deleted instead of each one!_) that was made in "release_30" to backport them to the  "development" branch.  This should help to *reduce* the differences between those branches :pray:.
Commit 01 of 10 originally entitled:
"fix for keeping reverse area exit map in sync with exit creation, adding,
and deletion"
Conflicts resolved in:
src/TRoom.h
Commit 02 of 10 originally entitled:
"bug fix for entranceMap having reversed key and value"
Conflicts resolved in:
src/TRoomDB.cpp
Commit 03 of 10 …
=> Backport: merge ten commits

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h
This implements Pull Request #212 (commit-859c2b68) in the development
branch with revisions to more closely match our adopted coding style (open
'{' on same line as conditional, single line code blocks always wrapped
with '{'...'}') and Lua run-time (value) errors returned as nil plus an
error message rather than throwing a lua error as argument type errors
do.
Adds lua commands:
* ```getAllRoomUserData(roomID)```: given a roomId number returns a lua table
of all the user data.
* ```getRoomUserDataKeys(roomID)```: given a roomId number returns a lua list
of all the keys of the user data for that room.
* ```clearRoomUserDataItem(roomID,key)```: given a roomId number and a user
data key removes that key/value pair from the user data for that room.
Returns true if data was removed, false if …
=> (release_30)Enhance: provide missing functionality for Map Room User Data

src/TLuaInterpreter.cpp
This implements PR #213 (commit-f5b6b42e) as applied to "development"
branch to the release_30 one, it includes a squashed in second commit
to fix a small redundant bit of code in the original.
Updates ```getRoomName()```, ```setRoomName()``` and ```searchRoom()``` to handle non-ASCII
room name data.  The strings passed to and from the lua subsystem now use
Utf-8 which is a super-set of (backwards compatible with) ASCII.
Also, the original lua command when invoked as ```searchRoom("string")``` did a
case insensitive room name search and used the supplied string for a
partial search of all room names in the map.  One or two optional Boolean
arguments can be now supplement the supplied search string for the
room-name, the first, if true, makes the search case sensitive and the
second, …
=> (release_30)Enhance: lua searchRoom() search, allow non-ASCII room names

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h
Source: http://bc-dev.net/2013/02/23/mudlet-getcmdline-function/
This function was requested by an IRC user. While I usually don't jump at any request for new functions, the user mentioned this was a good way to increase accessability for disabled people, because they might need long for each keystroke. The user's usage example: 
> the way I do it is this c + keypad, cc + keypad, ccc +keypad, cccc +keypad the letter c stands for curing and the keypad num key determines what and the manner I cure,  prefer macros I type slower due to a disability
=> Add function getCmdLine()

src/Host.h, src/TTimer.cpp, src/dlgProfilePreferences.cpp, src/ui/profile_preferences.ui
Adds a spinbox control to the last page of the profile preferences that
allows the user to set an interval for which any Timer less than this will
NOT dump it's command and script content to the debug console in dark
yellow on a blue background EVERY time it fires.  The Execute OK line will
still show up in green - so the timer can be seen to be firing but the
windows will not fill up with spammy text so much.
This fixes [bug 1511590](https://bugs.launchpad.net/mudlet/+bug/1511590) that I have raised in response to my encountering it
and remembering a user reporting it in the [forums](http://forums.mudlet.org/viewtopic.php?f=7&t=4745).
Also: I also spotted and corrected a couple of lines above my addition to
dlgProfilePreferences::slot_save_and_exit() where the unchecked global
pointer to …
=> Bugfix/Enhance:  Suppress debug output from short interval timers

src/Host.h, src/TTimer.cpp, src/dlgProfilePreferences.cpp, src/ui/profile_preferences.ui
Adds a spinbox control to the last page of the profile preferences that
allows the user to set an interval for which any Timer less than this will
NOT dump it's command and script content to the debug console in dark
yellow on a blue background EVERY time it fires.  The Execute OK line will
still show up in green - so the timer can be seen to be firing but the
windows will not fill up with spammy text so much.
This fixes [bug 1511590](https://bugs.launchpad.net/mudlet/+bug/1511590) that I have raised in response to my encountering it
and remembering a user reporting it in the [forums](http://forums.mudlet.org/viewtopic.php?f=7&t=4745).
Also: I also spotted and corrected a couple of lines above my addition to
dlgProfilePreferences::slot_save_and_exit() where the unchecked global
pointer to …
=> (release_30)Bugfix/Enhance:  Suppress debug output from short interval timers

src/Host.h, src/TLuaInterpreter.cpp, src/TMap.cpp, src/TRoomDB.cpp, src/ctelnet.cpp, src/mudlet.cpp
Uh, this should have been a single commit but I forgot to squash them together * *sigh* *.
Read the message for the second commit for details but the bottom line is that it add a Host::postMessage(const QString) wrapper for cTelnet::postMessage(QString) so the latter class doesn't have to be __#include__ d or referred to directly by the using class.
This is to make the two code branches have the same code in the areas touched after #277 is Pulled...
=> Code match (release 30)bugfix faulty non error message alignment

.travis.yml, CI/travis.install.sh, CI/travis.linux.install.sh, CMakeLists.txt, src/CMakeLists.txt, src/Host.cpp, src/TLuaInterpreter.cpp, src/TRoomDB.cpp, src/dlgPackageExporter.cpp, src/luazip.h, src/src.pro
This revises the Travis C.I. setup to:
Build all combinations of:
* MaoOs vs. Linux
* CMake vs. QMake project files
* G++ vs Clang++ compiler
Doing this has found a couple of small bugs in TRoomDB which the second commit fixes.
In testing we can have 5 (five) sub-builds active at a time and currently it takes around 11 minutes to do a full build.
The Linux build is using the _older_ "non-container" build as it uses sudo to tweak somethings that the new "container" based one does not allow.  I did try to migrate to the new (faster, more resources 2 cores per VM & 4GB vs. 1.5 cores & 3GB) but I found it impossible to setup the package selection we want.
I have made both this and the release_30 version much more similar - I have ported this one's use of boost 1.55 libraries to the release_30 …
=> Fix enhance travis ci setup

.travis.yml, CI/travis.install.sh, CI/travis.linux.before_install.sh, CI/travis.linux.install.sh, CMakeLists.txt, src/CMakeLists.txt, src/Host.cpp, src/TLuaInterpreter.cpp, src/TRoomDB.cpp, src/dlgPackageExporter.cpp, src/luazip.h, src/src.pro
This revises the Travis C.I. setup to:
Build all combinations of:
* MaoOs vs. Linux
* CMake vs. QMake project files
* G++ vs Clang++ compiler
Doing this has found a couple of small bugs in TRoomDB which the second commit fixes.
In testing we can have 5 (five) sub-builds active at a time and currently it takes around 11 minutes to do a full build.
The Linux build is using the _older_ "non-container" build as it uses sudo to tweak somethings that the new "container" based one does not allow.  I did try to migrate to the new (faster, more resources 2 cores per VM & 4GB vs. 1.5 cores & 3GB) but I found it impossible to setup the package selection we want.
I have made both this and the release_30 version much more similar - I have ported the development one's use of boost 1.55 libraries to …
=> (release 30)fix enhance travis ci setup

src/CMakeLists.txt, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/mudlet-lua/lua/LuaGlobal.lua, src/src.pro
Add comptile-time fallback to LuaGlobal.lua loading logic to attempt to load
from LUA_DEFAULT_PATH, defined in src/src.pro using the value from
LUA_DEFAULT_DIR.
For platforms that don't currently define LUA_DEFAULT_DIR in src/src.pro (e.g.
win32, macx), the loading logic will behave as though LUA_DEFAULT_DIR were
defined as "/", the root directory. This is accomplished by compile time
concatenation of LUA_DEFAULT_PATH and the string literal "/". If necessary,
LUA_DEFAULT_DIR can later be defined for additional platforms (win32, macx,
etc) in src/src.pro to provide a different compile-time fallback for that
platform.
=> Bugfix/Enhance: Load LuaGlobal.lua from LUA_DEFAULT_PATH

src/TCommandLine.cpp
On a full keyboard with a keypad, the special keys on the keypad are completely redundant.  Previously, much of the keypad couldn't be used because shift turns most of the buttons into these redundant special keys.  With this fix the buttons become available again.
=> Added shortcut for keypad keys (comments)

CI/travis.osx.install.sh, CMakeLists.txt, src/TArea.h, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/TMap.cpp, src/TMap.h, src/dlgProfilePreferences.cpp, src/src.pro, src/ui/profile_preferences.ui
~~The first commit is actually #277.~~ Evaporated from here as it has already been merged.
The ~~second~~ first is the purpose of this PR.  See it's comments for the details but its primary purpose is to provide data storage on a per area and a whole map basis in the same manner as the per room TRoom::userData member.  I have a use for this to hold extra attributes found during importation of Xml Map files but I realised that there is a more general usefulness to being able to store these types of data within the map; just a couple of random examples of the top of my head would be, for areas: the name of a piece of background music to play whilst in that area and for the map: a history of edits or - for a profile that is used for more than one character from within the same profile, …
=> (release 30)enhance add area and map user data structures

CMakeLists.txt, src/TArea.h, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/TMap.cpp, src/TMap.h, src/dlgProfilePreferences.cpp, src/src.pro, src/ui/profile_preferences.ui
~~The first pair of commits are actually #278.~~ That first pair have evaporated from here as that PR has already been merged.
The ~~third~~ first is the purpose of this PR.  See it's comments for the details but its primary purpose is to provide data storage on a per area and a whole map basis in the same manner as the per room TRoom::userData member.  I have a use for this to hold extra attributes found during importation of Xml Map files but I realised that there is a more general usefulness to being able to store these types of data within the map; just a couple of random examples of the top of my head would be, for areas: the name of a piece of background music to play whilst in that area and for the map: a history of edits or - for a profile that is used for more than one character …
=> Enhance add area and map user data structures

src/ctelnet.cpp, src/ctelnet.h
The event is fired when one of the data protocols MSDP, MXP, ATCP, GMCP or
Channel 102 were successfully enabled. User scripts can now freely use the
protocol.
The event has a second argument that denominates the protocol that was enabled.
The commit also makes sure that GMCP is only enabled if the user chose to enable
GMCP if the server sends IAC DO GMCP.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mudlet/mudlet/285)
=> (release_30)Add the new "sysNegotiationFinishedEvent"

src/TEvent.h, src/TLuaInterpreter.cpp
Currently, the raiseEvent function only accepts string and number arguments. Args of other types are simply ignored, and the argument list is shortened. This is just a small change to allow passing booleans, as well. The same functionality can be achieved by passing 0 or 1 (or "true"/"false", or whatever) and putting an explicit check in the event handler function, but it would be convenient to be able to pass booleans as is.
=> Make changes to TEvent and TLuaInterpreter to allow passing boolean args to raiseEvent().

src/TEvent.h, src/TLuaInterpreter.cpp
Same changes as in my recent PR to development. Haven't done any additional testing beyond making sure it compiles, but I don't see any potential sources of different behavior.
=> Allow passing boolean arguments to raiseEvent() and callEventHandler()

src/dlgTriggerEditor.cpp
The functions responsible for exporting profiles and triggers were
blindly appending ".xml" onto the end of the filename before writing.
This would result in exporting a file called <name>.xml.xml if the
user specified <name>.xml. This commit adds a case-insensitive check
to see if the filename already ends in ".xml" before appending it
to the end of the filename.
=> Fix: Bug where save profile as <name>.xml would save as <name>.xml.xml

src/TLuaInterpreter.cpp
There has been a fair amount of copy and paste in creating various Lua
commands - but the error messages have not always been revised when this
has happened.  With a bit of *nix shell-fu I have identified the cases
where this has happened and changed the function that is given as the
name where an error occurred.
Note that this does not attempt to improve the formatting to bring the
standard up to current guidelines - or that the amended functions actually
operate as intended - merely it fixes gross errors that will definitely be
confusing to anyone seeing those messages.
=> Bugfix: correct errors in Lua command error messages

src/TLuaInterpreter.cpp
There has been a fair amount of copy and paste in creating various Lua commands - but the error messages have not always been revised when this has happened.  With a bit of *nix shell-fu I have identified the cases where this has happened and changed the function that is given as the name where an error occurred.
Note that this does not attempt to improve the formatting to bring the standard up to current guidelines - merely it fixes gross errors that will definitely be confusing to anyone seeing the messages.
This is the release_30 version of the development version #297 and, line numbers, aside it makes the same changes.
=> (release_30)bugfix: correct errors in Lua command error messages

src/main.cpp
Whilst working on other things I noted that the Splash Screen Message on
start-up was too wide and overflowed the sides of graphic in some
situations - I've realigned the message to the top of the widget and
reformatted it to be a little less wide.
=> Tweak: Reformat Splash Screen Message

src/main.cpp
Whilst working on other things I noted that the Splash Screen Message on
start-up was too wide and overflowed the sides of graphic in some
situations - I've realigned the message to the top of the widget and
reformatted it to be a little less wide.
=> (release_30)tweak: Reformat Splash Screen Message

src/TBuffer.cpp
Whilst debugging other code I found that the flag that is set when a line
is started in a TConsole/TBuffer that records the timestamp is not reset
after it does it's job of getting the time and pushing it into the
(QStringList) TBuffer::timeBuffer - the symptom I was getting was with
an "empty" profile and adding a script that caused a line of text (I think)
ending with a line feed "\n" character - the code seemed to be stuck in a
busy loop.  From the structure of the code in the area of this commit I see
that after the flag has been used IT IS NOT RESET and so the assignment of
a time string as the backmost entry in TBuffer::timebuffer will be repeated
until the end of the buffer that is being timestamped is reached.
I do not know for sure if this is the whole story - I thought it seemed …
=> BugFix: fix a logic error that may be causing a hang on startup

src/TBuffer.cpp
Whilst debugging other code I found that the flag that is set when a line
is started in a TConsole/TBuffer that records the timestamp is not reset
after it does it's job of getting the time and pushing it into the
(QStringList) TBuffer::timeBuffer - the symptom I was getting was with
an "empty" profile and adding a script that caused a line of text (I think)
ending with a line feed "\n" character - the code seemed to be stuck in a
busy loop.  From the structure of the code in the area of this commit I see
that after the flag has been used IT IS NOT RESET and so the assignment of
a time string as the backmost entry in TBuffer::timebuffer will be repeated
until the end of the buffer that is being timestamped is reached.
I do not know for sure if this is the whole story - I thought it seemed …
=> (release_30)BugFix: fix a logic error that may be causing a hang on startup

src/TLuaInterpreter.cpp, src/TMap.cpp, src/TMap.h
About to start a real session of MUD playing I noted that there is no quick
way to assign ranges of room numbers when mapping out areas - it is useful
to some map-makers to group ranges of numbers to areas.  Since we do not
provide an implicit ways to renumber rooms (have to create new instance and
copy data across in a script) I think some would find it useful to be able
to supply a starting room number to the Lua command createRoomID and for
that to return the next available number past that.
{This will be familiar to a TinTin++ MUD Client user which behaves in the
same manner as I propose here - IIRC!}
The Lua createRoomID() has been updated (to current code/message
guidelines) - it will return a nil AND an error message instead of a
number if the optionally supplied first argument is …
=> Enhance: Add ability to specify starting room number to createRoomID()

src/TLuaInterpreter.cpp, src/TMap.cpp, src/TMap.h
About to start a real session of MUD playing I noted that there is no quick
way to assign ranges of room numbers when mapping out areas - it is useful
to some map-makers to group ranges of numbers to areas.  Since we do not
provide an implicit ways to renumber rooms (have to create new instance and
copy data across in a script) I think some would find it useful to be able
to supply a starting room number to the Lua command createRoomID and for
that to return the next available number past that.
{This will be familiar to a TinTin++ MUD Client user which behaves in the
same manner as I propose here - IIRC!}
The Lua createRoomID() has been updated (to current code/message
guidelines) - it will return a nil AND an error message instead of a
number if the optionally supplied first argument is …
=> (release_30)enhance: Add ability to specify starting room number to createRoomID()

src/Host.cpp, src/T2DMap.cpp, src/T2DMap.h, src/TArea.cpp, src/TArea.h, src/TConsole.cpp, src/TConsole.h, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/TMap.cpp, src/TMap.h, src/TRoom.cpp, src/TRoom.h, src/TRoomDB.cpp, src/TRoomDB.h, src/XMLimport.cpp, src/ctelnet.cpp, src/dlgMapper.cpp, src/dlgMapper.h, src/dlgProfilePreferences.cpp, src/dlgProfilePreferences.h, src/dlgRoomExits.cpp, src/glwidget.cpp, src/glwidget.h, src/mudlet.cpp, src/mudlet.h, src/src.pro, src/ui/profile_preferences.ui
A bit of a big one here but it does do something for [bug 1500927](https://bugs.launchpad.net/mudlet/+bug/1500927) as mentioned in the [forums](http://forums.mudlet.org/viewtopic.php?f=13&t=4857&p=23095). It also has a thorough map auditing/cleaner which should help to fix the sort of issues that past TArea::rooms addition/removal code introduced (particularly the removal part! :smile: ) and the custom exit line drawing code that would start to draw lines on an anonymous exit direction.  E.g. [this](http://forums.mudlet.org/viewtopic.php?f=0&t=4695&p=23384&hilit=QList#p23383).
As I had to touch up the mapper drawing code the 2D one in particular has gained a bit of a tidy up for the room list selection widget - and it should be a bit faster because of the QList to QSet changes. Ssaliss' …
=> Enhancement: move TArea::rooms to QSet (updated)

src/TForkedProcess.cpp
The read function for spawn() is only called once every time we get a chunk of output, even if that chunk containes multiple lines.
This is caused since TForkedProcess::slotReceivedData() doesn't get called for every line that it sent for it, but rather each time the output from the process is flushed.
You try this out by running 'ls' for example: `spawn(function(s) echo(s) end, "ls")`
The fix makes slotReceivedData() read all the lines that it can from the process before returning.
=> Bugfix for spawn() in TForkedProcess::slotRecievedData()

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h
As per the original poster on:
https://bugs.launchpad.net/mudlet/+bug/1427364
With a forum mention on:
http://forums.mudlet.org/viewtopic.php?f=9&t=4728
This seems to be caused by a code error that checked the wrong string (the name to give to the downloaded file) rather than the URL.
As well as fixing that error in:
`(int)TLuaInterpreter::downloadFile(lua_State *)`, this revision also validates and will produce a ___nil___ + _relevant error message_ return if the given URL does not seem valid; will handle non-ASCII characters in both strings and is more tolerant in parsing the string given as a URL.  It also returns a `true` value on a successful request creation and the URL that is
used to perform the request which may NOT be the same as the one the user give.
The related …
=> BugFix: TLuaInterpreter::downloadFile() not working for https URLs

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h
As per the original poster on:
https://bugs.launchpad.net/mudlet/+bug/1427364
With a forum mention on:
http://forums.mudlet.org/viewtopic.php?f=9&t=4728
This seems to be caused by a code error that checked the wrong string (the name to give to the downloaded file) rather than the URL.
As well as fixing that error in:
`(int)TLuaInterpreter::downloadFile(lua_State *)`, this revision also validates and will produce a ___nil___ + _relevant error message_ return if the given URL does not seem valid; will handle non-ASCII characters in both strings and is more tolerant in parsing the string given as a URL.  It also returns a `true` value on a successful request creation and the URL that is
used to perform the request which may NOT be the same as the one the user give.
The related …
=> (release_30)bugFix: TLuaInterpreter::downloadFile() not working for https URLs

src/dlgConnectionProfiles.cpp
I accidentally restored the font size to a readable one for the text assigned to the `QListWidgetItem` for each profile in the Connection Profile dialog when it was in fact set to a bare minimum to attempt to hide it from the user's eyes.  This commit undoes that and resets the size to the 1minimum.
=> bodge: restore min. font size to profile icon text in Connection Profile

src/dlgConnectionProfiles.cpp
I accidentally restored the font size to a readable one for the text assigned to the `QListWidgetItem` for each profile in the Connection Profile dialog when it was in fact set to a bare minimum to attempt to hide it from the user's eyes.  This commit undoes that and resets the size to the 1 minimum.
=> (release_30)bodge: restore min. font size to profile icon text in Connection Profile

src/Host.cpp, src/Host.h, src/TTimer.cpp, src/dlgProfilePreferences.cpp, src/dlgProfilePreferences.h, src/ui/profile_preferences.ui
It also removes the code that produces the output that it was removing if
the timer interval was below it's threshold...!
=> revert: remove previous code added to suppress some Timer debug output

src/dlgConnectionProfiles.cpp
In trying to avoid a crash if the user renamed the very first profile in Connection Dialog I handled the case where a value used as a divisor could be zero - but did not spot the situation where it would be -1, when creating a new profile.  This commit fixes this show stopper bug:
https://bugs.launchpad.net/mudlet/+bug/1633786
=> CriticalBugFix: prevent crash on New Profile Creation

src/Host.cpp, src/Host.h, src/TTimer.cpp, src/dlgProfilePreferences.cpp, src/dlgProfilePreferences.h, src/ui/profile_preferences.ui
It also removes the code that produces the output that it was removing if
the timer interval was below it's threshold...!
=> (release_30)revert: remove previous code added to suppress some Timer debug output

src/dlgConnectionProfiles.cpp
In trying to avoid a crash if the user renamed the very first profile in Connection Dialog I handled the case where a value used as a divisor could be zero - but did not spot the situation where it would be -1, when creating a new profile.  This commit fixes this show stopper bug:
https://bugs.launchpad.net/mudlet/+bug/1633786
=> (release_30)criticalBugFix: prevent crash on New Profile Creation

src/TLuaInterpreter.cpp
When I introduced area and map user data storage I also revised the room user data code - specifically `TLuaInterpreter::getRoomUserData(...)` to provide informative error messages on various failures, unintentionally though, this introduced an incompatibility with the documented behaviour for this function in that, as of commit-https://github.com/Mudlet/Mudlet/commit/79a8905c391d33ee3a7756a4b20afbe99cdf75c3 it was expected to return an empty string if the given room id (first argument) number did not exist or the data key (second argument) string was not found for that room.
As it happens the past and current code DOES allow an empty string to be stored against a given key but the past code did not allow the user to differentiate it from the case where the room didn't exist (though that …
=> (release_30)compatibilityHack: restore empty string response on no room user data

CMakeLists.txt, src/src.pro
While this was originally intended to make Debian packaging easier, Debian packaging is not longer a problem. Still sticking with the change however as it'll be easier to explain that zeta isn't the last preview version.
This makes the version naming follow the Latin alphabet using Greek letters.
=> Change version from zeta to iota

src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h
Whilst looking at a different issue I spotted that there were two sets of pointers in the `dlgTriggerEditor` class that were intended to track the "current" item in each of Aliases, Buttons ("Actions"), Keys, Scripts, Timers, Triggers and Variables.  The more appropriately named `mpCurrentXXXXItem` ones were largely unused and the `mCurrentXXXX` ones were mainly used.  However in the case of the ones for Variables the mixing of the use of both of them, may, I thought, have resulted in some oddities in hiding and un-hiding of variables that I previously remembered happening. 
In fact it doesn't but that is another story...
Also:
* Found some systematic duplicate checks in code for Aliases, Keys etc. for a `QTreeWidgetItem` pointer being non-null which I was able to remove.  I then spotted …
=> Refactor: eliminate duplicated set of pointers in dlgTriggerEditor class

src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h
Whilst looking at a different issue I spotted that there were two sets of pointers in the `dlgTriggerEditor` class that were intended to track the "current" item in each of Aliases, Buttons ("Actions"), Keys, Scripts, Timers, Triggers and Variables.  The more appropriately named `mpCurrentXXXXItem` ones were largely unused and the `mCurrentXXXX` ones were mainly used.  However in the case of the ones for Variables the mixing of the use of both of them, may, I thought, have resulted in some oddities in hiding and un-hiding of variables that I previously remembered happening.
In fact it doesn't but that is another story...
Also:
* Found some systematic duplicate checks in code for Aliases, Keys etc. for a `QTreeWidgetItem` pointer being non-null which I was able to remove. I then spotted a …
=> (release_30)refactor: eliminate duplicated set of pointers in dlgTriggerEditor class

src/Host.cpp, src/Host.h, src/TLuaInterpreter.cpp, src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h, src/mudlet.cpp
This fix will allow modules with sub-directories to be parsed and installed (which the prior code did not always do) as it scans archived packages/modules to establish any sub-directories needed and does not just rely on archive entries with a zero length file size ending in `/` which is the __defined__ method for indicating them - some (possible compressed) archive creation systems do not always seem to insert them.
This should also make significant improvements to package/module installation as it finally cleans up the "Unpacking" dialogue that previously was left in view should the un-archiving or other operation fail - the previous failure to do this was giving the impression that the operation had hung rather than failed!
Whilst preparing this I found some chunks of ineffective or …
=> Bugfix package installation and revise server gui handling

src/Host.cpp, src/Host.h, src/TLuaInterpreter.cpp, src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h, src/mudlet.cpp
This is an amalgumation of a series of commits previously applied to the
development branch:
Cleanup: clear dead code & prevent reentrancy issue in Host::installPackage
---------------------------------------------------------------------------
`Host::installPackage(...)` can call `Host::uninstallPackage(...)` which in
turn can call `Host::installPackage(...)` back.  This reentrancy could cause
issues with a single instance of a `QDialog` used by the former which was
accessed via a class member pointer.  The previous code structure avoids
this, but if the code failed to maintain the case where this is safe (when
second argument has the value of 2) there would be multiple `QDialogs`
created but only one could be tracked by a class member pointer.  It is
possible to avoid this issue by …
=> (release_30)bugFix: fix loading of packagage/modules

src/TLuaInterpreter.cpp, src/TTrigger.cpp, src/mudlet.cpp, src/mudlet.h
This moves sound from 4 static players into an unlimited QList,
fixing https://bugs.launchpad.net/mudlet/+bug/1645064
It also adds volume (0-100) to the LUA playSoundFile command, with 100
(maximum) substituted if not present for backwards compatability.
=> (release_30) sound updates - bugfix and enhance

src/TTextEdit.cpp
The set of conditionals that control when the mouse is close enough to the edge to scroll a console was uneven. Because height() is not zero-based, the scrollDown margin was 9.
=> Bugfix: equalizes mouse-drag scroll margins on TConsoles

src/TTextEdit.cpp, src/TTextEdit.h
This PR adds the ability to select entire lines at a time through ctrl+click and timestamp clicking. Dragging across lines is functional as well.
(also includes the bugfix in
https://bugs.launchpad.net/mudlet/+bug/1408198 that was never added to
the development branch)
=> Added: ctrl/timestamp + click to select entire lines

src/TTextEdit.cpp
Conditional has been fixed so that it hits the same 10 pixel range on
either side when you drag the mouse up and down a console.
See: #366
=> (release_30) Bugfix: equalizes mouse-drag scroll margins on TConsoles

src/TAction.cpp, src/TAlias.cpp, src/TKey.cpp, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/TScript.cpp, src/TTimer.cpp, src/TTrigger.cpp
Updates the code of each type of object to use an overloaded form of TLuaCompile::compile() that replaces `luaL_dostring` with `luaL_loadbuffer` followed by `lua_pcall` so that the name of the object is assigned to the chunk when it's compiled. In the case of a function erroring that is defined in one object but called in another, it causes the error message from the LuaInterpreter to properly report the name of the object that defined the function that the error is contained in. This eliminated the annoying `<[string "-------------------...": <line number>: <error>` style messages that often confuse new users of Mudlet.
=> Added: errors in compileScript now report which script they were generated from

src/Host.cpp, src/HostManager.cpp, src/HostManager.h, src/TEvent.h, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/dlgConnectionProfiles.cpp, src/dlgConnectionProfiles.h, src/mudlet.cpp
This ~~experimental~~ working system allows a script in one profile to: `raiseInterProfileEvent( data )` where data is one or more number, string, boolean or nil values that can be detected by a declared `sysInterProfileEvent` event handler in all active profiles.  The host order for reception of the event is maintained in a circular manner so that the profile that emitted the event is the one to receive it last.  The first argument received after the `sysInterProfileEvent` one is the name of the sending host, then the subsequent ones are the arguments supplied to the invoking function.
Also, as the data to be sent as an event has to be passed up to the main mudlet class this does have to lock some resources whilst the event is propagated to the other profiles which means it probably …
=> Enhance: add sysInterProfileEvent to enable inter-profile signalling

src/TMap.cpp
We're not lab scientists here working with very detailed timing data, just people wanting to play a game - nine decimal level precision is unwarranted. In fact even reporting the time is unimportant, the only thing that matters is that it happens fast and when it's not fast, the user knows when it'll finish.
=> Improved map timing to be more human-friendly

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/mudlet-lua/lua/GUIUtils.lua, src/mudlet.cpp, src/mudlet.h
I was trying to determine why my script was spamming the Central Debug Console with lines associate with the use of:
`TConsole::select(const QString &, int)`
at first I thought it was because we register `TLuaInterpreter::select()` as the user Lua command: `selectString` - to avoid any confusion with the built-in lua command of the same name that is used with variable length argument lists (often represented by `...` and meaning "all the remaining arguments") I have taken the opportunity to bring the function up to current style for error messages and argument handling (it will take three arguments where the first is an empty string or the translated equivalent to "main" to behave the same as the two argument case which acts on the main profile console window.)
This did not "cure" my …
=> Bugfix: remove Spam output from Lua [c|d|h]echo commands

src/HostManager.cpp
I don't think we mean to shift here.
It wasn't an actual problem though because the UI did the correct check beforehand.
=> (dev) Fix accidental shift instead of compare

src/TTextEdit.cpp
The scrollback now scrolls all the way to the bottom line of the console
instead of cutting off a full page above the bottom when you're
scrolling with the mouse wheel down.
=> Modified: mouse wheel scroll down behavior on consoles

src/XMLimport.cpp
With the use of Clang-format I found that it was necessary to disable the automagic header sorting that this utility does to the MSVC specific Qt library include guarding header files "pre_guard.h" and "post_guard.h", unfortunately when cloning the changes from the release_30 branch to this the development branch it seems I entered the wrong filename in the above
file.
Note that there is a similar name commit to be applied to the release_30 branch HOWEVER that fixes an entire different c**k-up in that branch (though the source was ALSO partly brought about by the same usage of code reformatting tools on the SAME file)... 8-(
=> BugFix: fixup recent change to ./src/XMLimport.cpp

src/XMLimport.cpp
With the use of Clang-format I found that it does not include the ability to insert/remove '{' and '}' around single statement code blocks in condition/loop construct.  I was inserting those manually but was thrown awry by the new/different layout for '} else {' that was chosen to be used and ended up paring a nested "else" code block with the wrong nested "if(...)" in (void) XMLimport::readAliasPackage() which breaks the parsing of many packages including the default ones so that they are not installed correctly.
Note that there is a similar name commit to be applied to the development branch HOWEVER that fixes an entire different c**k-up in that branch (though the source was ALSO partly brought about by the same usage of code reformatting tools on the SAME file)... 8-(
Signed-off-by: …
=> (release_30)bugFix: fixup recent change to ./src/XMLimport.cpp

src/3k-mapper.xml, src/deleteOldProfiles.xml, src/mudlet-mapper.xml
Updated scripts included with Mudlet to their latest versions from original source repositories.
=> (release 30) update default scripts (IRE, 3k mappers)

src/dlgTriggerEditor.cpp, src/mudlet.cpp
To save the settings, the config folder in QSettings across the source was set to "Mudlet".
For any other config file, the folder is "mudlet". 
Therefore, in case-sensitive systems (i.e. Linux), we were creating two config directories.
To fix it, I changed "Mudlet" to "mudlet" in the QSettings instanciations.
=> QSettings config directory

src/TLuaInterpreter.cpp, src/dlgTriggerEditor.cpp
In some places HTML tags have been incorrectly nested so that they did not operate correctly.
Some help texts in the Editor were missing a closing full-stop.
=> (release_30)bugFix: correct badly ordered HTML tags

src/TLuaInterpreter.cpp, src/dlgTriggerEditor.cpp
In some places HTML tags have been incorrectly nested so that they did not operate correctly.
Some help texts in the Editor were missing a closing full-stop.
=> BugFix: correct badly ordered HTML tags

src/Host.cpp
GMCP has clearly eclipsed ATCP at this point by popularity and it has also been rock-solid for a couple of years now, so we can safely enable it by default and save people having to do the whole 'enable GMCP & reconnect' dance on a new profile.
Haven't got that much information about MSDP so it's not enabled yet.
=> GMCP is now enabled by default on new profiles

src/TLuaInterpreter.cpp
See http://forums.mudlet.org/viewtopic.php?f=9&t=14770&p=34560#p34644
This actually reveals another bug; if you pass it 13 the error message will be "setExitStub: Need a dir number as 2nd argument" - which while being technically true as 13 is not a recognised dir number, it in reality pretty annoying to see because an unaware user might be thinking that they -are- passing in a dir number. That said, keeping scope of the PRs small for digestibility and don't want to do refactorings of functions before 3.0 final. See https://bugs.launchpad.net/mudlet/+bug/1670245
=> (release_30) Fix setExitStub to allow in/out stubs

src/TLuaInterpreter.cpp
See http://forums.mudlet.org/viewtopic.php?f=9&t=14770&p=34560#p34644
This actually reveals another bug; if you pass it 13 the error message will be "setExitStub: Need a dir number as 2nd argument" - which while being technically true as 13 is not a recognised dir number, it in reality pretty annoying to see because an unaware user might be thinking that they -are- passing in a dir number. That said, keeping scope of the PRs small for digestibility and don't want to do refactorings of functions before 3.0 final. See https://bugs.launchpad.net/mudlet/+bug/1670245
(cherry picked from commit cd8c25861feb9cc243b76c38d414d879987dce0b)
=> (dev) Fix setExitStub to allow in/out stubs

src/ctelnet.cpp, src/mudlet.cpp
I spotted the missing icon recently and I recall it was something that had already been ddressed in the development branch (by AC in commit: 9d52886268cfbb77498bedced2dc52ce6da1c815 ) but was not done for the release_30 branch for some reason.
There is also a `qDebug()` in `(void)cTelnet::_loadreplay()` that is in the wrong place and which grossly fills up any debugging output as a result, it seems I (or more likely Heiko) may have introduced it in commit: 1a6106aa21cdfcb053a25eb0722de87325a24bbc though AC did refactor it to use `qDebug()` when it previously used a `std::cout` - unfortunately he did not spot that it would dump the entire content of a replay chunk as many times as there were characters in that chunk!
These fixes only have to go into the release_30 branch - they have been …
=> (release_30)bugFix: fix missing icon from replay toolbar and a spammy replay qDebug

src/main.cpp
Seems to help a lot on my Hackintosh anyway, awaiting feedback from the users. Previously, once the mapper widget was open, all sorts of graphical corruption issues would happen with the toolbar - this seems to fix them.
=> (dev) Added a usable workaround for rendering issues on macOS

src/main.cpp
Seems to help a lot on my Hackintosh anyway, awaiting feedback from the users. Previously, once the mapper widget was open, all sorts of graphical corruption issues would happen with the toolbar - this seems to fix them.
(cherry picked from commit 9a62f7455429ce9fa6f9362073d9ceaf328bf792)
=> (release_30) Added a usable workaround for rendering issues on macOS

src/XMLimport.cpp
In commit 18750755c8a8acbb35a5dd65478333923da6a8e1 (Pull Request #373) a change was made that reordered the compilation of the Lua scripts for Mudlet items.  This commit reverts that aspect to restore the compilation of parent (e.g. folder/container) items before their children.
=> (release_30)partialRevert: restore compilation order on profile loading

src/XMLimport.cpp
In commit a7f81aafd9897cf38137f22638bfc3bca4d9f0d5 (Pull Request #372) a change was made that reordered the compilation of the Lua scripts for Mudlet items.  This commit reverts that aspect to restore the compilation of parent (e.g. folder/container) items before their children.
=> Partial Revert: restore compilation order on profile loading

src/CMakeLists.txt, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/mudlet-lua/lua/LuaGlobal.lua, src/src.pro
Need to fix the Linux generic installer - as the current one does not work, _at all_, for anybody. Switching over to using [AppImage](http://appimage.org/) instead of BitRock as I've validated AppImage with two random Ubuntu users and it at least seems to work better. Plus, it seems to be a better thing for the Linux ecosystem in general.
These fixes cherrypick 7922a3a4e3c71eae84fcfc1027d5c48ebaeb79ff from the ``development`` branch, improve that function to return multiple paths, and in general, make Mudlet also search things relative to its binary using an _absolute_ path. This is because AppImage does not set the current working directory for us unlike what Mudlet has been used to.
Merging this will also require merging which is a fix to LuaGlobal to also load stuff relative to the …
=> (release 30) Linux generic installer fixes

src/mudlet.cpp
Fixes https://bugs.launchpad.net/mudlet/+bug/1670393.
(cherry picked from commit 46bf0723ef6f98220ccef4c2beaf588a1e9625c1)
=> Fix Alias/Trigger/Script/etc button not bringing up script editor again

src/TAlias.cpp, src/TAlias.h, src/TTrigger.cpp, src/TTrigger.h, src/dlgTriggerEditor.cpp
Fixes a long standing [bug 583584](https://bugs.launchpad.net/mudlet/+bug/583584).
Although original problem was with `TAlias` items (which use a regexp) to match against user keystrokes it also minded me to take a look at the behaviour of `TTrigger` items that had perl regexp type entries, and I have updated the error messages for those to also report the error details should there be any in a regexp.
=> (release 30)bug fix report regexp errors correctly

src/mudlet-lua/lua/LuaGlobal.lua
7922a3a4e3c71eae84fcfc1027d5c48ebaeb79ff added getMudletLuaDefaultPath() that returned a single path, whereas the PR #414 changed function to be getMudletLuaDefaultPaths() and made it return an indexed table.
This fixes the wrong call that got left behind between cherrypicking and merging.
=> (release_30) Undo call to getMudletLuaDefaultPath()

src/ctelnet.cpp, src/mudlet-lua/lua/LuaGlobal.lua
Applies second patch from https://bugs.launchpad.net/mudlet/+bug/1119884.
Confirmed fixes test case for darklord.evils.in:9100 (create a character and type 'compress' to toggle MCCP on/off)
Confirmed fixes test case in http://www.mudbytes.net/forum/comment/72091/#c72091
Test case works on coffeemud.net port:2323 as well
=> (release_30) fix mccp toggling

src/ctelnet.cpp
Applies second patch from https://bugs.launchpad.net/mudlet/+bug/1119884.
Confirmed fixes test case for darklord.evils.in:9100 (create a character and type 'compress' to toggle MCCP on/off)
Confirmed fixes test case in http://www.mudbytes.net/forum/comment/72091/#c72091
Test case works on coffeemud.net port:2323 as well
=> (dev) fix mccp toggling

src/TLuaInterpreter.cpp
With this change, we can get rid of the run_mudlet helper script in the macOS
app bundle.
This is similar to a part of #414
=> (release_30) Modify the package.cpath for MacOS as well

src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h, src/ui/actions_main_area.ui
This is ANOTHER attempt to get the Command Up and Down for buttons restored to Mudlet to get the release_30 branch ready for release.  Previous attempts got bogged down in trying to do too much in one swell foop.
This provides the minimum IMHO to get the missing functionality back and to fix a significant bug in the previous handling of toolbars that were inserted into modules.
It is not everything that is wanted for the final release but represents a functional package of changes that are hopefully possible to swallow in one chunk.
It DOES NOT fix the behaviour of push-down buttons not sending the right thing on every press - I am still investigating that urgently (I do have some ideas); also the layout in the editor when some elements have been necessarily been hidden is not perfect.  I …
=> (release_30)BugFix_buttonCommandUpAndDownRedux_modulesWithToolBars

src/T2DMap.cpp, src/T2DMap.h
Cherry-picked commit that fixed a crash when opening the custom exit lines dialog (because the point was not initialised properly), and a case where if X was used to close the dialog drawing was still commenced.
Original message below:
As per http://bugs.launchpad.net/mudlet/+bug/1369041 the built-in dialog
button that some OS/Window systems provide did close the dialog but did not
cancel the custom line drawing process.  This fixes the matter by
connecting the reject() signal that the button produces to code to clean
up.
During debugging this it became clear that: if the custom line dialog was
being displayed but before the user had selected the exit to draw the line
for, it was possible to click on the map and add points to create a line;
this would be for a custom line with an Empty …
=> Close button on map custom exit dialog not cancelling line drawing

src/ActionUnit.cpp, src/ActionUnit.h, src/EAction.cpp, src/EAction.h, src/TAction.cpp, src/TAction.h, src/TEasyButtonBar.cpp, src/TEasyButtonBar.h, src/TFlipButton.cpp, src/TFlipButton.h, src/TToolBar.cpp, src/TToolBar.h, src/XMLexport.cpp, src/XMLimport.cpp
The first three commits do a fair amount of de-crufting which make it easier to find the salient issues which are addressed in the fourth commit.  This PR fixes: [Bug 1673672](https://bugs.launchpad.net/mudlet/+bug/1673672) "_Disabling button up still keeps the command toggle_". :grinning:
=> (release 30)BugFix: fix mButtonState behaviour for non-Push-Down "Buttons"

CMakeLists.txt, src/src.pro
It is my understanding that urgent bug fixes for the Release 3.0.0 need to be based on a version with the same version major.minor.patch "Sematic Version" string but, until actually "released" will carry a "-dev" build suffix. This commit will introduce the change so that the resultant point in the repository becomes the start point for such fixes and other work.
=> Version: advance master to form start point for future work

src/TRoom.cpp, src/TRoom.h, src/TRoomDB.cpp
Generally choose `QString` argument passing by `const` reference as opposed to
by value...!
=> Resolve all conflicts in TRoom and TRoomDB classes [ci skip]

src/XMLexport.cpp, src/XMLimport.cpp, src/XMLimport.h
In XMLimport / XMLexport classes generally retain the HEAD version except for the bit that supports `TAction::mButtonState` conversion to `bool` from `int`.
=> Resolve all conflicts in XMLimport and XML export classes [ci skip]

CMakeLists.txt, src/src.pro
This follows http://wiki.mudlet.org/w/Manual:Versioning.
We always had development on ``3.0.1-dev`` but that was in lieu of a proper versioning strategy...
=> Bump development to 3.0.0-dev

src/src.pro
This sets the APP_VERSION in that file to 3.0.0 and the APP_BUILD to "-dev" this matches the values in the CMake project file.
The .clang-format file is currently located in the ./src/ directory, that has been used to select the appropriate file in the DISTFILES variable.
Note that there was missing HEADERS files mentioned in BOTH merge sources for the irc sub-directory so I have picked through them to report the .h that seem to be present.
Added ./CI/travis.set-build-info.sh and ./src/testdbg.h into QMake project file.
=> Resolve conflicts in src.pro [ci skip]

src/dlgConnectionProfiles.cpp, src/dlgConnectionProfiles.h
Removed (Host *)HostManager::self() as per AC's changes in: https://github.com/Mudlet/Mudlet/commit/2555505ec897d3ebc72ce87bfbe156ac40d990f8
a.k.a. commit-2555505ec897d3ebc72ce87bfbe156ac40d990f8
Removed `dlgConnectionProfile::slot_chose_history()` as it was commented out in header file and in the HEAD version in `dlgConnectionProfile.cpp`.
=> Resolve conflicts in dlgConnectionProfile class [ci skip]

src/TBuffer.cpp, src/TBuffer.h, src/TConsole.cpp, src/TConsole.h, src/dlgMapper.h
Although unused `(void)TBuffer::set_text_properties(int)` was removed from cpp file it was still declared in header file - so I whipped it out in passing.
The `TBuffer` class also contains some currently commented out code to provide HTML support for over-line and inverse which are both ANSI ESC code-able SGR effects but which we do not currently provide.
The code changes for `TConsole::toggleLogging(...)` is slightly confusing at first because some code was shifted to a separate `TConsole::slot_toggleLogging()` wrapper used by the GUI but not by the Lua subsystem that only calls the "wrapped" method.  This is so that on-console logging starting and stopping messages could be avoided in the latter usage, nevertheless the OTHER merge branch contained some `QStringLiteral(...)` wrapped text …
=> Resolve conflicts in TBuffer, TConsole, dlgMapper classes [ci skip]

src/dlgProfilePreferences.cpp, src/dlgProfilePreferences.h
A number of the conflicts in the `.cpp` file are repeated instances of code to set a specific button to a user selected colour - the older conflicting instances had some repeated boilerplate that A. Charles moved into a separate `setColor(Button, Color)` function in the new instance - but which
did not take a local copy of the `Host` pointer and checked it for non-nullness before it was used.  The resolution I have done here does both.
=> Resolve remaining conflicts in: dlgProfilePreferences [ci skip]

src/dlgRoomExits.cpp
Fixes: [Bug 1676086](https://bugs.launchpad.net/mudlet/+bug/1676086) "Unable to clear south-east exit from 2D map "Room Exits" dialog".
This is a year or more old bug that I recently discovered in "both" code branches...
=> BugFix: allow south-east exit to be cleared on 2D map Room-Exits dialog

src/dlgRoomExits.cpp
A typo in: https://github.com/Mudlet/Mudlet/commit/f2fa6f4e51381e06beb0ac20509e03031060a71d (from 2015-02-07 10:57:12) for release_30 and in: https://github.com/Mudlet/Mudlet/commit/11b9331133208ea70097dc805ebae8e1397dc58e (from 2015-08-15 22:15:39) when it was ported to the development branch causes issues in trying to clear an exit in the south east direction.
Fixes: https://bugs.launchpad.net/mudlet/+bug/1676086 now recorded as https://github.com/Mudlet/Mudlet/issues/480.
=> (release_3_0_1)bugFix: allow south-east exit to be cleared on 2D map Room-Exits dialog

src/mudlet-lua/genDoc.sh, src/mudlet-lua/lua/GUIUtils.lua, src/mudlet-lua/lua/geyser/GeyserLabel.lua, src/mudlet-lua/tests/GUIUtils.lua
This is all pre-reviewed code that is already available in latest development (with a few minor last-min merges) that I'm moving from [vadi2/mudlet-lua](https://github.com/vadi2/mudlet-lua) into the Mudlet repository officially. The amount of commits is big because I'm moving all of the files with history, instead of copy/pasting them as that was the case before.
You'll see that the only actual differences really are the few outstanding PRs I've merged in.
Historically, mudlet-lua was split off into a separate branch for maintenance because the official Mudlet development was rather cumbersome and patch-based. We have solved that problem with time however and it was now the fact that mudlet-lua was in a separate repository became the issue: we have to sync things every once in a while, …
=> Move vadi2/mudlet-lua into Mudlet/Mudlet officially

src/XMLimport.cpp
=> Fix a memory leak that happened when loading checked variables

CI/travis.after_success.sh, CI/travis.set-build-info.sh
The former suffix made it hard to identify the actual PR and commit, even though
it was mentioned. The new build part is now PR{PR-ID}-{SHORT_SHA1}.
=> Change PR builds to a different suffix

src/TArea.cpp, src/TLuaInterpreter.cpp, src/TRoomDB.cpp, src/TTrigger.cpp
I've replaced obvious iterator declarations where the data structure of the iterator wasn't relevant to code with auto. In cases where it does matter, such as TTrigger matching, it's useful to keep it in so you can know what data structures are you working with.
In general, would like strive to modernise all of the codebase to C++11 - while keeping in mind that C++14 and C++17 are already available and C++11 is 6 years old, so we should be moving onto the newer stuff.
=> Modernised iterator declaration to use 'auto'

src/TMap.cpp
This'll enable us to test newer map formats 17 and 18.
Cut down on the verbosity of a "map format too new" message, I think the new one gets the message across just as well while not appearing like a wall of text.
=> Removed artificial version barriers to loading maps

src/LuaInterface.cpp, src/T2DMap.cpp, src/TAction.cpp, src/TCommandLine.cpp, src/TConsole.cpp, src/TEasyButtonBar.cpp, src/TForkedProcess.cpp, src/TMap.cpp, src/TTextEdit.cpp, src/TToolBar.cpp, src/TTrigger.cpp, src/Tree.h, src/VarUnit.cpp, src/XMLimport.cpp, src/dlgConnectionProfiles.cpp, src/dlgPackageExporter.cpp, src/dlgProfilePreferences.cpp, src/dlgRoomExits.cpp, src/dlgTriggerEditor.cpp, src/mudlet.cpp
Improved readability of code, less text to look at while all of the information is still there
I had to skip the iterators in TTrigger because .first() and .second() are used and without seeing the point right there and then, you wouldn't know what kind of data structures would those functions be operating on. Unfortunately haven't found a way yet to tell clang-tidy to ignore applying ``modernize-use-auto`` on it so it'll keep coming up in the future.
=> Applied auto to variable declaration

CI/travis.set-build-info.sh
The variable was set into quotes, which made the replacement of the original value fail. This is corrected now.
=> Fix replacement of the BUILD qmake variable

src/TConsole.cpp, src/TConsole.h, src/ctelnet.cpp
Turns the prefix of "[ ERROR ]" messages a brighter red and make the body yellow and tweak the colour of "[  OK  ]" mesage body to be cyan instead of orange.
Also modifies the signature of one form of `TConsole::print(...)` from:
`(void) TConsole::print( const QString &, int, int, int, int, int, int )`
to:
`(void) TConsole::print( const QString &, const QColor, const QColor )`
=> bugFix: make Error messages more visible

.travis.yml
Since macOS `gcc` builds are actually just clang builds with it posing as `gcc`,
we can save a little time and computing power by skipping the duplicate builds.
Fixes Mudlet/Mudlet#867
=> Skip gcc builds for macOS

src/mudlet.cpp
Fixed variables crash issue reported in 3.0.0 in http://forums.mudlet.org/viewtopic.php?f=9&t=19488
Tagging @Mudlet/core-cpp for review
=> (release_30) Fixed GUI saved variables crashing with autologin

src/Host.cpp, src/XMLexport.cpp, src/XMLimport.cpp, src/XMLimport.h, src/dlgConnectionProfiles.cpp, src/dlgTriggerEditor.cpp, src/mudlet.cpp, src/mudlet.h
I foresee the need to tweak the Xml format in the future, however though there once was some checks for this in the code in the past it was commented out.  This commit is a revised version of a pull request (#370) originally aimed at the release_30 branch but which has changed so much it was easier to restart from a more up to date point.
This version checks the "version" attribute of the `MudletPackage` element of most types of XML files read (not Maps) and will allow through without comment a string value that works out to a float less than `2.000f` (three decimal place resolution) but will cause `XMLimport::importPackage(...)` to return a FALSE value - {the return is largely ignored currently} - to not read the file further and to cause an "[ ALERT ]" message on the main console should …
=> (release3_0_1)Enhance: restore version check to Mudlet XMLimport code

src/mudlet.cpp
Credit to patch at https://launchpadlibrarian.net/147506428/profile_dialogue_patch.diff from SlySven.
Fixes https://github.com/Mudlet/Mudlet/issues/610.
=> Fixed main window buttons getting enabled when you hit Cancel

src/ui/trigger_editor.ui
There was a constraint set on a parent widget that prevented the `QComboBox` that is used to enter search terms from re-sizing itself to accommodate larger text than the form was originally designed for.
This commit removes that constraint and should prevent the clipping that was reported to be occurring.
=> BugFix: prevent clipping of Editor search term entry widget

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/mudlet.cpp, src/mudlet.h
Allows Mudlet Lua scripts to simply save and close open profiles and then closes the application.
Botman uses Mudlet like it is a service and sometimes the service needs to be restarted by admin users of the Botman service.  This function allows Botman to script the entire restart process so service admin users can instruct the service to restart via command input and don't need to use remote desktop to restart the application and botman services.
=> Added Lua closeMudlet() 

src/glwidget.cpp
glColor4b uses signed bytes and represents the range -1 to 1.
glColor4ub uses unsigned bytes and represents the range 0 to 1.
I think the colors specified through glwidget.cpp are intended to
have 0 to 255 represent 0 to 1, as opposed to what actually
happened, which is that any value above 127 became negative
and represented a negative color value.
=> Change glColor4b to glColor4ub.

CI/travis.osx.after_success.sh
This fixes some issues with the deployment of tags for macOS:
- `mudlet.org` was not among the known hosts. We skip the check now, as the kkeys get added at startup time only anyways.
- `DEPLOY_URL` was never properly set
@Mudlet/infrastructure should review this
=> Fix tag deployment

src/T2DMap.h, src/TAction.cpp, src/TMap.h, src/mudlet.cpp
Also use whitespace to reenforce the association between them.
=> Cleanup comments so that they are always just before their referent.

src/TLuaInterpreter.cpp
Since it has been decided that the Mudlet Lua API should not have the capability to report errors in using the API in a translated form the use of the Qt `tr(...)` function to mark such `QStrings` is not wanted.  This commit switches those usages to use the `QStringLiteral(...)` wrapper instead. As the strings concerned are each unique the known downsides of using this "non"-translatable `QString` wrapper should not be significant and the code "template" for the two things are very similar {if there are no second or second & third arguments in the `tr(...)` case} - the editing to switch to `QLatin1Strings` in the same location would be much more intensive.
Where the (formerly) translated `QString` is then passed to the Lua system there are some instances where `QString::toUtf8()` must be …
=> I18n: clear out translatable Lua error messsages

src/Host.cpp, src/Host.h, src/TConsole.cpp, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/dlgTriggerEditor.cpp
This introduces a new pattern we haven't used in Mudlet before - passing multiple return values to the Lua interface.
I haven't replaced all cases where we save the profile yet with the overarching ``Host::saveProfile()`` yet - will do that after people agree this style is a good one to go with.
=> Added saveProfile()

src/TLuaInterpreter.cpp
Applied i18n guidelines and improved the message to be a lot more intuitive: it still concisely describes the problem yet also offers the obvious solution at once. I'm not sure if the `! pHost->mpMap->mpRoomDB` check is necessary anymore but it doesn't hurt to leave it in.
Fixes https://github.com/Mudlet/Mudlet/issues/945.
=> Fixed crash on centerview() with no map open.

src/TBuffer.cpp
Found missing braces was allowing some code to execute when the item it
was trying to reference did not exist.
=> BugFix: getting crashing at start of session

CI/travis.after_success.sh, CI/travis.osx.after_success.sh
When changing the way the BUILD part of the version is specified, I forgot
to change the variable used in the after_success travis hook. This should be
fixed now.
=> Use MUDLET_VERSION_BUILD env var instead of BUILD

src/Host.cpp, src/Host.h, src/TBuffer.cpp, src/TBuffer.h, src/TTextEdit.cpp, src/XMLexport.cpp, src/XMLimport.cpp, src/dlgProfilePreferences.cpp, src/ui/profile_preferences.ui
Using timeBuffer list, which is avaiable even when Show Time Stamps is turned off.
Both for html and txt log formats.
=> Enhance: added timestamps to log file.

src/mudlet.cpp
Additions made in PR #951 created a crash condition when closing Profile tabs that have opened TDockWidget consoles and have not closed them before closing the profile.  
This patch adds a loop which calls `->close()` on all DockWidgets associated with the profile being closed.
=> Fix DockWidgets to close with associated Profile.

src/TMap.cpp
This means that maps will now be saved in map format 18 by default and will require Mudlet 3.0.0 at minimum to load.
This is part of the release process.
=> Updated default map format to 18

src/TLuaInterpreter.cpp
The error (4 instances) is not harmful and it is ineffective code; however code analysers are moaning about this error and there is no reason not to correct by removing the `L, ` that has been inserted into the condition code for some "if"s in the Lua commands that set up events for `TLabels`.
=> BugFix: remove typo made in previous work

src/mudlet.cpp
Found issue https://github.com/Mudlet/Mudlet/issues/1003 when debugging something else, the code that causes a `sysSoundFinished` event to be sent to the `Host`(profile) that started the sound playing was storing a pointer to that `Host` and attempting to use it even when it had been destroyed, specifically when multi-playing...
This solves the issue by ensuring the code used a `QPointer` to retain the address of the `Host` instance which will automatically be zeroed when the `Host` is destroyed and by now testing the pointer value before using it.
=> BugFix: prevent long-playing sound crashing Mudlet if starting Host gone

src/TRoomDB.cpp
While there was already code that ensures a map has the Default (reserved) -1 area when a file is loaded in and when the existing one is cleared by `TRoomDB::clearMap()` there was nothing to ensure this state for a new profile with no pre-existing map data.
This seems to be the cause of both Issues:
* https://github.com/Mudlet/Mudlet/issues/1001
* https://github.com/Mudlet/Mudlet/issues/1002
IMHO and the commit here should address both.
=> BugFix: ensure there is always a "Default" map area

src/XMLexport.cpp, src/XMLexport.h, src/XMLimport.cpp, src/XMLimport.h, src/mudlet.cpp
We use XML to save Mudlet game data including the scripts that contain Lua code for all of the Mudlet item {Alias|Button|Key|Timer|Script|Trigger} but because the former (at version 1.0 which is all that the Qt library code handles) prohibits all but Horizontal Tab, Carriage Return and Line Feed out of the range of ASCII control codes it means that a user trying to embed a raw string containing, say, the ESC code (0x1b) will either lose their code for just the item containing that code OR everything that follows it in the file that it is being loaded from.  As that could be the game save data this may will cause data loss.
This commit allows all but the ASCII NULL (`\0`) character code to be stored as it replaces the remaining control codes with a pair of other Unicode code-points that …
=> BugFix: allows most ASCII control characters to be used/saved in Lua Code

src/TRoomDB.cpp
A user reported that they were constantly getting:
"--------------------------- Area id: ### --------------------------------
[ ALERT ] - Area with this id expected but not found, will be created."
error messages on loading in a map.  It turned out that although there was code to detect when there was an Area Name for an area or one or more rooms that claimed to be in an area but no such area existed;  there was NOT code to actually create that area should it have a positive id number (and thus be a valid one) but not actually be present in the map. If the area had an invalid id (0 or <-1) it would have been handled!
This commit addresses that issue; should there be an existing area name for the missing id than it will persist and be used, but the now established non-blank and unique …
=> BugFix: insert new TArea instances for wanted but absent ones on map load

src/T2DMap.cpp, src/TMap.cpp, src/dlgConnectionProfiles.cpp
Qt docs say it maps to [Qt::transparent](http://doc.qt.io/qt-5/qt.html#GlobalColor-enum).
=> Improved QColor(0, 0, 0, 0) readability

src/AliasUnit.cpp, src/AliasUnit.h
I don't think these variables have any practical effect, but I want the typos gone anyway.
=> Fixed 'aliass' typos

src/dlgProfilePreferences.cpp, src/ui/profile_preferences.ui
I wanted to document the map format improvements but found the location of mapper-related options to be unsatisfactory and not where they should be.
I've moved the map options from special settings (they're not special settings) to correctly be map options . I've also improved the tooltip for downgrading a map to be a lot more concise and friendly-sounding since that might be a fairly common operation people have to do until we make updating Mudlet be super easy and automatic.
=> Moved map options to be in map options

.travis.yml
qmake doesn't seem to honor the `CC` and `CXX` environment variables. That means we need to specify the compiler toolchain manually.
=> Tell qmake on travis to use clang on linux

src/Host.cpp, src/T2DMap.cpp, src/TAlias.cpp, src/TConsole.cpp, src/TLuaInterpreter.cpp, src/TMap.cpp, src/TRoom.cpp, src/TRoomDB.cpp, src/TTextEdit.cpp, src/TTrigger.cpp, src/XMLimport.cpp, src/ctelnet.cpp, src/dlgConnectionProfiles.cpp, src/dlgIRC.cpp, src/dlgMapper.cpp, src/dlgProfilePreferences.cpp, src/dlgRoomExits.cpp, src/dlgTriggerEditor.cpp, src/mudlet.cpp
Saves on memory allocations and it's especially useful in some performance-critical functions like the mapper paint event.
This would need a thorough review to avoid issues like https://github.com/Mudlet/Mudlet/issues/999 again.
Fixes https://github.com/Mudlet/Mudlet/issues/903.
=> Replace chained .args with multi-arg

src/Host.cpp, src/mudlet.cpp
I've tested this with the tempTimer and with the profile provided for MidnightSun2 and this seems to do the trick, in those cases at least. I'm hopeful this will resolve Issue #512 
All this really does is attempt to raise the disconnection event earlier by disconnecting the telnet client earlier in the closing processes rather than disconnecting it in the destructor for the host itself.  
**Edit:**  to clarify, this causes the `sysDisconnectionEvent` to be raised a bit earlier when closing a host profile or Mudlet itself, which should mean all our host windows, labels, etc., etc. are still in-memory for use by Lua.
=> Proposed fix for sysDisconnectionEvent related crash

src/ui/triggers_main_area.ui
I think it's pretty important to mention that `matches` won't work anymore and people need to use `multimatches` instead. Removed the redundant text on reading the manual if you don't understand something - obviously you'll go read the manual if you don't get what to do.
=> Clarified tooltip that AND trigger captures go into multimatches

src/ActionUnit.cpp, src/ActionUnit.h, src/TAction.cpp, src/TAction.h, src/TToolBar.cpp, src/TToolBar.h, src/dlgTriggerEditor.cpp, src/mudlet.cpp
This PR focuses on making Floating Toolbars more usable and addressing bugs with the `TToolBar` object and its related parts.   In short this PR has made the following changes:  
1.  Fixes bug where Floating Toolbars were not closed with their Host Profile.
2.  Changes how Floating Toolbars are constructed, to avoid pulling the Editor Dialog away from the user abruptly.
3.  When Floating Toolbars are docked they get rebuilt in the same place you left them last, unless you delete them or restart the host profile.
Before this set of changes Floating Toolbars would create frustrating usability conditions.  
While a Floating Toolbar is active, clicking any of the Toolbars, Menus, or Buttons (`TAction`) items in the Editor Dialog window would result in the main window being raised and shown. …
=> Fix some TToolBar bugs.

src/mudlet.cpp
This makes Mudlet feel a lot more snappier when it's launching. Can't go below 50ms because X11 is async and the window doesn't get painted before that.
Should double-check this still looks ok on macOS and Windows.
=> Reduced autologin delay by nearly a second

src/TMap.cpp, src/TRoomDB.cpp
A code structure error in a prior fix meant that instead of sorting the missing areas if there was more than one such area BEFORE creating them ALL, the corner case of a single missing area was not being created as required.
Also move two chained `QString::arg()` usages into a single instance as per new coding guidelines - as the first is a number it is necessary to force it to a `QString` to avoid a compile failure (in later Qt versions ?) that have a twin argument overload that expects a first number argument to be followed by a second numeric value being a width specifier.
Also re-layout a few related console messages to avoid hitting a default re-wrapping width at 80 characters.
=> BugFix: create missing area when there is only one missing

src/run-lua-code-v4.xml
Somehow the new default is to put in even more empty fields into the file :|
Tagging @Mudlet/lua-interface for review.
=> Updated the default run lua code script

src/KeyUnit.cpp, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h
Bug fixes for issue(s) raised in: https://github.com/Mudlet/Mudlet/issues/1068
* in `TLuaInterpreter::permKey(...)` corrected `luaL_typename(...)` calls to refer to correct argument instead of hard-coded `1`.
* in `TLuaInterpreter::permKey(...)` and `tempKey(...)` corrected tests for strings for optional third and required fourth to be the number ones as that is what we want them to be interpreted as; edited the type error message to match; revised the error message to the `keyModifier` argument to refer to it as optional as it is!
* in `TLuaInterpreter::tempKey(...)` forced the error message generation to no longer be subject to potential translation efforts following the decision already implemented elsewhere in the class NOT to I18n these texts.
* in `TLuaInterpreter::permKey(...)` and …
=> BugFix: multiple issues with TKey creation from lua script commands

src/mudlet-lua/lua/Other.lua, src/mudlet-lua/tests/Other.lua
We all know [the pain](https://github.com/Mudlet/Mudlet/blob/development/src/src.pro#L21) of not having a proper function to do version comparison, so we shouldn't inflict it on Mudlet users.
Makes it easy to write `if mudletOlderThan("3.2") then return end` in case some features cannot be checked in the preferred way of `if desiredMudletFunction then` such as coroutine support - coroutines were always present and would instantly crash the application if you tried to use them. There's no way to check for that sans checking the major+minor version.
I've also dumped some tests but as busted doesn't work, they're incomplete. Somehow busted's [tests are passing](https://travis-ci.org/Olivine-Labs/busted) so we'll have to see how do they make it work.
Tagging @Mudlet/lua-interface for review.
=> Added mudletOlderThan()

src/mudlet-lua/lua/Other.lua
If you want to check if Mudlet has a certain function, you can do something like `if echo then`. If you want to check if Mudlet has a certain feature, you can't. I started on #1064 as a misguided attempt to solve this, but making people sprinkle random version numbers in their code is a terrible idea, starting with poor readability.
Instead, we could have a `mudlet.supports*` values where we could put such Lua-unarticulatable feature flags in - so in case of coroutines for example, you could do `if mudlet.supportscoroutines then`. Nice and readable! 
As coroutines are a new feature in 3.2 and using them in 3.1 or below completely crashes the application, I'd like to have this toggle in so people can start writing code the right way from the start.
(it would be nice if it could be …
=> Add mudlet supports coroutines

src/TLuaInterpreter.cpp
This allows you to do things right like:
```
lua string.len("привет")
12
lua utf8.len("привет")
6
lua string.upper("привет")
"привет"
lua utf8.upper("привет")
"ПРИВЕТ"
```
The Lua library we'll be using [starwing/luautf8](https://github.com/starwing/luautf8), it is very popular and has been confirmed by an independent third party that it works fine in production (http://notecasepro.com has used it for years).
Most of the work will not be in this PR but documenting all of the utf8 functions on our wiki and updating all installers to include it. I hope this won't take long to merge so I can get started on the documentation and installers efforts.
Fixes https://github.com/Mudlet/Mudlet/issues/854.
=> Added utf8 Lua module

src/TConsole.cpp
This adds a call to save the window layout of Mudlet when closing a profile which is marked for auto-saving on exit.    Hopefully this will address Issue #1075 and if not it should at least prevent similar issues on platforms we know are able to use the window layout methods.
=> Adds saveWindowLayout() call to ForceSaveOnExit processing.

src/TBuffer.cpp, src/TTextEdit.cpp
import: some fixes by Zoilder from the MudletRL fork:
* in `TBuffer::translateToPlainText(...)`: make some MXP related code execute   only if `Host::mFORCE_MXP_NEGOTIATION_OFF` is NOT set as well as another condition.
* in `TBuffer::wrap(...)`: change a `for(...) {...}` loop termination condition be a `<` rather than a `<=` test - which sounds like an "off-by-one" error fix-up.
* In `TTextEdit:updateScreenView()`: revise code that seems to prevent the width of a "main" console being set too small and NOT written to the "parent" `Host::mScreenWidth` variable - the original modification removed such a restriction completely, but I have just lowered the minimum from 100 to 40 and ensured it is always stored both in the local "main" console and to the parent record in the `Host` class for …
=> BugFix: import some fixes by "Zolder" from Mudlet Realms of Legend Fork

src/mudlet.cpp, src/mudlet.h, src/src.pro
Should only be sending the events to whichever window is active, but I could be mistaken. Needs some testing. Note that for Windows users, you're limited to XInput devices, like Xbox 360/One controllers, some 3P controllers, and PS3 and PS4 controllers if you use the right software to spoof XInput with them. Other OS's should have access to all gamepads, although the QGamepad class is only really meant to handle Gamepads ala: https://en.wikipedia.org/wiki/Gamepad and might not function with joysticks/etc
=> Event-based gamepad functionality

src/dlgProfilePreferences.cpp
This should address the Coverity issue in the IRC related code additions.
=> initialize int nIrcPort with dlgIRC::DefaultHostPort value [Coverity]

src/TLuaInterpreter.cpp, src/dlgIRC.cpp
maps any `false` + status return value to a nil + error format, and ignores return values from `connection->sendCommand()`
=> Removes false from sendIrc() return, ignores command filtering status

src/mudlet-lua/lua/Other.lua
Enforce uniform locale so scripts don't get tripped up on number representation differences (. vs ,)
Tagging @Mudlet/lua-interface for review.
=> Fix locale to C in Lua

src/TBuffer.cpp
It'll now return the original value passed - it's way better than returning the wrong value.
=> Fixed getComputerEncoding in case no key found

src/T2DMap.cpp, src/dlgProfilePreferences.cpp, src/mudlet.cpp, src/mudlet.h, src/ui/profile_preferences.ui
Per user feedback on https://github.com/Mudlet/Mudlet/issues/1079, removed statusbar. It has done its purpose well and we've now superceded it with a connections dialog that comes up automatically, and as of this PR, tooltips in the right-click menu.
=> Remove mainwindow statusbar

src/Tree.h
_Edited: This should, IMHO, fix #1174 (I got the number wrong twice!) ..._
I think that that absence of an initialisation value for the `(bool) mTemporary` flag recent moved out of the Mudlet "items" derived classes and down to the base class was causing these issues as "temporary" items are not shown in the editor and not saved at the end of a session.  Technically a value of not zero is a `true` value according to C coding standards but C++ tends to use the specific integer values of `0` and `1` (not `-1`) for `false` and `true` - I suspect there was some ambiguity when another value was being seen when a derived item was instantiated without this boolean being set to a definite value.
I have taken the liberty to also go through and mark the template file up for `const`ness... and also …
=> BugFix: stop items being hidden in editor & getting lost (Fix #1174)

src/TLuaInterpreter.cpp
setTextFormat had a bad if statement that was causing it to default to "main" any time the windowName argument wasn't actually "main" already, meaning it modified "main" 100% of the time.
=> Bugfix: fixed setTextFormat ignoring windowName argument

CI/travis.linux.after_success.sh
The uploaded tarball was gzipped, but only had a file ending of `tar`. This created issues in some environments with extracting the AppImage. Choosing `tgz` should fix those.
=> Don't gzip appimage tarballs

src/AliasUnit.cpp, src/KeyUnit.cpp, src/TLuaInterpreter.cpp, src/TRoomDB.cpp, src/TimerUnit.cpp, src/TriggerUnit.cpp
We were using mising constant and non-constant iterators, and the non-constant ones can detach in Qt (https://wiki.qt.io/Iterators#QT_STRICT_ITERATORS).
Credit to https://github.com/KDE/clazy/blob/master/src/checks/level0/README-strict-iterators.md for discovering the issues.
=> Fix incorrect iterators use in searching

src/mudlet.cpp
It is funny that above in echoWindow() the same thing is done and then _that_ argument is passed to the function.
=> Remove unused QString, not adding any value.

src/TTextEdit.cpp, src/TTextEdit.h
y sometimes was == size() of the buffer, so an off-by-one error.
Also fixed an inefficiency in resetting the y for every x inside the for loop.
Possible fix for https://github.com/Mudlet/Mudlet/issues/796.
=> Possible fix for the highlighting crash

src/Host.cpp, src/Host.h, src/TBuffer.cpp, src/TBuffer.h, src/TTextEdit.cpp, src/TTextEdit.h, src/mudlet.cpp, src/mudlet.h
This commit removes the items identified in issue:
https://github.com/Mudlet/Mudlet/issues/1251 as of 2017/08/08 01:30
as being dead code.
=> Decruft: remove unused items from code-base

src/dlgTriggerEditor.cpp, src/ui/timers_main_area.ui
Now specifies a time value (of zero) for each of the time section entry spin-boxes instead of using `clear()` in: `dlgTriggerEditor::slot_timer_selected(QTreeWidgetItem *)` so they are left showing a zero if there is no previous value to display from an existing item. This should fix issue #1253...
Also:
* Refactors the setting of those same control widgets to eliminate some unneeded temporary intermediates variables.
* Adjusts the hours, minutes and seconds controls to show "00" instead of "0" - to reflect that they are divisions of time (00-24/00-59) rather than simple integers - bringing them into line with the recently "fixed" milliseconds.
=> BugFix: (Issue #1253) New timer starts with blank values

src/TRoom.cpp
The code to load a map into other profiles needs to scan through but not permanently store map data which includes the temporary creation of `TRoom` instances - unfortunately this was not being taken into account in the destructor for that class!
=> BugFix: (Issue #1280) TRoom d'tor causes crash when not made by map loading

src/mudlet.cpp
This is so they can be targetted by setAppStyleSheet selectors. This does mean that we can't change them nilly-willy them now either, since we'll be breaking skins people do for Mudlet.
=> Added names to toolbar buttons

CMakeLists.txt, src/mudlet.pro
This helps to avoid an initial failure to build should a developer not realise they need the separate edbee editor widget that Mudlet now uses.
Though this is documented in the Wiki, not everyone may RTFM and it can catch even experienced developers (including me) out should they start working on a fresh development platform...!
Signed-off-by: Stephen Lyons <stephen@Rachel.lyonsnet>
=> Fixup: ensure edbee-lib editor widget is present in src code

src/TLuaInterpreter.cpp, src/mudlet-lua/lua/Other.lua
Before it was only possible to register lua code as strings to events.
This resulted in either being unable to use closures for events (by writing
code as anonymous event handler) or littering the global namespace (by
giving a global function name as event handler).
This solution trades a single global function (as event handler) for the
ability to use local functions (or even lambdas) as event handlers.
I will add wiki documentation as soon as I know in which mudlet version this will land.
=> Allow to register lua function objects to events

src/mudlet.cpp
We were trying to assign an object name to a null pointer - the reason the pointer is null is that it was being obtained by searching on the main toolbar for a widget that had not YET been added to it temporarily for the replay..!
=> BugFix: correct crashing during replay initiation

src/dlgColorTrigger.h, src/dlgConnectionProfiles.h, src/dlgIRC.h, src/dlgKeysMainArea.h, src/dlgNotepad.h, src/dlgRoomExits.h, src/dlgSystemMessageArea.h, src/mudlet.h, src/ui/color_trigger.ui, src/ui/connection_profiles.ui, src/ui/custom_lines.ui, src/ui/custom_lines_properties.ui, src/ui/delete_profile_confirmation.ui, src/ui/irc.ui, src/ui/keybindings_main_area.ui, src/ui/lacking_mapper_script.ui, src/ui/main_window.ui, src/ui/module_manager.ui, src/ui/notes_editor.ui, src/ui/package_manager.ui, src/ui/package_manager_unpack.ui, src/ui/room_exits.ui, src/ui/set_room_area.ui, src/ui/system_message_area.ui
Previous experiments/dry-runs have pointed out to me that some forms have "class" and possibly "widget" attribute names that do not match their file name and one of those is used to provide the "context" for the translation files so that an identifier is used that did not match the context! This commit renames the class/widgets to match the defining files but requires  that the C++ classes {marked by "INHERITED BY:" below} that use them to revise what they are derived from; the renaming (in ui file the same as the NEW name with a .ui extension and files affected) are:
* "_old name_" -> "_new name_" ==> _what is involved/used it_
* "color_trigger_dlg" -> "color_trigger" ==> INHERITED BY: `dlgColorTrigger` class
* "profile_dialog" -> "connection_profiles" ==> INHERITED BY: …
=> Refactor: tweak some form/dialog details

src/dlgSourceEditorArea.cpp, src/ui/about_dialog.ui, src/ui/actions_main_area.ui, src/ui/aliases_main_area.ui, src/ui/color_trigger.ui, src/ui/composer.ui, src/ui/keybindings_main_area.ui, src/ui/module_manager.ui, src/ui/notes_editor.ui, src/ui/package_manager.ui, src/ui/package_manager_unpack.ui, src/ui/room_exits.ui, src/ui/scripts_main_area.ui, src/ui/system_message_area.ui, src/ui/timers_main_area.ui, src/ui/trigger_editor.ui, src/ui/trigger_pattern_edit.ui, src/ui/triggers_main_area.ui, src/ui/vars_main_area.ui
Several forms/dialogues do not need a title (because they are incorporated into other forms; others that are floated free have their title set elsewhere - in both cases it is advantageous to remove strings that do NOT need to be made translatable when Mudlet is localised into a language and they just pollute the code/make extra strings that would automatically be marked as needing translation - so removing them is mildly useful.
The "composer" form/dialog used for certain MUDs had the title: "__News & Message Composer__" whereas it is simpler for translation to turn the "&" back to "and" as that character has to be escaped in XML files such as the ".ts" ones we will use to make "translations" and it may not display as the original in Qt Linguist (I think it will get replaced by its …
=> Refactor: remove unneeded dialog titles from some forms + other tweaks

src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h
There were a whole lot of cases where the error should have been shown or hidden.
Fixes #1292 which really comes to light once you start using the `Ctrl+S` shortcut or hitting the `Save Item` button for saving stuff.
=> Fixed error notifications showing or hiding right

src/TConsole.cpp
In the case someone repeatedly searched for the same thing, the last search result happened to be right at the top of the buffer, and then the buffer was shrunk because some lines were batch deleted, the index to start searching lines from was never adjusted - and caused a crash.
This should fix it by choosing a minimum available value of the total lines or the last index to search from.
Fixes https://github.com/Mudlet/Mudlet/issues/497.
=> Fixed a rare crash with search

src/TBuffer.cpp, src/TBuffer.h, src/TConsole.cpp
Before this, logging would first log the previous prompt - and then when the player command was received, it would log the prompt _again_ with the command. It looked like this:
```
6800h, 9300m, 6300e, 10p elrx<>-
6800h, 9300m, 6300e, 10p elrx<>-x
You see a single exit leading down.
6800h, 9300m, 6300e, 10p elrx<>-
6800h, 9300m, 6300e, 10p elrx<>-x
You see a single exit leading down.
6800h, 9300m, 6300e, 10p elrx<>-
```
This fixes that and only logs the line as you actually see it:
```
6800h, 9300m, 6300e, 10p elrx<>-x
You see a single exit leading down.
6800h, 9300m, 6300e, 10p elrx<>-x
You see a single exit leading down.
6800h, 9300m, 6300e, 10p elrx<>-
```
=> Fixed logging not to double-log the prompt

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h
Makes
```lua
expandAlias("command", nil)
```
Be treated same as:
```lua
expandAlias("command")
```
Because it should be the same per Lua convention. Fixes https://github.com/Mudlet/Mudlet/issues/582
=> Fix expandAlias("command", nil) not working

.travis.yml
The repository we need to use for Qt 5.9.x has a different name and the old one had gone away - causing Travis Builds to fail on Linux.
=> BugFix: a recent update to Qt 5.9 to 5.9.1 broke Travis CI testing

.travis.yml, src/FontManager.cpp, src/Host.cpp, src/TConsole.cpp, src/TLuaInterpreter.cpp, src/TMap.cpp, src/ctelnet.cpp, src/dlgConnectionProfiles.cpp, src/dlgConnectionProfiles.h, src/dlgIRC.cpp, src/dlgNotepad.cpp, src/dlgPackageExporter.cpp, src/dlgProfilePreferences.cpp, src/dlgTriggerEditor.cpp, src/main.cpp, src/mudlet.cpp, src/mudlet.h
Using a static method means that we can centralise the generation of strings used to access parts of the file system used to hold Mudlet user data - which may be useful if we change them for - say running from a thumb-drive or just to use an OS specific location for them. {Using a ".config/mudlet" sub-directory on Windows is not quite how that OS expects things to be done...!}
This also reduces the number of raw strings that will have to be wrapped in `QStringLiteral(...)` and the like for forthcoming __I18n__ work.
Also:
* The use of "mudlet-data" as a windows symlink sub-directory to ".config/mudlet" in the user home directory may not work because the Qt Documentation suggests that a ".lnk" extension is required - this commit adds that __FOR THAT OS ONLY__.
* Previous code placed (only …
=> Refactor: reduce use of raw string literals for directories and file paths

src/Host.cpp, src/mudlet.cpp
In #1286 I made what I think is a copy paste error and ended up with the wrong string being used in: `(bool) Host::installPackage(const QString&, int)` for the directory to be used to unzip (archive) file format packages/modules (there was a `/` missing between the profile's HOME directory name and the "packageName" of the concerned module being the file name contained in the `config.lua` should that differ from the base name of the archive file).
For archives where all the files are contained in a single directory the effect is to create a folder/file in the wrong place in the mudlet part of file-system and to expand all the modules in the profile's HOME directory (the fact that they all contain a file called `config.lua` is not an issue as the modules are unpacked in sequence and that …
=> BugFix: module/package handling error

src/dlgAliasMainArea.cpp, src/dlgAliasMainArea.h, src/dlgScriptsMainArea.cpp, src/dlgScriptsMainArea.h, src/dlgTimersMainArea.cpp, src/dlgTimersMainArea.h, src/dlgTriggerEditor.cpp, src/dlgTriggersMainArea.cpp, src/dlgTriggersMainArea.h
The save function do trim the name before saving. 
This happens in the relative `QLineEdit editingFinished` slot as well, in an attempt to alleviate the copy/paste issue before saving as reported in issue #1119 
I'm not sure this solution respects the project standard so please, double-check and let me know.
=> Trim sensitive name in editor

.travis.yml, CI/appveyor.after_success.ps1, CI/appveyor.install.ps1
Added a [random PPA](https://launchpad.net/~jonathonf/+archive/ubuntu/php7?field.series_filter=trusty) I found that has a newer libzip. I'm not certain if it has the development headers, however.
We need the ZIP_FL_ENC_UTF_8 flag to support encoding i18n names for 4.0.
Addresses issues @SlySven's been running into [here](https://gitter.im/Mudlet/Mudlet?at=59e252ac614889d475b4ef74) and [here](https://github.com/Mudlet/Mudlet/pull/1355#issuecomment-339213256).
=> Up libzip requirement to 1.x for Unicode support

src/mudlet-lua/lua/Other.lua
As per #835, some tests were made that show `setExit()` is no longer needed in mudlet-lua. After removing the duplicate code and testing the function in Mudlet, these were the results:
```
lua addRoom(createRoomID())
true
lua addRoom(createRoomID())
true
lua getRooms()
{
"",
""
}
lua setRoomName(1, "Room One")
true
lua getRooms()
{
"Room One",
""
}
lua setRoomName(2, "Room Two")
true
lua getRoomExits(1)
{}
lua getRoomExits(2)
{}
lua setExit(1, 2, "south")
true
lua getRoomExits(1)
{
south = 2
}
lua setExit(2, 1, "north")
true
lua getRoomExits(1)
{
south = 2
}
lua getRoomExits(2)
{
north = 1
}
lua addRoom(createRoomID())
true
lua setRoomName(3, "Room Three")
true
lua setExit(1, 3, "e")
true
lua setExit(3, 1, "d")
true
lua getRoomExits(1)
{
east = 3,
south = 2
}
lua getRoomExits(3)
{
down = …
```
=> Remove duplicate setExit() from mudlet-lua

src/TBuffer.cpp
I forgot to initialise the two new variables, added them to the constructor.
Less Coverity warnings.
=> Fix untinitialised scalar value

src/TLuaInterpreter.cpp
Removed an unnused variable in `tempComplexRegexTrigger()`.
Less static analyser warnings, the better.
=> Removed unnecessary Lua interpreter init

src/ActionUnit.cpp, src/TTrigger.cpp
Applied clang-tidy's `modernize-use-emplace` to use `emplace_back` instead of `push_back` where we can.
`emplace_back` constructs the object in-place instead of creating it first and then copying or moving it over: http://en.cppreference.com/w/cpp/container/list/emplace_back
=> Apply modernize-use-emplace

src/XMLexport.cpp
This commit should address the above issue in:
`(bool) XMLexport::exportToClipboard(TTrigger*)`
It also removes some unneeded bits of code in that and the other `exportToClipboard(`...`)` methods and adds explicit `close()` calls for the temporary `QBuffer` entities created.
See [Coverity-1459636](https://scan7.coverity.com/reports.htm#v27731/p14359/fileInstanceId=38807038&defectInstanceId=8378712&mergedDefectId=1459636)
=> BugFix: Coverity 1459636 Unchecked return value

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/TTrigger.cpp, src/TTrigger.h, src/dlgTriggerEditor.cpp, src/ui/trigger_pattern_edit.ui
Adds a `prompt` trigger pattern and `tempPromptTrigger()` Lua function.
Addresses https://github.com/Mudlet/Mudlet/issues/1353 as well as [feedback here](http://forums.achaea.com/discussion/comment/379459/#Comment_379459). 
tempPromptTrigger() was also a useful function, for example I had to define my own in in [Svof](https://svof.github.io/svof/#svo.prompttrigger).
Download preview Mudlet:
[Windows](https://ci.appveyor.com/api/buildjobs/4wi1ukxsyr1ihjo0/artifacts/src%2Fmudlet.zip)
[macOS](https://transfer.sh/7U9xZ/Mudlet-3.5.0-testing-PR1373-a554288.dmg)
[Linux](https://transfer.sh/auhil/Mudlet-3.5.0-testing-PR1373-a554288-linux-x64.AppImage.tar)
=> Added prompt pattern type trigger

src/ActionUnit.cpp, src/AliasUnit.cpp, src/KeyUnit.cpp, src/ScriptUnit.cpp, src/TimerUnit.cpp, src/TriggerUnit.cpp
Removed unnecessary null check, it was confusing the static analyser:
```
Logic error: Called C++ object pointer is null
1: Assuming 'pChild' is non-null in /home/vadi/Programs/Mudlet/mudlet/src/TimerUnit.cpp:112
2: Value assigned to 'pChild' in /home/vadi/Programs/Mudlet/mudlet/src/TimerUnit.cpp:122
3: Assuming 'pNewParent' is non-null in /home/vadi/Programs/Mudlet/mudlet/src/TimerUnit.cpp:124
4: Assuming 'pChild' is null in /home/vadi/Programs/Mudlet/mudlet/src/TimerUnit.cpp:126
5: Called C++ object pointer is null in /home/vadi/Programs/Mudlet/mudlet/src/TimerUnit.cpp:134
```
Line 4 is will never happen since it's guarded by TimerUnit.cpp:112.
Less warnings in the analyser the better.
=> Removed unnecessary null check

src/ctelnet.cpp, src/glwidget.cpp
Fixed a few cases where [cppcoreguidelines-pro-bounds-constant-array-index](http://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-bounds-constant-array-index.html) was lighting up.
The reason why is started looking into was for unsafe use of `[]` to read a value, however, this was flagging writes as well with the following:
>  do not use array subscript when the index is not an integer constant expression; use gsl::at() instead
Can't say I understand it but making the index be a const variable seems to do the trick.
Seems like a good thing to do.
=> Fix a few cppcoreguidelines-pro-bounds-constant-array-index warnings

src/dlgProfilePreferences.cpp, src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h, src/mudlet.cpp, src/mudlet.h
The code that sized/resized the main (and replay) and editor toolbar icons and editor treeWidget icons was inconsistent - when adjusted in the preferences it only adjusted the editor of the current profile even if others were also present.  Also some methods had an argument to receive the size setting but ignored it and read the value directly from the variable that stored it in the `mudlet` class.
Also:
* converted some tabs in the source code to spaces.
* added `mudlet::setToolbarVisible(bool)` and `mudlet::setMenuBarVisible(bool)` to simplify the coding when the relevant mudlet class items had their visibility adjusted in the preferences dialog.
* added code to ensure replay toolbar also gets it's icons adjusted when the main one to which it is docked gets adjusted.
Signed-off-by: …
=> Refactor: de-spaghetti-fy toolbar & editor treeWidget icon sizing code

src/TLabel.cpp, src/TLabel.h
This commit mostly resolves Issue #764 
Added workaround for the mapper not receiving mouse events while
sharing space with a Label. This commit checks mouse click events in
Labels before allowing the Label to process the event. If the topmost
element at the cursor position is a child of the QWidget with
objectName "mapper", the event is manually redirected to that element.
This commit also adds overrides for wheelEvent and mouseMoveEvent to
the TLabel class, for redirection purposes.
The only unresolved issue is the 3D map not being drawn over Labels.
=> Fix mapper not receiving mouse events while sharing space with Labels

src/TLabel.cpp, src/TLabel.h
Added map to TLabel.h to map Qt::MouseButton to strings, which, upon TLabel::mousePressEvent or TLabel::mouseRelease events, are appended to the existing callback parameters. Appending the string in this manner prevents breaking existing Mudlet scripts.
Allows more customization for GUI makers
Originally #1398, felt like the changes/scope warranted a different PR
=> Add support for all Qt::MouseButton to label click/release callback

src/Host.cpp, src/Host.h, src/TTextEdit.cpp, src/XMLexport.cpp, src/XMLimport.cpp, src/dlgProfilePreferences.cpp
...when loading a profile with no SearchEngineName. #1378
tested switching 3.5 release to 3.5 development. Defaults to Google.
Everything relates to `QMap mSearchEngineData` built in the Host constructor so we can just save the `mSearchEngineName` to the profile and get what we need through `getSearchEngine()`.
If you'd like to manage this in a different way please let me know.
=> Fix Search Engine not defaulting to anything

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h
The majority of code in TLuaInterpreter functions
setLabelClickCallback, setLabelReleaseCallback, setLabelOnEnter,
setLabelOnLeave was repeated, with the only difference being the
function to set the callback to. This commit condenses the
repeated code to a new function setLabelCallback. This will
facilitate the addition of label callbacks in the future.
This change will facilitate the addition of more label callbacks, 
including mouseDoubleClick, mouseWheel, and mouseMove
events.
=> Condense repeated code in TLuaInterpreter's label callback methods

src/HostManager.cpp, src/HostManager.h, src/dlgConnectionProfiles.cpp, src/dlgProfilePreferences.cpp, src/dlgProfilePreferences.h, src/mudlet.cpp, src/mudlet.h, src/ui/profile_preferences.ui
This modifies the profile preferences dialogue so that all the non-profile specific options are on the first tab and all the ones on that tab that are profile specific are moved elsewhere on the dialogue.  It then disables all but the first tab if the constructor is called with a `nullptr` value for the `Host *` argument.  This is so that it is possible to access the dialogue even when there is NOT a profile loaded.  The `dlgProfilePreferences` class methods are also made fully safe should `(Host *) dlgProfilePreferences::mpHost` be a `nullptr`...
I am doing this in anticipation of it being necessary to be able to access the _settings_ on start-up when perhaps there are issues locating the translations files or if there are problems in determining which one to use - it also seemed a …
=> Refactor separate per profile settings from general ones

mudlet.desktop
Added a super-vital `;` to the string list...
Fixing CI builds to work, they are broken right now as these pedantic issues are now treated as errors.
See https://standards.freedesktop.org/desktop-entry-spec/latest/ar01s05.html for details.
```
/home/travis/build/Mudlet/installers/generic-linux/build/mudlet.desktop: error: value "3.5.0-testing-PR1413-8324574" for key "Version" in group "Desktop Entry" is not a known version
/home/travis/build/Mudlet/installers/generic-linux/build/mudlet.desktop: warning: key "Encoding" in group "Desktop Entry" is deprecated
/home/travis/build/Mudlet/installers/generic-linux/build/mudlet.desktop: error: value "Game;AdventureGame;RolePlaying;ActionGame" for string list key "Categories" in group "Desktop Entry" does not have a semicolon (';') as trailing …
```
=> Fix .desktop file for Linux builds to work again

mudlet.desktop
AppImage validation is still complaining with:
> mudlet.desktop: error: value "1.1" for key "Version" in group "Desktop Entry" is not a known version
> ERROR: Desktop file contains errors. Please fix them. Please see
>        https://standards.freedesktop.org/desktop-entry-spec/latest/
>        for more information.
That is despite the standard clearly saying 1.1 is what should be used:
> Version of the Desktop Entry Specification that the desktop entry conforms with. Entries that confirm with this version of the specification should use 1.1. Note that the version field is not required to be present.
Fix AppImage builds to work.
=> Remove version information entirely

src/TDockWidget.cpp, src/TDockWidget.h, src/mudlet.cpp
By default calling `openUserWindow()` would load the window layout from disk each time it was called.  This behavior is normally OK except when the user is able to interact with the window layout state while the window layout state is being restored.  
The changes in this PR cause the layout to be loaded only once per each uniquely named UserWindow object which allow the `openUserWindow()` calls to be used within timers and prevent them from always reloading window layout data when called a second time.   
It patches a crash condition related to loading the window layout state at the same time as a user-initiated window Move event is being processed to update the current window layout state.  
- This PR addresses the crash condition in issue #1403  
- If the user needs to manually/force …
=> Patch UserWindow Crash condition

src/TConsole.cpp, src/TConsole.h, src/TLuaInterpreter.cpp, src/mudlet.cpp
This merges the font size handling (setFontSize, getFontSize) of UserWindow and MiniConsole.
The distinction is an older remnant, but from a user point of view, UserWindows and Consoles are not much different. There are examples of functions working for both types.
Simplify scripting for users.
=> Merge UserWindow and MiniConsole font size handling

src/dlgConnectionProfiles.cpp
pItem is allocated just before and not deleted when we skip out the loop. We normally don't have to delete it because Qt takes over the memory management when we add it to the treewidget.
Smidgeon less memory used.
This is where I wish Qt wasn't hampering us from using smart pointers :(
=> Fixed memory leak with predefined MUDs

src/mudlet.cpp
This fixes a possible issue of dereferencing a pointer first then checking for its existence.
A crash free(er) Mudlet!
=> Check for existance of TConsole pointer before using it

src/mudlet.cpp, src/mudlet.h
It seems that a recent change (the addition of the updater code) may have included code that modifies the `(bool)QtGUIApplication::quitOnLastWindowClosed` flag and that and/or the removal of the `qApp->quit()` call at the bottom of `(void) mudlet::closeEvent(QCloseEvent*)` seems to be why the Central Debug Console - if visible - prevents the Mudlet application from shutting down.  As far as I can tell the previous `mudlet::closeEvent()` only closed the `TConsole` instance inside the Console but it did not close the `QMainWindow` {pointed to in `(QMainWindow*) mudlet::mpDebugArea`} itself.
This commit seems to fix the issue by using the `close()` method of the `QMainWindow` rather then what is it's central widget (the `TConsole` that has the `isDebugConsole` flag set).  For safety's sake I …
=> BugFix: ensure Central Debug Console closes at application exit

src/main.cpp
When Mudlet is launched, the current behavior is to create a symlink to the  "\~/.config/mudlet" directory in the root of the user's home directory "\~/mudlet-data". This change causes Mudlet to only create this symlink if it is the first launch. This enables users to delete the symlink if they do not want it without it being recreated again the next launch.
I personally do not want the above mentioned symlink in my user's home directory and deleted it. When it reappeared upon launching Mudlet again, I was motivated to modify the source code.
=> Only create mudlet-data symlink on first launch. This enables users to delete the symlink if they do not want it.

src/dlgProfilePreferences.cpp, src/dlgProfilePreferences.h
The code that initialises the control of the updater must be initialised so that development versions do not have it enabled.  Unfortunate because two recent PRs (one of mine to allow the Profile Preferences to operate safely without a profile loaded and one of Vadim's to add the updater) both modified chunks of the `dlgProfilePrefences` class the merge algorithm allowed the new control for the updater to be placed in amongst other code that was shifted to only work when there WAS a profile loaded when
in fact it was an exceptional piece that should have stayed in the constructor.  As the code that had to be relocated was around half of a chunk that seems to have been hived off into a separate method `(void) dlgProfilePreferences::loadSpecialSettingsTab()` it was cleaner to re-position …
=> BugFix: ensure Updater option control works when no profile loaded

src/dlgProfilePreferences.cpp
As noted by issue #1433 the settings dialogue does not remember the currently used displayFont pointSize. This change updates the initializer list for dlgProfilePreferences to use the existing pointSize when initializing mFontSize instead of setting it to the hard coded value of 10.
Like the person who reported the issue, I also noticed that the settings dialogue did not remember the previously set value. I felt motivated to make this change so that I did not have to re-enter my preferred font size every time I open the settings dialogue.
=> fixes #1433 settings now uses existing pointSize

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/TTextEdit.cpp, src/TTextEdit.h, src/mudlet-lua/lua/geyser/GeyserMiniConsole.lua, src/mudlet.cpp, src/mudlet.h
Registering two new lua functions:
- `getColumnCount()`: Returns the number of characters than can fit on the width of a given window.
- `getRowCount()`: Same thing but using the height to calculate the number.
See issue #1438 
I've seen that Mudlet is already calculating the font width for a TTextEdit, but it takes into consideration the 'W' character (not the ' ' as discussed on the issue mentioned earlier) `mFontWidth = QFontMetrics(mpHost->mDisplayFont).width(QChar('W'));`. 
As discussed, I'm using the space, but if this were to change we could refactor `getColumnCount()` to use it and not calculate the width on each call.
=> Registering two new lua functions:

3rdparty/communi/include/IrcCore/ircglobal.h, src/dlgConnectionProfiles.cpp, src/mudlet-lua/genDoc.sh, src/mudlet.pro
Added a hash-bang entry to src/mudlet-lua/genDoc.sh
Commented out "almost illegal" `#define` of `_DEBUG_` to nothing in: `src/dlgConnectionProfiles.cpp` as that is reserved for _compilers' use_ in the C++ standards and should not be `#define`-d by the end user.
Removed some lines containing just a `#` character in `3rdparty/communi/include/IrcCore/ircglobal.h` as Codacy was reporting an un-closed `#if...#else` - the `#  endif` was present but it is not clear that isolated `#` characters are wise/safe to use in a C/C++ source code file.
Also added some non-source code files to main Qt project files including one modified by this commit so that they show up in the Qt Creator IDE.
=> Fixup: improve some things reported by Codacy

src/dlgTriggerEditor.cpp
In https://github.com/Mudlet/Mudlet/commit/5ce683b1b0e4b1037dee7702aaa872e8fbfdfa34 the writing of the (encoded) colour trigger data into the `(QLineEdit*) pItem->lineEdit_pattern` in `(void) dlgTriggerEditor::slot_trigger_selected(QTreeWidget*)` was removed if the trigger item is a colour one - probably because in that type that element is hidden from the user (as it was then also removed for the new Prompt type trigger).
This closes Issue #1468 .
=> BugFix: color triggers get erased in 3.6.1

src/TLuaInterpreter.cpp
Fix `setBold("miniconsole", true)` and friends to work again. They only previously worked on the main window.
Fixes a two year old regression.
They broke by the misleading QString::compare() function which returns 0 in a successful call. I've changed the style to use `== 0` everywhere instead of `!compare` as that would have been even more confusing.
=> Fix formatting functions to work on miniconsoles

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/mudlet.cpp
Adds Lua API support for move and resize calls on UserWindow instances using `moveWindow()` and `resizeWindow()` lua method calls.    
The method `TLuaInterpreter::resizeUserWindow` was changed to `TLuaInterpreter::resizeWindow` to follow related naming conventions.
The move and resize Lua methods work only on MiniConsoles and have less-than-helpful impact on the UserWindow instances.
=> Add UserWindow move and resize support.

src/mudlet-lua/lua/GUIUtils.lua
- Add: ansi2decho now can handle bold tags no matter if they are after or before any other ANSI codes.
- Add: ansi2decho now has a second optional parameter which allows it to handle the behaviour of orphan bold tags without a previous specified colour.
- Allow ansi2decho to better handle bold tags and ANSI codes.
- Proposal for #1473
=> [#1473] Extend bold support for ansi2decho

src/TLuaInterpreter.cpp
The option to set this format feature is optional (defaults to `false`) but the condition to check for enough arguments to control this was reversed so the code to set the option would be unreachable and so the option was never applied (and would clear it if set elsewhere, say with `setStrikeOut([window name], true)`.
This corrects the bug I mentioned I found in #1474 .
=> BugFix: allow Lua setTextFormat to control strike-out format correctly

src/TLuaInterpreter.cpp
=========== ALTERNATIVE B: Correct error messages to match code ===========
The code reported errors in the arguments to the Lua function as per the Wiki documentation at the time - but both were wrong in regard to how the arguments were actually used.
This will not break things for people who have already found out that the documentation was wrong and have ignored the discrepancies but it does fix the error messages to reflect how the code actually works.
The Wiki will need to be revised - possibly with an explanation of the defect in older version help texts.
I suspect that this is the better fix compared to the alternative PR #1480 - __only one should be merged__.
=> BugFix: correct fore/back ground being swapped in setTextFormat (Option B)

README.md
This adds a badge similar to the others for build status and gitter link but for the Mudlet Discord server.   
Using https://shields.io/ to create the discord badge.
Just to add another pretty badge to the list, for Discord. 
Working sample of the badge:  
[![Discord](https://img.shields.io/badge/discord-join%20chat-7289DA.svg)](https://discord.gg/kuYvMQ9)
=> Add a Discord badge/link to README.md

src/TLuaInterpreter.cpp
Fix the code formatter to load on macOS again.
Fix regression in 3.7.0.
Somehow `Q_OS_UNIX` was snuck in when we do not support UNIX as an operating system... and it introduced a regression by grabbing the wrong operating system, namely macOS.
=> Q_OS_UNIX goes off for macOS when the code is not intended to

src/dlgProfilePreferences.cpp
I think this was a merge error, but these are no longer needed as the selection of search engine is now determined when the profile preferences dialog is closed instead of being set immediately the control is adjusted.
The effects of them being present are run-time error messages because the specified slot function is no longer needed or present in the code.
=> BugFix: remove unneeded connect/disconnect(...) for Search Engine selector

src/TTextEdit.cpp, src/mudlet.cpp
In mudlet::getMudletPath, I chose to return an empty string, and in TTextEdit:getSelectedText, I returned whatever happens to have been added to the buffer before hitting the end of the loop. Maybe ideally, an error should be thrown as this code should never be reached, but at least this way it won't cause any other problems.
This patch adds default return values to two functions that did not have them. Technically this code should never actually be reached.
I'm creating an updated package for openSUSE Tumbleweed, and RPMlint would not let me continue with this problem.
=> Fix RPMLint msg: Returns random data in a function

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/mudlet-lua/lua/Other.lua
This will help my FreeBSD porting as the original script would return the incorrect string `"linux"` on that...!
=> Enhance: improve and extend lua OS platform identification getOS() command

src/main.cpp
This revision runs a GUI application on WINDOWS ONLY when the `-h`/`--help` or `-v`/`--version` command line options are given so that a `QMessageBox` can be used to display the information shown on the command line for other platforms.  This is because Windows makes it very hard/impossible to have an application that can be both run on the command line and as a GUI application.
This also reverts the "command line argument introducer" back to be `-` or `--` (the same as the other platforms) because that is what Qt applications use, even on Windows, where this is normally `/`...
_This is a single issue PR which I, perhaps unwisely, tried to bundle up with some other things, hopefully it will get in unchanged so it's effects will disappear from #1506... 🙏_ 
Signed-off-by: Stephen Lyons …
=> BugFix: get command line arguments for help and version working on Windows

src/LuaInterface.cpp
Upgraded variables code to allow i18n. 
i18n drive.
Unfortunately it exposes the problem that the variables code does not return errors properly, so if try to give the variable **name** a non-Latin value, it looks like crap. https://github.com/Mudlet/Mudlet/issues/1503
=> Enable variables tab to set Lua variables to non-Latin text

src/TConsole.cpp, src/TLuaInterpreter.cpp, src/TTextEdit.cpp, src/dlgConnectionProfiles.cpp, src/main.cpp, src/updater.cpp, src/updater.h
`Q_OS_WIN` includes `Q_OS_WINRT` which is not what we want - use `Q_OS_WIN32` (which is also set on 64-bit windows).
`Q_OS_MAC` is a deprecated synonym for `Q_OS_DARWIN`, and Qt documentation says "Do not use."
There are three places that are NOT fixed by this commit however they will clash with a pending PR #1506 that needs to modify the same lines so will be fixed by a commit in that set of changes.
=> Revise: fixup incorrect Q_OS_XXXX values {Main part}

CI/appveyor.install.ps1
It appears that Powershell uses only TLS 1.0 by default. Github now requires a higher version (I guess 1.2), so downloads failed.
=> Set powershell to use newer TLS version

src/Host.cpp, src/T2DMap.cpp, src/T2DMap.h, src/TConsole.cpp, src/TMap.h, src/dlgMapper.cpp
The `T2DMap` was a bit messy and this PR attempts to do some clean up work in the first commit which should not otherwise change the operation. The bug fix for #1536 is in the second commit and it has the result of doing a missing call to `T2DMap::init()` from the bottom of the `dlgMapper` constructor which is hit in some cases - I think when maps are loaded from the lambda function run when the application has emptied its event loop.  As well as ensuring the set of pixmaps that are needed to put ASCII characters (only) onto the 2D map room symbols it also initialises the room size and exit width on the 2D map which was something else I had noticed was not happening when the room "letters" were missing.
This is a bug fix for those missing letter but the system that is used to create them …
=> Bug fix room marker letters not showing #1536

src/TLuaInterpreter.cpp
When I extended the range of platforms and moved this function recently from the external Other.lua file to the C++ core (where there is a whole smorgasbord of OS macros) I was working from FreeBSD and did not spot that had lost the "linux" one - so that users on that platform would get a generic "unix" response, this commit fixes that.
Fixing an obvious error that I did not spot previously. :blush:
=> BugFix: restore "linux" to list of OSs reported by lua getOS()

src/T2DMap.cpp, src/ui/room_exits.ui
I found that the existing triangular markings drawn on the room symbols to indicate non-XY exits (i.e. up, down, in and out) mask any glyph drawn on as a symbol because for the real exits they are completely filled in black.
This commit enhances the design so that a mid shade "brush" is used instead for real exits and a light cross-hatch brush is used for stub exits. Importantly the colour used for the brush is either a contrasting black or white - the same as the pen used to draw the outline but it is now drawn in the same colour as the door markings on XY plain exits - so that doors can now be indicated on those up/down/in/out exits or stubs.
The tool-tips in the room exits dialogue have been amended to suit this long-planned (by me) enhancement!
The pen used to draw the outline is also …
=> Revise: improve non-XY exits/stub exits/doors indications on 2D Map

src/TBuffer.cpp, src/TBuffer.h, src/ctelnet.cpp, src/ctelnet.h
This commit adds in the ability to process the 1/2 (or 4 for GB1830) byte sequences that at least Mainland China uses for simplified Chinese for even historic language symbols. It actually uses the Qt decoder but like the UTF-8 processor in the `TBuffer` class it needs to process the incoming stream byte by byte so as to map each `QChar` in the recovered data to a corresponding `TChar` attribute element that Mudlet needs to have to work with the visual presentation of that text data. Note that once processed in `TBuffer` the textual data is held in the UTF-16BE form that Qt uses for its `QString` datatype.
Wanted by @markx (Ke Xu on Gitter) for use with **Pkuxka** MUD {accessible via **mud.pkuxkx.net:8080** in the West}
Even the login screen demonstrates the brokeness in our current …
=> Enhance: add GBK/GB18030 decoder for Far Eastern locales

src/main.cpp
I, perhaps carelessly, disabled the code to install fonts from the place where Mudlet extracts the bundled fonts to and then loads them in (in versions WITH bundled fonts) to be done for the versions WITHOUT those fonts.  This means that a module that includes a font for a particular MUD could not rely on Mudlet using a font placed in that part of the mudlet area of the user's file-system by loading the font in.
This commit remedies that error, I hope.
So that all versions behave the same should modules include font resources that they hope to use.
=> BugFix: allow font-load from sub-directory w/versions without bundled fonts

src/mudlet.pro
Some build configuration details only need to be reported on the first pass of the three that occur on Windows (or any other platform where the Qt `CONFIG` variable contains `debug_and_release`).  On the first pass `build_pass` is NOT present in `CONFIG` but it and `debug` or `release` as appropriate is added to that variable.
The trouble is that I made a previous typo and used `build-pass` instead, this commit corrects that.
=> Revise: prevent qmake spamming Windows builds unnecessarily

src/ui/lacking_mapper_script.ui
A previous form name change must have disconnected a signal/slot connection that was defined within the form/dialog XML (and not visible in the C++ application core) - the effect of which was that the "close" button did not work on that dialog...
It turns out that this may have been caused by commit: https://github.com/Mudlet/Mudlet/commit/5c342dd6e67dc8325dd85404137d4118354ea04f which tried to clean up variations between form names and class names so that future use of these for "context" resolution by `QObject::tr()` and related methods used the same identifiers across the application (so that the place(s) that the translation was needed for were correctly identified to the translator).
=> BugFix: make "close" button work on "lacking mapper script" dialog

CI/appveyor.install.ps1, src/TAlias.cpp, src/TKey.cpp, src/TLuaInterpreter.cpp, src/TTrigger.cpp, src/TriggerUnit.cpp, src/ctelnet.cpp
Adds flags to pcre_compile(...) calls.
Converts some places where `TLuaInterpreter` and other classes using `QString::fromUtf8()` and `QString::toUtf8()` (the latter where `QString::toLocal8Bit()` or `QString::toLatin1()` were used where it might be relevant - there are still more other places where this conversion is needed.
=> Enhance: convert Triggers/Aliases to work with non-ASCII text

src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h
Added event filter to allow capturing of keypad arrow key
I made a pull request some years ago to allow keypad keys to be used at hotkeys.  This worked successfully but I've found that in the current release there is no actual way to create them.  The reason is that (at least on Windows) if you have NumLock on and press Shift it effectively turns NumLock off.  So pressing e.g. Shift+KP4 is treated the same as pressing the left arrow, which causes focus to move back to the text field instead of capturing it.  What this change does is install a global event filter during the "grab key" sequence to allow these keys to be used, and then removes it again once the key is captured.
=> Add support for capturing keypad arrow keys

src/TBuffer.cpp
This expands the fix provided in PR #1570 for other cases and closes #1580 as an issue!
Also tweaks a couple of debugging messages in the same area of code to use leading zeros rather than spaces in some hex number details.
=> BugFix: prevent crashes when GBK/GB18030 decoder fed invalid encoded data

src/dlgRoomExits.cpp
Somehow one line of code is absent from `void dlgRoomExits::init(int id)` - it seems as if it was missing all the time as this can be traced back to *exactly* four years ago to a commit of mine:
https://github.com/Mudlet/Mudlet/commit/d8ff7e0c12a358071e00f38e083a641848d6ab17
=> BugFix: ensure changing out exit door induces a check for modifications

src/mudlet-lua/lua/geyser/GeyserLabel.lua
**NOT READY FOR MERGING**
Updating Geyser documentation (via LDoc) for the new Label callback parameters
I can't figure out the proper way to document a table that doesn't exist in the Lua file... not sure of the proper way to go about this. I added references to the affected functions, and "documented" the tables at the bottom of the file, but LDoc doesn't seem to recognize the documentation because the tables don't exist.
I think the compounding issue here is that the table in question isn't a parameter or return value of any of the functions in this file, so there's no obvious place to document it.
=> Updated Geyser documentation.

src/mudlet.cpp
The code to ensure a sensible default was not being limited to only working if a valid size had **NOT** been retrieved from the settings and was overriding the latter when it should not have been.
Closes issue #1598 .
=> BugFix: allow non-default Toolbar size settings to be saved

src/main.cpp
Adds the qt poll bearer workaround
Fixes  https://github.com/Mudlet/Mudlet/issues/1587
We should update to the latest Qt and remove this workaround, however we are blocked by https://github.com/Mudlet/Mudlet/issues/1176.
=> Workaround latency spikes

src/main.cpp
Remove qt bearer poll timeout
Having Mudlet lag every 5min is not acceptable, which it turns out the previous option did. 
See discussion at https://github.com/Mudlet/Mudlet/pull/1605#issuecomment-380891899
Upgrading to Qt 5.9.4+ fixes the problem too.
=> Remove qt bearer poll timeout

.gitmodules, src/TLuaInterpreter.cpp
This updates the lua formatter to the latest version and a branch that supports the 5.1 Syntax.
The formatter bundled with earlier Mudlet versions did not support 5.1 syntax. This was apparent in some subtle way like having a variable `goto`.
=> Use 5.1 syntax branch for formatter

src/TCommandLine.cpp, src/TConsole.cpp, src/TConsole.h, src/TLuaInterpreter.cpp, src/TTextEdit.cpp, src/TTextEdit.h, src/dlgProfilePreferences.cpp, src/dlgTriggerEditor.cpp, src/mudlet.cpp
It is stupid (IMHO) to call them `console` and `console2` as it means it is easy to confuse which one is which (and also confuses them with being `TConsole` instances). These renames make it altogether more easy to keep track of what each one is:
* `(TTextEdit*) TConsole::console`  ==> `TConsole::mUpperPane`
* `(TTextEdit*) TConsole::console2` ==> `TConsole::mLowerPane`
* `(bool) TTextEdit::mIsSplitScreen` ==> `TTextEdit::mIsLowerPane`
=> Refactor: rename the upper and lower TTextEdit pair in each TConsole

src/updater.cpp, src/updater.h
Change `installOrRestartButton` to be initialised in the constructor.
Coverity likes it more that way and the code has less surprising member initialisations in the middle of the class.
Fixes Coverity 1468471.
=> Initialise restart button in the constructor

src/TLuaInterpreter.cpp
Fix uninitialised lua_result value, it's possible if all of the 'if' calls fail.
Fix coverity 1468469.
Is there a way we can detect this at compile time?
=> Fix uninitialised lua_result value

src/mudlet-lua/lua/GUIUtils.lua
replaceAll currently fails if the length of the replaced string and the replacement string significantly differ. This is caused from an unnecessary index argument to find on line 600. Removing the argument seems to fix the issue.
I was writing a script which uses replaceAll and noticed some odd behaviour.
=> Fixed bug with replaceAll

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/mudlet-lua/lua/CoreMudlet.lua
Add a new function to Mudlet CoreLua getEpoch() returns number of seconds from unix epoch with milliseconds precision.
There did not appear to be a straightforward way to get number of seconds since unix epoch with milliseconds precision. This addition was desired to aid in scripts that require a higher accuracy source of time, for example to calculate durations of cure balances or similar events in the MUD.
Some were using os.clock() which is CPU TIME not time of day - and its behavior is not consistent across all platforms. os.clock() is thus the incorrect method. os.time() is better but did not have milliseconds precision. The best known way to achieve what getEpoch() does was to append os.time() to getTime(true, ".z") and convert it to a number, which is not desirablefor  performance …
=> Add Lua function getEpoch()

src/TLuaInterpreter.cpp
This commit should address the above issue in:
`(int) TLuaInterpreter::selectCaptureGroup(lua_State*)`
See [Coverity-1415093](https://scan7.coverity.com/reports.htm#v27731/p14359/fileInstanceId=38807018&defectInstanceId=8378731&mergedDefectId=1415093)
=> BugFix: Coverity 1415093 Using invalid iterator

CI/travis.osx.after_success.sh, src/TConsole.cpp, src/TConsole.h, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/mudlet-lua/lua/geyser/GeyserMiniConsole.lua, src/mudlet.cpp, src/mudlet.h
Add setFont() to allow setting a custom font in a window.
So UI designers can have fancy fonts in miniconsole windows.
=> Add setFont() to allow setting a custom font in a window

.travis.yml, CI/travis.osx.install.sh
This activates `ccache` use on travis. The tool speeds up compilation by caching compilation units and only regenerating those that change.
The general use was already enabled, but it wasn't installed on macOS and the cached files were not saved between builds, Both things are changed with this PR.
Faster compilation time means less waiting for jobs to complete.
=> Activate ccache on travis

.travis.yml
This defines the build matrix for travis builds explicitly. That way we can specify, which packages to install per matrix entry and thus we don't need to install both Qt 5.6 and Qt 5.9 all the time.
Decrease build times a bit more.
See https://github.com/travis-ci/travis-ci/issues/3505 about the technique used.
=> Explicitly state build configs to decrease number of installed packages

src/TTreeWidget.cpp, src/VarUnit.cpp
Code was trying to read the Lua variable that corresponds to the list header - there is none.
Fix #1659
=> Fix crash when clicking on the X= icon in variables view

src/TAlias.cpp
Fix aliases to work again - re-add code that marks which Lua function an alias should call.
Mudlet is a crappy client if no aliases work, and we don't want a crappy client.
The lesson I've learned is to do these kinds of refactoring one smaller bit at a time.
=> Fix aliases to work again

src/XMLexport.cpp
While closing Mudlet when autosave on was fine, closing just 1 profile was not, since the writer would try to call a method of the host already gone.
Fix #1687.
Qt docs on providing the context:
> The connection will automatically disconnect if the sender or the context is destroyed. However, you should take care that any objects used within the functor are still alive when the signal is emitted.
=> Fix crash closing 1 tab with autosave on

src/ctelnet.cpp
When sending a `Client.GUI` GMCP push Mudlet displays the following text while upgrading from version 6 -> 7:
```<The server wants to upgrade the GUI to new version '6'. Uninstalling old version '7'>```
This swaps the numbers to display them in the order the text expects.
=> Client.GUI server push version numbers are backwards

src/dlgRoomExits.cpp
This is the central feature of the abandoned Pull-Request #1672 and will close #1665 .
However that are other things in the `dlgRoomExit` class that I think are not up to scratch (Coverity is moaning about a couple of "medium" risk items) and there could be some issues with some uses of:
`QMap<T1, TExit*>::value((T1)key)` that will cause null pointer issues in some cases (which may be what Coverity is unhappy about!)
=> BugFix: Core fix for macOs versions not updating "Save" on Room-Exit dialog

src/AliasUnit.cpp, src/Host.cpp, src/KeyUnit.cpp, src/KeyUnit.h, src/TriggerUnit.cpp
This commit makes the `enableKey(<name>)` and `disable(<name>)` lua functions return `true` only if a key with the given name was found (instead of when any Key was present in the profile) - which is more like the handling for other items such as Triggers and Aliases.
It also arranges for all temporary keys to be "blown-away" when the profile is reset - which was not happening even though it does happen for other item types.
Furthermore when the "Emergency Stop" is activated it now also disables all the keys like it disables all timers/aliases/triggers.  I think this is desirable because if the user sets a binding on a normal key with no modifiers that it is impossible to type the character on that key into the profile's command line - so being able to disable the interception of the key …
=> Revise: update Key code to be more like other items

src/TLuaInterpreter.cpp
Highlight foreground and background were processed as a single
argument, even though documentation says otherwise.
Signed-off-by: Mateusz Kulikowski <mateusz.kulikowski@gmail.com>
One of arguments to tempComplex was skipped (or rather copy-pasted previous value).
Bug
=> BugFix: Properly handle highlight in tempComplexRegexTrigger

src/mudlet-lua/lua/geyser/GeyserMiniConsole.lua
Allow turning off scrollbar when it's not needed by changing the constructor from `scrollBar = true` to `scrollBar = false` and saving the script.
Simpler development cycle.
=> Turn off scrollbar when disabled in contructor

src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h
Improve load times for profiles with many packages by reloading the entirety of the trigger editor only once, not every single time for every single package loaded.
Faster profile load times.
Linux: https://transfer.sh/wcDgD/Mudlet-3.9.0-testing-PR1712-751e73e-linux-x64.AppImage.tar
macOS: https://transfer.sh/YbHQ3/Mudlet-3.9.0-testing-PR1712-751e73e.dmg
Windows: https://ci.appveyor.com/api/buildjobs/1e5wu5c5k0o3y6tp/artifacts/src%2Fmudlet.zip
No need to install, just unzip Mudlet and to test this new feature. Please report back if it works or doesn't work for you :smile:
=> Improve load times for profiles with many packages

src/TConsole.cpp
This speeds up loading of profiles that make use of miniconsoles. The major slowing factor here was creating many hunspell dictionaries.
Search and other buttons are still created, but they don't take a significant amount of time unlike hunspell creation
Faster profile load times
VTune showed the problem:
=> Don't create a command line for miniconsoles

src/dlgTriggerEditor.cpp
Took out out setFirstColumnSpanned() which was entirely unnecessary - that's the default, and it was taking up way, way too much time.
Fixed ALias typo to Alias
Fix https://github.com/Mudlet/Mudlet/issues/1662 which is a pain point for users.
Thank you Intel for making VTune free for non-commercial use (on a renewable trial license).
Finding the problem was as easy as running search and looking at this:
Linux: https://transfer.sh/DPxgc/Mudlet-3.9.0-testing-PR1711-f6ec8ef-linux-x64.AppImage.tar
macOS: https://transfer.sh/7g2e1/Mudlet-3.9.0-testing-PR1711-f6ec8ef.dmg
Windows: https://ci.appveyor.com/api/buildjobs/m51ssc8pr6y5di4s/artifacts/src%2Fmudlet.zip
No need to install, just unzip Mudlet and to test this new feature. Please report back if it works or doesn't work for you :smile:
=> Improved code editor search to be massively faster

src/ctelnet.cpp
Don't raise EOR Lua events just like we don't raise them for GA.
Improve performance by not raising an event for every transmission.
If someone wants to trigger on the prompt, they already can using the prompt trigger.
I don't think anyone would have been using this obscure option and even more an obscure telnet option to do much, so I don't think this will break anything. I only found 1 script at all that makes use of `sysTelnetEvent` and [it does nothing](https://github.com/Earthcrusher/Godspeaker/blob/master/current/10-09-2017%2303-12-03.xml) with it.
=> Don't raise EOR Lua events just like we don't raise them for GA

.github/CODEOWNERS
This adds `TLuaInterpreter.h` and `TLuaInterpreter.cpp` as special cases for code review. Changes in both files should request automatic reviews from the lua-interface team as well.
Flagging the right people for a review without action.
Closes #1724
=> Include TLuaInterpreter.[h|cpp] in codeowners as special case

src/TMap.cpp
While looking at translations I noticed this English text has an error.
`you could be be better`
Simple info text clean up!
=> Info message has a double `be`

.appveyor.yml, CI/appveyor.after_success.ps1, src/ctelnet.cpp
This fixes a memory corruption on Windows when compiling Mudlet with MinGW 5.3. It might have been a problem on other platforms as well, but it became apparent on Windows with #1176. The memory corruption is triggered in the linked issue by denying the telnet subnegotiation for ATCP. The cast from `char` to `int` lead to a change at a negative index in a bool array which happened to modify the internal state of `zlib` which in turn lead to a segfault or faulty state (which stalled).
We can switch to an updated Qt version on Windows!
Fixes #1176
=> Cast to correct data type to avoid memory corruption

src/mudlet-lua/lua/geyser/GeyserMiniConsole.lua
Originally it was trying to call disableScrollbar instead of disableScrollBar, which naturally caused errors.
=> BugFix: Correct typo in GeyserMiniConsole.lua attempting to call disableScrollBar

src/T2DMap.cpp
Show render time only in debug builds
It's a very technical detail that is not useful to the usual user (it's not FPS either).
Prompted by discussion on Crowdin.
=> Show render time only in debug builds

src/TLuaInterpreter.cpp
Improved setBackgroundColour to work with main window, applied the improved error message style, and made the alpha argument optional (since it does not work on miniconsoles).
Bring it in-line with other miniconsole functions that work on the "main" window and allow https://midmud.com to set a custom background colour in their Mudlet package.
=> Improved setBackgroundColor to work with main window

src/TCommandLine.cpp, src/TLuaInterpreter.cpp, src/TRoom.cpp, src/TRoomDB.cpp, src/TTrigger.cpp
This is a continuation of #1612 and #1613. After latest changes introduced in Mudlet 3.10.0, WITH_UPDATER=NO makes compilation fail again if Qt is version 5.11.0 (doesn't complain on 5.10.1), and requires including <QRegularExpression> in the header of several more files.
It is most likely not all of them (which should be noted for the future), but it is a good enough fix for now.
Tested on both Qt 5.11.0 and 5.10.1.
Please review, I'm not entirely sure if the placement of said includes is correct.
Thank you.
=> Fix compilining on Qt 5.11.x when WITH_UPDATER=NO

src/TTextEdit.cpp
Copying a block of text in a console where the selection does not include the *whole* of the first line causes the pasted first line content to be shifted over to the left margin.  In most situations that I can think of where only a part of the first line is copied then it makes sense to retain the layout relative to the remainder.
The padded out of a partial first line in a context menu invoked copy of text in a console was already being done for the HTML case but it was missing from the plain text form.
=> BugFix: correct missing indent of first line of plain text copy

src/TCommandLine.cpp
This should close issue #1753 .
The problem is likely to come about because the macOs platform includes the *KeyPad* modifier on arrow key presses whereas other platforms do not.
=> BugFix: get History Scroll Back Keys Working.

src/XMLexport.cpp, src/XMLimport.cpp
It seems a clash in including two PRs lost the bit of code that was in one of them to save the settings, because the saving code was revised by the other.
This should close issue #1765 ...
=> BugFix: ensure logging settings are saved with profile

.travis.yml, CI/travis.compile.sh, CI/travis.linux.after_success.sh
This will try to update the strings to translate (`translations/mudlet.ts`) on a daily basis with the already existing cron job.
Automating the update of translation strings to get forward with our Mudlet 4.0 goals.
This is pretty hard to test, sadly. The machine account needs to bypass the branch protection of `development` as it can't simply update a different branch from travis. That's also why I chose the cron job to run the `lupdate`.
=> Update strings to translate

CI/travis.linux.after_success.sh
Obviously, travis checks the latest commit out, which creates a detached head
state. That state can't be pushed, so we need to switch back to the development
branch first.
=> Switch to development branch for translation update

.appveyor.yml, .travis.yml, src/main.cpp
`main.cpp` is missing an `#include` needed for Windows builds that would otherwise be pulled in by the updater code.
=> BugFix: allow compilation for Windows builds without updater

src/TLuaInterpreter.cpp
This is a fix for #1789 "TLuaInterpreter hardcoded to search incorrect location for Lua extension dlls" - not, perhaps a long-term one but it might do for the moment.
It does suggest that I may to make a further change in this area to tweak things for FreeBSD!
=> BugFix: update a path that is needed for a newer mingw from Windows Qt

src/T2DMap.cpp, src/T2DMap.h, src/dlgProfilePreferences.cpp
Add a right-click menu that allows creation of a new map or loading of an existing one should the user have no maps available in the profile.
Make the mapper a little more usable for those without a mapping script.
=> Allow creating new maps in the map

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/TTrigger.cpp, src/TTrigger.h
Allows self-expiring temporary triggers. Adds an `expireAfter` argument to all of the functions:
```lua
tempTrigger(substring, code, expireAfter)
tempBeginOfLineTrigger(part of line, code, expireAfter)
tempColorTrigger(foregroundColor, backgroundColor, code, expireAfter)
tempComplexRegexTrigger(name, regex, code, multiline, foreground color, bg color, filter, match all, highlight foreground color, highlight background color, play sound file, fire length, line delta, expireAfter)
tempExactMatchTrigger(exact line, code, expireAfter)
tempLineTrigger(from, howMany, code, expireAfter)
tempPromptTrigger(code, expireAfter)
tempRegexTrigger(regex, code, expireAfter)
tempTrigger(substring, code, expireAfter)
```
Sample use:
```lua
-- expire after 1 prompt match
tempPromptTrigger([[echo("hey! got a …
```
=> Add expiring temp triggers

.travis.yml, CI/travis.linux.after_success.sh
Travis now complains when using `sudo` in container builds. This breaks CI builds.
Additionally, I deactivated the push back to github for modified translation files, which didn't work.
Fix our CI builds.
=> Fix coverity uploads and CI builds

src/dlgRoomExits.cpp
Removing the changing part like `(n of 5)` from translation comments of otherwise identical strings to archieve improved Crowdin integration.
There were comments like `This string is also used programmatically ensure all instances are the same, (1 of 5)` etc. but it seems like Crowdin can automatically ensure this. 
Compare the string in the same file with comment `This string is used in 2 places, ensure they match!` which is only listed once for translation in Crowdin, not twice, but indicates both line numbers as context:
So to have the same effect here, we need to remove the changing part (n of 5) from source: 
Also some typographical correction to ensure understandability of the two ideas mentioned in the comment.
Then again, the comment is thereby obsolete and should be adjusted for …
=> unify duplicate strings for i18n

src/TLuaInterpreter.cpp
This closes #1813.
A mistake in the string format specifier for a `lua_pushfstring` call used for an error message made that error fatal to the application rather than just the lua function involved!
=> BugFix: prevent getGridMode on non-existant area from seg. faulting

src/TConsole.h, src/dlgNotepad.cpp, src/dlgNotepad.h, src/mudlet.cpp
I put in code to close the Notepad in two places (although only one is
in currently used code) where it was missing, and also include calls to the
loading and saving of the text contents in the constructor and destructor
respectively.
This should close Issue #1800.
=> BugFix: ensure Notepad is always saved on profile close

CI/travis.linux.after_success.sh
Looks like curl doesn't like an equal sign between an option and its value.
=> Fix the curl argument

src/Host.cpp, src/Host.h, src/TConsole.cpp, src/XMLimport.cpp
If a profile save file was from an older version it may not have an `logFileNameFormat` attribute for the `<Host>` element this would clear the `(QString) Host::mLogFileNameFormat` member away from the default coded value. This commit now only changes the setting away from the default if a setting is present in a saved file.
Additionally, the old default value for the DateTime specification string used for some log file format types did not match any of the settings in the "Profile Preference" control for this - with the result that a new profile would show **no** setting when the preferences dialog was opened. This commit updates a faulty DateTime setting by changing any "hh" read in it to "HH" which then makes the rest of the code work as intended.
Signed-off-by: Stephen Lyons …
=> BugFix: fix faulty log options for new profiles or old profile save files

src/T2DMap.cpp
Align "no map"message in centre propely. 
Better aesthetics:
Salvaged the improvement from https://github.com/Mudlet/Mudlet/pull/1334
=> Align "no map" message in centre propely

src/Host.cpp
Create module zip if it's not already created when syncing - this fixes a crash in the case that the original zip is no longer present.
Fix https://github.com/Mudlet/Mudlet/issues/1834
=> Create module zip if it's not already created when syncing

src/mudlet.cpp, src/mudlet.h
Pulled out actions into a mudlet member class variables, similar to what https://github.com/Mudlet/Mudlet/pull/1334 did previously.
So they can be addressed directly for i18n.
I know that `enableToolbarButtons` can be improved - that can be done later.
=> Pulled out actions into a mudlet member class variables

src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h
Fix 'save profile as' to reliably work again.
Fix https://github.com/Mudlet/Mudlet/issues/1824.
Auto-save was kicking in as soon as the editor window lost focus due to the file browser dialog - and since auto-save was in the process of saving the profile already, save profile as was getting from doing the same.
=> Fix auto-save kicking in and blocking save profile as

CI/appveyor.install.ps1
The https://indy.fulgan.com site has started to not allow access to the archives for some reason - this should use a suitable alternative.
This will close #1849 if the resulting Windows CI build works for Windows users.
=> BugFix: use Alternative OpenSSLBinary for Windows

src/dlgConnectionProfiles.cpp, src/mudlet.cpp
This closes #1861 by ensuring that a setting that must be stored in the profile home directory rather than in the save file is read when auto-loading a profile as well as when it is loaded manually.
=> BugFix: set Server Encoding correctly on auto-loading profiles

src/mudlet-lua/lua/geyser/GeyserGauge.lua
Adds new property for Geyser gauges which, when true, prevents the gauge from overflowing. 
Currently if you are setting a gauge programmatically, you can end up with current values higher than maximum values coming in from the mud. When this happens and you feed the raw values into a Geyser gauge, it makes the front label of the gauge longer than the back one, 'overflowing' the constraints of the gauge. This adds an option you can set which will prevent this, setting the value of the gauge to 100 and showing it as full.
I brought the idea up briefly in the #mudlet-development discord room, but didn't open an issue for it since I was going to add the feature myself.
=> Add property 'strict' to Geyser gauges which enforces a max value of 100%

README.md
Readme did link to gitter chat as one of the first things. Does not anymore.
Gitter has not been used in multiple months and only has archival nature at this point. 
No need to link newbies there at the very start of the readme.
=> Stop linking inactive gitter chat

src/T2DMap.cpp, src/TConsole.cpp, src/dlgProfilePreferences.cpp
Remove necessary html-tags (which do not need translation) from strings we give to translators, as to not confuse translators.
Address #1802 issue 14
This does not address .io files. There is no tr() function, so I see no way to leave parts of strings as "not to be translated"
=> Remove html from translation input

src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h
Only autosave on a 1min interval when the editor is open and at no other times, instead of also autosaving (and running the script) when the window loses focus.
Turns out it's a pretty annoying idea!
Closes https://github.com/Mudlet/Mudlet/issues/1892.
=> Don't autosave when the window loses focus

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/lua-function-list.json
This function is reverse of getRoomIDbyHash.
It is more expensive as it iterates over all rooms.
Signed-off-by: Mateusz Kulikowski <mateusz.kulikowski@gmail.com>
Add reverse of getRoomIDbyHash()
* To ease sharing of map metadata while not sharing maps (data using hash instead of id can be easily imported to map created by someone else)
N/A
=> Add getRoomHashByID()

src/ui/triggers_main_area.ui
A new and well-written tool-tip was layered above most but not all the area of an older tool-tip. The old tool-tip has now been removed and the new tool-tip made visible in the whole area.
Improve exposure of quality texts, remove duplicate information for translators
Address #1802 issue 13
=> Ascend tool-tip from filter sub-area

src/TMap.cpp, src/TMap.h, src/dlgProfilePreferences.cpp
Adds StickMUD as a game that supports MMP map downloads.
Easy map download when the user opens the map for the first time and re-download via settings if needed.
`downloadMap()` arguments changed to plain arguments from pointers for simpler use - there was no reason for them to be pointers.
=> Add StickMUD support for MMP downloads

src/mudlet-lua/lua/Other.lua
Change to speedwalk function to replace long form directions with short form ones so that it parses correctly.
Fixes https://github.com/Mudlet/Mudlet/issues/503
=> Fix Speedwalk function to recognise long directions

src/TCommandLine.cpp
Fix tab completion to work with non-English languages by adding the `QRegularExpression::UseUnicodePropertiesOption` flag to regex.
i18n
Fixes https://github.com/Mudlet/Mudlet/issues/1934.
=> Fix tab completion to work with non-English languages

src/dlgProfilePreferences.cpp, src/dlgProfilePreferences.h, src/dlgTriggerEditor.cpp, src/mudlet.cpp, src/mudlet.h, src/updater.cpp, src/updater.h
Some time back the code-base was revised to only allow one Profile Preferences to be active at a time - this was so multiple clicks on the menu item or toolbar button did not make loads of copies of the form / dialogue.  However there are some advantages to being able to see the settings for multiple profiles side-by-side - this PR aims to provide this.
To stop the common settings being confused/getting out of sync if more than one profile is active and has the preference dialogue open, saving those setting by closing such a dialogue/form will now update the common settings currently defined for that dialogue in the other instances.
CARE SHOULD BE TAKEN THAT ANY OTHER "APPLICATION-WIDE" SETTING IS ALSO HANDLED IN THE SAME WAY SO THAT CHANGING THE SETTING AND SAVING IT FROM ONE PROFILE'S …
=> Enhance allow a profile preference dialog per host

src/TLuaInterpreter.cpp
Redirects are relatively normal these days. The chosen redirect policy allows only redirects to the same origin (scheme, host and port), minimizing the attack surface.
Less struggles like https://forums.mudlet.org/viewtopic.php?p=44693&sid=1a22ef7c84fd67f0e07f2369f14f6dd1#p44693
=> Allow downloadFile to follow redirects

src/mudlet-lua/lua/geyser/GeyserMapper.lua
Minor change to Geyser.Mapper so that map windows remain hidden when the container they are in is hidden rather than the map window itself being hidden.
=> Fix to Geyser.Mapper

src/TConsole.cpp, src/TTextEdit.cpp
Hi! This pull request modifies the HTML generation code in copying and logging to allow text wrapping.
Right now, if you open the generated HTML in a browser, you're forced to scroll horizontally if you're on a small screen. It's really inconvenient, especially for mobile users. This change makes it so long lines are wrapped while the original intent of keeping 'pre' for empty lines is still maintained.
I used the following resource to understand the 'white-space' CSS directive: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
Sample:
Before: https://ada-young.appspot.com/pastebin/hBgVhr9W
After: https://ada-young.appspot.com/pastebin/sAwe0hjn
Screenshots from an iPhone X: https://imgur.com/a/RD1L7Ja
=> Allow text wrapping in HTML copy and logger

src/LuaInterface.cpp, src/TVar.cpp, src/TVar.h, src/dlgTriggerEditor.cpp
Fix Mudlet crashing when renaming a table variable that's on the root `_G` level in the UI.
Fix #1966.
The code to rename a variable was incorrect and always assumed it would be nested within a table, not at `_G`, so it didn't work and failed - thus Mudlet's state tracking would get out of sync with Lua and a crash would happen later down the line.
https://ci.appveyor.com/api/buildjobs/qjos86ankij6077m/artifacts/src%2Fmudlet.zip - windows
https://transfer.sh/VJN0x/Mudlet-3.13.0-testing-PR1973-03ccca9.dmg - macOS
https://transfer.sh/NXRB3/Mudlet-3.13.0-testing-PR1973-03ccca9-linux-x64.AppImage.tar - linux
=> Fix UI editor crashing when renaming variable

src/TConsole.cpp, src/ctelnet.cpp
Before:
After:
Fix `resetFormat()` to respect the users colour selection as well as `[ INFO ]` & friends.
The ability to change background colour and not have Mudlets commands stand out glaringly.
I'm also thinking that once we get this working well, we should change the default from black to a bit of a nicer colour like modern Linux terminals do. Purple used in screenshots is only for example's sake and not a suggestion.
=> Fix resetFormat() & system messages to respect users selection

src/ctelnet.cpp
This will attempt to match system messages for colouring purposes using their translated strings, and not the English ones.
Correct colouring for translated text.
Fix https://github.com/Mudlet/Mudlet/issues/2005. A more proper solution would be to type this in C++ and not do string matching, but that is a more extensive overhaul and we need a solution before the next release.
Note that it's not possible to test the fix just yet - we'll need to update Crowdin for the new strings, get people to translate them, and _then_ this'll work. Let's merge this in fast to give translators time to translate and for us to fix any issues that come up.
=> Fix system messages getting coloured wrong when translated

src/ctelnet.cpp
Fix a newline in data throwing off the parsing of what is a GMCP key and what's the data payload.
Fix wrong code. http://www.mushclient.com/gmcp mentions also mentions that the separation is done with a space. I suspect this code was copied over from the ATCP implementation and games just didn't have a newline in their data to trigger this.
I've left the old behaviour in there as a fallback measure.
=> Fix GMCP parsing with embedded newlines

src/ctelnet.cpp
https://github.com/Mudlet/Mudlet/pull/2018 worked well - except that untranslated text now lost its colour. Let's colour both.
Consistent colouring for both translated and untranslated messages.
=> Keep colouring of untranslated text as well

src/dlgPackageExporter.cpp, src/dlgPackageExporter.h, src/ui/dlgPackageExporter.ui
Fix package exporter crashing when non-English was used.
Necessary for 3.14 release.
Fix https://github.com/Mudlet/Mudlet/issues/2006
Because the names of items were translated now, the code couldn't find them anymore.
=> Fix package exporter crashing when non-English is used

src/Host.cpp, src/Host.h, src/TMap.cpp, src/TMap.h, src/ctelnet.cpp, src/dlgProfilePreferences.cpp
Enables the following from GMCP:
```
Client.Map {
"url": "https://...."
}
```
This allows Mudlet to know that a game supports an MMP map - it is then downloadable from settings as well as when the user opens the mapper for the first time.
This is currently in ExVenture and you can see it at https://midmud.com/ when connecting.
Remove the need to hardcode games in Mudlet that support MMP.
Fix https://github.com/Mudlet/Mudlet/issues/1962.
=> Allow enabling MMP map download via GMCP

src/Host.cpp
Set the `server-icon` straight away when the custom ID is set if none is set otherwise.
This makes Mudlet behave as described in https://wiki.mudlet.org/w/Manual:Scripting#GMCP when only info is sent and no status.
=> Set the server-icon when the info is sent and not only on status

src/XMLexport.cpp, src/XMLimport.cpp
Rename Discord attribute keys to be consistent with other key names - with an `m` prefix.
Consistency in key names.
It's not very xml-like, but inconsistency is worse.
=> Rename Discord options to use the m prefix for consistency

src/TLuaInterpreter.cpp
Return `/` with `getMudletHomeDir()` even on Windows.
QSS does not accept `\` as a separator on Windows, and it has been a continuous source of issues throughout the years even by most experienced developers that you need to convert the forward slashes to backslashes.
In theory, doing so should not break anything... that is the intention. Let's merge it early in the 3.15 development cycle to see if anything does break.
=> Don't convert forward slashes to backslashes in Windows

src/mudlet-lua/lua/GUIUtils.lua
Moved declaration of prefix and suffix functions to end of file so that the table they use for function replacements will have the necessary functions declared before it is declared.
=> Update GUIUtils.lua to move prefix and suffix

translations/translated/generate-translation-stats.lua
Sometimes there are warnings or other messages which don't contain information
about the translation status. Skip them so we always have a valid number.
Don't fail anymore (like our current i18n branches do)
=> Skip lines without translation information

src/mudlet.qrc
There were some entries in `./src/mudlet.qrc` that had gotten duplicated which `qmake` moans about when it sees them - this commit sorts the entries in that XML file and removes the duplicates entries that were causing this.
=> BugFix: remove duplicate entries in resource file

src/mudlet.pro
Added the `CMakeLists.txt` that does in CMake what `updateqm.pri` does in QMake and the `generate-translation-stats.lua` file that they *both* use: to list of files that Qt Creator "knows about" in the Mudlet project file.
=> Revise: add unlisted files to QMake project file

src/TLuaInterpreter.cpp
hideWindow and showWindow had 'hideUserWindow' and 'showUserWindow' in their error messages. This changes the error messages to match the proper name of the function. Part of Issue #2069.
=> Fixed showWindow and hideWindow error messages

translations/translated/updateqm.pri
Improves the script in the `updateqm.pri` file that tries to identify what the command to run the Lua interpreter is so that it can handle the alternative `lua51` that FreeBSD uses for the (now a non-default) Lua 5.1 interpreter.
Added an advisory message to ignore the error message that the Windows process (using `where` in `cmd.exe`) generates when the first one or two tries to find the lua interpreter use the wrong file name.
Also tidied-up some poorly nested/indented `qmake` procedures which made it hard to visually determine what was being attempted.
**Added the `-compress` argument to the calls to `lrelease` in the qmake project file so that the invocation produces the same effect as the CMake one.**
=> Revise: improve updateqm.pri file

src/ctelnet.cpp
Some games were sending ANSI codes in GMCP that weren't properly escaped, replacing '\27' with '\\u001B' to convert it to what it should be in the first place.
Aardwolf and some other games are passing ANSI codes in GMCP with improperly escaped ANSI escape codes, causing errors converting them from JSON. This change is intended to convert it for them.
=> Update ctelnet.c to try to fix ANSI in GMCP

src/dlgProfilePreferences.cpp, src/dlgProfilePreferences.h, src/mudlet.cpp, src/mudlet.h
I had previously forgotten to set the `checkBox_showIconsOnMenus` control to the current (application-wide) setting on creation of the Profile Preferences. This commit inserts the code necessary and supports updating the control in multiple profiles' preference dialogues should it be changed when one instance is saved and closed.
=> BugFix: initialise checkBox_showIconsOnMenus in Preferences Dialogue

src/mudlet-lua/lua/GUIUtils.lua
xEcho was using the non-existent variable "window" in its moveCursor call, rather than the intended variable "win". Fixed.
=> Fixed xEcho to properly move cursor after insert

src/Host.cpp
Fix crash when saving profiles with synced modules. The `[]`'re were creating a new entry in the map while it was being iterated...
Fix crash.
Fix https://github.com/Mudlet/Mudlet/issues/2046.
=> Fix module sync not to crash

src/mudlet.cpp
Using "English" to describe "American English" introduces some confusion when "English (British)" is also listed. Similarly calling a language "Chinese" when it actually means "Simplified Chinese" which is what is generally used in China can be confusing when Taiwan uses "Traditional Chinese" - this is actually a point of contention in that part of the World and it is not wise to mix up what each setting is supposed to mean or to imply a difference importance to different variants for the same language.
Note that I have changed to use square brackets `[`...`]` around the Country or other disambiguation term here because `(`...`)` are already used for only partially translated languages and it looks messy to use the same type of brackets twice in the same item when they imply completely …
=> Revise: properly distinguish between two pairs of two languages

src/ctelnet.cpp
Fix data separation logic to work for the case when both newlines and spaces are present.
More robust detection.
Allows usecases like https://github.com/Mudlet/Mudlet/issues/2040 still to work.
=> GMCP: determine data separator better

src/TLuaInterpreter.cpp, src/ctelnet.cpp, src/main.cpp
Including many strings for translation, mostly related to connecting and disconnecting a profile.
Removing strings from translations where they are not needed.
Adjusting code to better grasp strings to translate.
Reduce English texts in translated Mudlet versions to mostly only texts used internally.
As discussed in #1964 and #2010 and Crowdin
=> Translate strings for connection/disconnection

src/ui/profile_preferences.ui
Don't make the profile dialog too wide in case the user has a very, very long name for a trigger/alias/etc.
Better user experience.
Fix https://github.com/Mudlet/Mudlet/issues/2073.
=> Fix profile preferences blowing up with a long item name

src/ctelnet.cpp
The code analysis that we have done by Coverity recently reported a dead (unreachable) code issue that I introduced whilst trying to "improve" the Telnet status reporting sub-option (5) - as a side effect of #1852. Basically I was comparing a `size_t` loop variable (which ran through all the values between 0 to 255 inclusive) to a `const char` which should have had the value of 240 (I also had a coding error and was using a value of 250 but the same principle applied!)  Due, I think, to the intricacies of `char` promotion to `int` a `char` value greater than 127 gets treated as a negative value (as a `signed char`) rather than the `unsigned char` I was expecting. I hope to fix that with this commit which makes the conversion go via the `unsigned char` type which should make it work...
If …
=> BugFix: cure Coverity reported error

src/TConsole.cpp, src/TConsole.h, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/mudlet.cpp, src/mudlet.h
Added `text, start, length = getSelection()`.
Knowing where the current cursor is in case it's modified by a 3rd party.
Addresses the need in https://github.com/Mudlet/Mudlet/issues/698.
=> Added getSelection()

src/mudlet.cpp, src/ui/main_window.ui
Some clean up work:
Remove some unused `QActions` defined in the `./ui/main_window.ui` form:
* `dactionForum_2`
* `dactionIRC_2`
* `actionTest1`
* `actionAsdf`
Removed the `windowTitle` and `windowIcon` definitions in the `main_window.ui` form as they are wrong and overwritten in the `mudlet` constructor anyway - the former would also have cropped up as a pointless `QString` to be translated.
Remove some unused `QActions` defined in the `mudlet` constructor but never placed into the application's windows:
* `mactionConnect`
* `mactionAlias`
* `mactionTimers`
* `mactionButtons`
* `mactionScripts`
* `mactionKeys`
* `mactionMapper`
* `mactionHelp`
* `mactionOptions`
* `mactionMultiView`
* `mactionAbout`
Moved the `statusTip` texts for items on the menu bar to the corresponding `toolTip` …
=> Revise: dead code removal for main window

.travis.yml, CI/travis.osx.install.sh
The Personal Package Archive (on Ubuntu) called `ppa:jonathonf/php7` no longer seems to be available which has cause Linux CI builds to error out however there is a commonly used (mainline ?) alternative called `ppa:ondrej/php` which seems to do the job.
Also with recent upgrades the Mac CI builds are erroring because Boost 1.68 is being built from scratch as it is not available as a "bottled" formula on the Homebrew system - and it takes so long the install/setup process times out... However we do not need a bleeding edge Boost so it is sufficient to use the supplied CI version (which seems to be 1.60).
Also fixed a spelling mistake in a comment in the CI/travis.osx.install.sh file.
=> BugFix: try and get both Mac and Linux Travis CI builds working

src/mudlet.cpp
In https://github.com/Mudlet/Mudlet/pull/2110 I arranged for all the no-longer shown status tips (we discarded the status bar on the main window some time ago) to become tool tips for the main menu.  Unfortunately, I never turned on the option for those tool-tips to be shown!
This commit fixes that.
=> Enhance: arrange for main menu tool tips to actually be shown to user

src/TBuffer.cpp
Some code that only is used when an additional decoder is needed for non-Unicode multi-byte encodings was missing being run for the ***Big5*** one.
To ensure correct operation for *that* encoding.
=> BugFix: fixup some code omissions for Big5 character encoding

src/TLuaInterpreter.cpp
`lua_isboolean` used instead of `lua_toboolean`
`expandAlias(LastAttack, DebugFlag)` worked before 3.16 but does not anymore. Same for `svo.doaddfree("get gold",  DebugFlag)`
Known workaround: Use "nil" instead of "false"
=> Fix expandAlias()

src/TMap.cpp, src/dlgProfilePreferences.cpp
Remove all games MMP map location from hardcoding since all games support [Client.Map](https://wiki.mudlet.org/w/Manual:GMCP_Extensions#Automatic_map_download) now.
Less hardcoding, less fragility!
=> Remove MMP hardcoding in favour of Client.Map

src/TTextEdit.cpp
This will close https://github.com/Mudlet/Mudlet/issues/2143 .
=> Bugfix: correct a typo that provoked a Coverity warning

src/main.cpp
This pull requests sets the autoscaling flag for Qt on Unix systems.  Mac and Windows have built-in scaling systems so the flag is gated for only Unix systems.  
On HiDPI displays on Linux/Unix systems, Mudlet will be scaled too small out of the box.  Qt offers a way to autoscale applications on systems by setting an application attribute.  See http://doc.qt.io/qt-5/highdpi.html  This pull request sets that attribute for these systems.
Tested against Ubuntu 18.10.  
Although this helps significantly with HiDPI, in the long term a transition away from fixed point font sizes and absolute sizing would be recommended.
=> Adding Automatic Qt Scaling for HiDPI for Unix systems

src/Host.cpp, src/Host.h, src/XMLexport.cpp, src/XMLimport.cpp, src/ctelnet.cpp
This PR solves Issue #2151 that would not allow version numbers other than integers for the Client.GUI version. The prior version was converting a string of text sent from the MUD server to the Mudlet client to an integer.  If Mudlet detected it was something other than an integer, it would default pHost->mServerGUI_Package_version to 0. To support a string representation, the following changes were made:
- modified:   ../src/Host.cpp -> pHost->mServerGUI_Package_version was int now QString
- modified:   ../src/Host.h -> pHost->mServerGUI_Package_version defaulted to -1 now QLatin1String("-1")
- modified:   ../src/XMLexport.cpp -> String no longer converted to a number
- modified:   ../src/XMLimport.cpp -> String no longer converted to a number
- modified:   ../src/ctelnet.cpp -> String …
=> Allow non-int version for gmcp.Client.GUI version (#2151)

src/TConsole.cpp, src/TConsole.h, src/TTextEdit.cpp, src/dlgTriggerEditor.cpp, src/mudlet.cpp
By replacing the following somewhat adhoc collection of flags it is easier to refactor code that is dependent on the particular type of `TConsole`:
* `(bool) TConsole::mIsDebugConsole`
* `(bool) TConsole::mIsSubConsole`
* `(bool) TConsole::mUserConsole` - flag for a subConsole/Buffer/UserWindow
Also removed the unused:
* `(bool) TConsole::mWindowIsHidden`
This has revealed that there are numerous cases where the `Buffer` type of `TConsole` is including code that was likely only intended for the main one for each profile...!
=> Refactor: use a single enum to classify all TConsole instances

src/dlgAboutDialog.cpp, src/main.cpp
Happy New Gregorian Year everyone.
This commit changes the ending year in the copyright message that appears on the splash screen as
required now that we have taken out the code that used to do it dynamically - which was frowned upon
because it breaks *[reproducible-builds](https://en.wikipedia.org/wiki/Reproducible_builds)* ...
Needed for the New Year.
=> DataStamp: revise copyright strings for new year (2019)

src/XMLexport.cpp, src/XMLexport.h, src/dlgTriggerEditor.cpp
This is a BugFix  for issue https://github.com/Mudlet/Mudlet/issues/1872 where it is reported that non-ASCII characters in the file name for items that are to exported as packages fails on Windows platforms. {An empty file with the right name is created as well as one with the expected contents but where every non-ASCII character in the file name has become Mojibake - furthermore should the same happen further up in an absolute path and file name then it is likely that erroneous path elements would be formed which due to file-system access control mechanism will either fail to be created or put the eventual XML file in a bogus location.}
This is an issue for non-English users who are likely to use characters outside of the limited range of ASCII characters in file names.
It transpires …
=> BugFix: allow XMLexport to files with non-Latin1 character filenames

src/T2DMap.cpp, src/T2DMap.h, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h
Adds `getMapSelection()` to the lua API that returns a table containing the details of the currently selected items in the (2D) map. At present this is limited to rooms being selected but there is an extensible scope within the implementation to handle other things (e.g. an existing custom exit line, or a map label). 
As an aside in: https://github.com/Mudlet/Mudlet/issues/2155 I suggested that it could be useful to have a lua function that would return a list of rooms when they are selected in the (2D) mapper - this will be useful for user scripts/aliases that want to modify such a selection.
To allow the handling when something other than a room or rooms is selected the function actually returns an associative table which always contains the key `type` which will be `rooms` if it does …
=> Enhance: add lua getMapSelection() function {only covers rooms for now}

src/EAction.cpp, src/EAction.h
A single character defect meant that the `SIGNAL` from the push-buttons on menus were not being connected to the `SLOT` that was expected to get the signal in order to perform the required behaviour.
As such the `EAction::triggered(QAction*)` signal declaration is not required and can be excised.
This will close https://github.com/Mudlet/Mudlet/issues/1914 .
=> BugFix: get buttons working in menus on button toolbars

src/T2DMap.cpp, src/TMap.cpp, src/ctelnet.cpp, src/dlgMapper.cpp
Prompted by some changes made for #2173 I decided to clean up the other *old-style* `connect(...)` and `disconnect(...)` usages which are only checked at run-time compared to the *new-style* which forces the type checking to be done at compile time.  The changes here includes some for unimplemented and commented out instances.
It does not include a usage of `QSignalMapper` which has been declared obsolete and is not supported by the new, compile-time checking, system.
It also does not include usages in the third parties libraries, particularly the `edbee-lib` editor widget and the `communi` IRC libraries.
=> Refactor: remove all possible remaining old style SIGNAL/SLOT connect(...)s

src/TTextEdit.cpp, src/main.cpp
Add DPI scaling for TTextEdit
When scaled for a HiDPI screen, the font in the main windows looks pixelated as the main windows are being stretched. This adjusts the size of the main window to account for the DPI on the screen the textbox is on.
Resolves issue [2171](https://github.com/Mudlet/Mudlet/issues/2171).  See the issue for screenshots.
Fixes https://github.com/Mudlet/Mudlet/issues/800.
=> QPixmat dpi adjustment

src/ctelnet.cpp
Fix Mudlet to connect well on the first try again.
Qt throws up this warning which seems relevant:
```
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QSslSocket(0x560e5ff6b270), parent's thread is QThread(0x560e5f06f330), current thread is QThread(0x7f1bd8004a00)
```
=> Fix Mudlet to connect well again

src/mudlet-lua/lua/LuaGlobal.lua
This will close https://github.com/Mudlet/Mudlet/issues/839 . This piece of Lua script has not been needed since: https://github.com/Mudlet/Mudlet/commit/b6705a1735fd275a78e000bc1299c58a548eadeb .
=> Refactor: remove redundant external Lua module override

src/TMap.cpp
* split long sentence in 2
* handle multi-line error-message accordingly
* drop extensive explanations
Increase readability
=> TMap::serialize UI texts updated

src/T2DMap.cpp
This change should cause the "Move room to other area" combobox to be in a proper A-Z order rather than to be in an area ID number order.
Ensure that others will find the area that they can move the room to other areas easily. Plus it is an easy issue to fix.
1)that should close #2180 and #1549
2)also, this is PR being separated from older PR #2191 (because it is on development fork which should and would screw up the future merge.
3) all feedbacks from that old PR are applied.
=> set room area dropdown menu should be sorted by name, not by area ID. (part two...)

src/TBuffer.cpp
erronoeous fixed string in MXP handler fixed
It is to fix a potentially bug in TBuffer.cpp in regards of MXP handler of a fixed string.
ez mode fix and try branching out for a seperated pull request.
This should close issue #2130
=> Erronoeous fixed string in MXP handler in `TBuffer::translateToPlainText(...)`

src/mudlet-lua/lua/GUIUtils.lua
Added enableGaugeClickthrough and disableGaugeClickthrough functions to make use of enableClickthrough and disableClickthrough functions with gauges easier.
=> Add support for clickthrough functions to gauges

src/TLuaInterpreter.cpp
this is for issue #683 partially. extending the isActive() and exists() functionality for scripts
It is to complete the request of issue #683. so one could execute in lua script to find them. E.g: exists("cow", "script") and/or isActive("svo", "script")
this partially completing the request of #683.
=> extends lua functionality of exists() and isActive() for scripts

src/Host.cpp, src/Host.h, src/TBuffer.cpp, src/ctelnet.cpp
This change ensures that MXP will be on open line state by default initially after the completion of MXP IAC negotiation.
The motivation of this patch is to ensure that it affirms the MXP spec, and to an extent, that some servers use Evennia codebase or other will be able to display the lines as intended as it should be.
this should solve the issue with #2196 and evennia/evennia#1058
=> ensure that the MXP init state is in a open line state at start by default.

src/TBuffer.cpp, src/TLuaInterpreter.cpp, src/mudlet.cpp, src/mudlet.h
Allows a extra initial string argument as a mini-console, user window or buffer name to get the text from `TConsole` instance as well as the main profile one. To that end, the empty string and the name "main" are reserved and treated as referring to the main one.
Note that this PR ~may~ will clash with another PR I have pending: https://github.com/Mudlet/Mudlet/pull/2226
This will close Issue: https://github.com/Mudlet/Mudlet/issues/754 which was originally opened in December 2013!
=> Enhance: extend getLines(...) to support user created windows

src/dlgTriggerEditor.cpp
Adds call to trigger cleanup after script save finished compiling the script. Tested working with the same scenarios it was discovered with.
Before PR, if you had the following script in a script object and saved it several times between receving lines from the MUD, all the triggers it created when saved will be triggered, then the ones marked for deletion will be cleaned up. Until the line is received, the number of tempTriggers reported in system statistics also goes up. This change prevents that.
```lua
if testtemptrigger then
killTrigger(testtemptrigger)
end
testtemptrigger = tempRegexTrigger([[^.*$]], [[cecho(" HI I am a trigger, and I just fired!!!")]])
```
Discussed this issue over discord in the help and development channels, adding a quick PR.
=> Adding call to TriggerUnit::doCleanup() after a script save to avoid stale triggers

src/Host.cpp, src/TBuffer.cpp, src/ctelnet.cpp
The aim of this PR is to make MXP work enabled or not across the MUDs. It has been tested to ensure that it work ON IRE MUDs, Chatmud, and Evennia, and other.
magical fix to some weird MXP issues. at least it should make IRE, ch…
because my last PR didn't expect the situation where IRE didn't negotiate for MXP; hence the creation of this pr.
this should resolve regression of #2229
=> Magical quirks to fix MXP issues to make sure it work on various MUDs

src/dlgTriggerEditor.cpp
There were a couple of places where some copies of the same text for translation did not have the comments that other copies had - leading to confusion for translators. And the ones that did share the comments had a spelling error in them!
And in one place whilst reviewing this PR I realised I had put the wrong comment in one place - which needed fixing before pressing the "Create pull request" button! :see_no_evil: 
It would be nice if this can get carried forward into the 3.17.0 release but I am not sure if that is acceptable in the current scheme of things.
=> BugFix: correct variation & typo in translation disambiguation comments

src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h
Removes all colours from trigger patterns - we used to have foreground colours but that caused issued on dark themes. The addition of background colours looks pretty bad, so might as well remove the colours altogether - in theory this should now work on a dark theme.
Better support for dark themes while not turning the triggers area into a kaleidoscope! 
We might be able to reinstate the foreground colours only if https://stackoverflow.com/a/15520024/72944 works, perhaps? Otherwise, we can see if we get any feedback on the foreground colour removal. If nobody misses it, then it wasn't useful at all.
=> Remove colours from trigger patterns

src/TTrigger.cpp
this should point to a correct item that causes Lua function error, or regex error. so it should be item n + 1, not item n(it would cause it to say 'item 0' when there is only item 1 and up on the list.
resolved for issue #2255
=> Fix trigger error messages showing wrong pattern #

src/mudlet.cpp, src/updater.cpp
Also stops it running on development version when it is supposed to be permanently disabled but was still putting up the change-log when the main application ended.
There is similar code in the `Update::setupOnWndows()` method and I do wonder whether it may also be the cause of: https://github.com/Mudlet/Mudlet/issues/1823 in the Windows version?
I also found two other things needed to keep the updater sedated for development versions of the code:
- hide the Update option from the "About" sub-menu
- Prevent the setup of the UpdateDialog on start up as that initiates the on-line search for updates - which is pointless in the development version case.
=> BugFix: fix updater problems on Linux and Windows OSes

src/KeyUnit.cpp, src/KeyUnit.h
Some fixes go into place to ensure that it won't cause a move of a key to a subfolder to malfunctioning that would cause a displacement of naming, unable to delete or modify a key.
I find it interesting that moving triggers into folder won't cause a problem but keys would. so it gives me a good guess where and why it won't work.
it should resolve #2253 .
=> Moving-a-Key-into-a-subfolder fix.

src/dlgProfilePreferences.cpp
Info, Error and Warning images are now shown much bigger, after the image files got increased resolution
Image taking up too much space:
Trying fix from #2231 here as well
=> Fix notification image size in security preferences

src/dlgTriggerEditor.cpp
The code was incorrectly using the string that had been parsed from the style-sheet used to set the colours of some push buttons with the result that it was returning the invalid colour `QColor(0,0,0,0)`. 
This was because the `QColor` constructor needs the `#` prefix when parsing a hex colour code like `#RGB` or `#RRGGBB` or `#RRRGGGBBB` where the letters represent the parts of a 3, 6, 9, 12  (or 8) digit hex numbers.
=> (release-3.17) BugFix: repair loss of trigger colorization

src/ctelnet.cpp, src/ctelnet.h, src/mudlet.cpp
Fix Mudlet freezing when host that has an open secure connection is closed on Windows.
Pretty bad to have Mudlet freeze at all!
Fix https://github.com/Mudlet/Mudlet/issues/2272.
=> Fix Mudlet freezing on Windows when securely-connected host is closed

src/main.cpp
Only enable HiDPI on Linux on Qt 5.12+ where it's safe. Qt versions 5.6 - 5.11 make the application blow up twice in size on normal displays.
Most people don't have a a HiDPI display, so it's better to have it working for the majority.
Workaround https://github.com/Mudlet/Mudlet/issues/2246.
=> Only enable HiDPI on Linux on Qt 5.12+

src/Host.cpp, src/Host.h, src/TCommandLine.cpp, src/TCommandLine.h, src/dlgProfilePreferences.cpp
Using `QString::toLatin1()` when transferring text to and from the Hunspell library will miss-encode any characters that are not in the ISO 8859-1 (Latin 1) character set and will not work if used with languages that use characters outside of that set.
The existing code only installed the user selected dictionary for spell-checking in the constructor of the `TCommandLine` class instances which meant that changes with the profile active did not take effect until the next profile load - which is less user friendly than changing it when requested. This commit corrects that problem.
At the moment there is (or should be?) only one `TCommandLine` per profile - for the Main Console.  I have chosen to use the signal/slot method for the `Host` class to inform the rest of the profile that the …
=> BugFix: ensure command line spell checker handles non-Latin1 characters

src/dlgProfilePreferences.cpp, src/dlgTriggerEditor.cpp, src/mudlet.cpp, src/updater.cpp
Add 'this' argument for the context to `connect()` calls, so the lambda is not called should the object be destroyed.
https://github.com/KDE/clazy/blob/master/docs/checks/README-connect-3arg-lambda.md
=> Pass 'this' argument to lambdas for extra safety

src/TBuffer.cpp
Use QString.midRef() instead of QString.mid()
Trivial performance improvement
https://github.com/KDE/clazy/blob/master/docs/checks/README-qstring-ref.md
=> Avoid unnecessary allocations with midRef in TBuffer

src/Host.cpp
Some games are sending `"inviteurl": ""` in what is probably a misunderstanding that the key is optional - ignore it for further purposes.
Not much right now since we don't display the invite url anywhere, but when we do, it'll be nice not to have to work around it!
=> Ignore empty Discord inviteurl from GMCP

src/TLuaInterpreter.cpp
…by calling to getColumnNumber(win).
This ensures that calling to GetColumnNumber(windowName) on the mudlet side will properly return the result for Xecho function on the Lua side.
I find it curious that moveCursor is not the main cause of misalignment rather, it is getColumnNumber that failed to return the result. so in this fix, it should now correctly return the result as intended.
this should resolve #2316 and #743
=> Fix getColumnNumber("main")

src/mudlet-lua/lua/generic-mapper/generic_mapper.xml
Added check so that quick help is only ever shown once per session, even if no prompt pattern is set.
Issue #2305
=> Fixed multiple quick help issue

src/mudlet-lua/lua/generic-mapper/generic_mapper.xml
The speedwalk function was removing commands for which there wasn't a translation, causing problems for non-standard commands. Looking at the existing code, it appears that door handling as it is won't work properly with translations, but I'll come back for that later.
Someone was having trouble using speedwalk through portals, and debugging revealed this as the root cause.
=> Fixed speedwalk with translations

src/Host.cpp, src/ctelnet.cpp
If the user has an enabled "show current game" option in Discord:
Don't go out of our way to mask the actual game name with "Mudlet" like it is currently happening:
And show the actual game name instead (without revealing any information about the player!)
This change does not affect the Discord opt-in because it does not have the possibility of leaking data (such as character names), the game name is hardcoded by the developers for everybody equally.
The idea of Discord integration was to actually show the game name + give the ability for game admins and players to show more data. The feature was built with very good privacy controls and is opt-in. I think we went overhead with masking things though - nothing wrong with showing the current game if the user has **already** enabled it in …
=> Don't go out of our way to mask the game name for Discord

src/mudlet.cpp
Mac now uses same keyboard shortcuts as all other OS
Before this, Mac users had mixed up O and I keys
Fix #2323
=> Align Mac shortcuts for profiles&modules manager

src/Host.cpp, src/Host.h, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h
Changing the default command separator from ';' to ';;' and adding getCommandSeparator functions to support dynamically making use of the command separator.
The command separator has long been a point of discussion in Mudlet. The default of ';' causes issues when someone uses it as grammatical punctionation, sometimes sending folks to support to figure out why their sentences keep getting broken up. It's also parsed by send() and similar functions to split a command into multiples. This causes problems if you use send() with the command separator in lieu of sendAll(), or if you use expandAlias() with the command separator in your script and wish to distribute it. Despite some of these things being poor practice, we can't ignore that they are and have been used. This change allows use to …
=> Get command separator

src/main.cpp
Remove the workaround for the toolbar going black when the 3D mapper is opened on macOS since https://bugreports.qt.io/browse/QTBUG-41257 is now fixed.
We can delete the code when we deprecate support for 5.12 (way later) and it might have a positive side-effect to disable it now.
=> Limit macOS workaround for 3D mapper to known bad Qt versions

src/mudlet.cpp
This PR should ensure that the Console will show itself, then the dock widget reappears on the screen.
resolve #2333
=> Reopen/show User Window should cause console to appear in a dock widget.

src/dlgTriggerEditor.cpp
previously, it is not possible to append after list don't have any event handlers in them(by deleting them). This change in this PR will recreate a list after the previous list is completely cleared for an event handler. 
this resolve #2320
=> event handler to properly function by re-append after deletion for a registered event handler 

src/Host.cpp
This manifests for MUDs that are not known to Mudlet.
Reported by ZureaL on Discord.
Also fix a pair typos of missing apostrophes in the same file that showed up whilst debugging.
=> BugFix: sort-out Discord Large and Small Icons/Text mixup

src/ctelnet.cpp, src/ctelnet.h
Adjust the socket read function to take its data in as parameters.
So we can enable fuzzing or unit testing on it.
Hopefully this doesn't break anything, this is very important code. Doesn't seem to with a quick test.
=> Refactor telnet socket read for unit testing / fuzzing

src/TTrigger.cpp
Not 100% sure what case this will fail to work on... why isn't the last `(pCT->mBgColor == (*it).background())` condition enough?
Less warnings in Coverity.
Thanks to Coverity for finding the issue.
=> Fix copy/paste trigger bug in background colour matching

src/mudlet.h
it seems that the absence of the updater code (presumably) causes a needed `#include` to be missing from a well used header file causing compilation to fail.
Thinking about it - this has come about because of the enhancement of the "About" button on the main toolbar which has indeed been changed from a `QPushButton` to a `QToolButton` to enable it to have an instant popup when a menu is added to it on other OSes when an update is spotted for users who have set their Mudlet to NOT automatically update.  Obviously that is not applicable for this OS so it would not be surprising if the missing header was included from, say, `./3rdparty/dblsqd/update_dialog.h` which is not retrieved on a platform without the updater functionality...
Whilst it is not likely that anyone else in the project core …
=> Bugfix: fix header includes for compilation on FreeBSD

src/Host.cpp, src/TLuaInterpreter.cpp, src/ctelnet.cpp, src/ctelnet.h, src/mudlet.cpp
The cause of Issue #2288 "Mudlet freezes when closing secure profile with self-signed certificates on Linux" seems to be because there is an asynchronous signal from the network thread that arrive when there is not enough of the profile left to handle it.
Putting a call to the `cTelnet` method `disconnectIt()` {was called `disconnect()` see below} in the `Host` destructor is the primary suspect in this case!
This PR seems to fix the issue by not allowing the profile to be closed until it is known to be disconnected from the game server.
it also renames `(void) cTelnet::disconnect()` to `(void) cTelnet::disconnectIt()` this is so that it does not hide the non-static `QObject::disconnect(...)` call with three arguments which are all defaulted (although that does have a `bool` return type). …
=> Bug fix freeze when closing self signed certificates on linux

src/Host.cpp, src/Host.h, src/T2DMap.cpp, src/TConsole.cpp, src/TConsole.h, src/TMap.cpp, src/TMap.h, src/TRoomDB.cpp, src/ctelnet.cpp, src/ctelnet.h, src/dlgMapper.cpp, src/glwidget.cpp
This will enable them to establish the identity of their related `Host` instance without the need to call `Host::getName()` which involves a mutex in the latter class. This makes things a bit faster and less likely to cause deadlocks in odd places and does make things simpler for some other related classes.
The `Host::setName(const QString&)` method has been revised to ensure that changes are passed across to the other three classes on change. This will close https://github.com/Mudlet/Mudlet/issues/2357 - with the exception that changing the name of the profile whilst it is active will need some further jiggery-pokery in the HostManager and mudlet classes.
This came about as I was investigating https://github.com/Mudlet/Mudlet/issues/2288 but it became something that could be sorted out …
=> Refactor: provide mProfileName to cTelnet, TConsole and TMap classes

src/ui/profile_preferences.ui
This file was provoking four warnings on compilation because the same name was being used in two places for 2x4 = 8 items.
This PR resolves the clashes (mainly in auto-suffixed with "_##") in the names of some `QGridLayout`/`QVBoxLayout`s by changing the suffixes to reflect the item that they were the layout for.  There was a similar clash with two unsuffixed items both called "verticalSpacer`".
At the same time I have taken the opportunity to reset the order of some items in `QGridLayout`s in this form so that the row/column values are in ascending order. Maintaining that order in PRs will help to improve the signal-to-noise ratio in other git diffs - though it does make this one almost undecipherable!
=> Revise: QGridLayouts' order & resolve names in profile_preferences.ui

src/TTextEdit.cpp
As FreeBSD does not include the updater code it is missing a needed header associated with handling `QVersionNumber`s - probably this header is a requirement for the updater code and since I recently added code that uses that class I had not spotted that the include was being provided indirectly rather than explicitly at the top of the implementation file.
=> BugFix: missing header for non-updater platform builds

src/dlgTriggerEditor.cpp, src/dlgTriggerPatternEdit.cpp, src/dlgTriggerPatternEdit.h
We recently removed the foreground colour coding of text entered into the trigger item text line because it could render some types unreadable with some themes/styling.  That was not universally popular because the colour was also a sub-conscious reminder to some users as to the item type.
This PR adds a coloured icon to the trigger type selection `QComboBox` but - given that it is a little way from the point at which any text is entered I have also arranged for the coloured (they could also be pictorial icons if someone wanted to design a set) icons to be duplicated at the start of the `QLineEdit` where the text is entered.
The colours largely duplicate the colours previously used for those with text entry and I have chosen a pair of contrasting colours for the two (colour and prompt) …
=> BugFix: redo triggerT-type Indication in editor to return a colour coding

src/TBuffer.cpp, src/TBuffer.h
Fix cases like this:
`Here is a line from a MUD. It has some words and then some more words and then word wrap
.`
So they are this:
`Here is a line from a MUD. It has some words and then some more words and then word
wrap.`
Happy @Eraene.
Fix https://github.com/Mudlet/Mudlet/issues/1928.
=> Fix punctuation being put on a line of their own when wrapped

src/ctelnet.h
Remove unused boolean from the `ctelnet` class which was added during SSL work.
Less Coverity complaints.
=> Remove unused SSL-status boolean from ctelnet

src/mudlet.pro
They were thus missing from the view within the Qt Creator IDE:
* ../3rdparty/discord/rpc/include/discord_register.h
* ../3rdparty/discord/rpc/include/discord_rpc.h
* ../.crowdin.yml
* ../.gitignore
* ../.gitmodules
* ../COMMITMENT
* ../translations/translated/updateqm.pri
* ../CI/mudlet-deploy-key.enc
* ../CI/copy-non-qt-win-dependencies.ps1
* ../CI/mudlet-deploy-key-windows.ppk
* ../CI/qt-silent-install.qs
* ../CI/travis.compile.sh
There is no change to the code so it is not going to be helpful to run the CI processes - but it does mean that merging may have to be done by @vadi2 to force it past the requirement to have CI passes.
=> Update: include some files in qmake project that were missing [skip CI]

src/ui/vars_main_area.ui
This is so that there is no colours to interfere with dark Desktop or Mudlet application themes.
The widgets have been rejigged and a vertical spacer inserted at the bottom so that in certain situations that may arise in conjunction with other changes forthcoming in the Editor (get the splitter working properly) the details area does not swell up to grab the whole right hand side of the editor such there be no other widgets in the whole of the right side.
=> Revise: remove colour palettes from vars_main_area.ui

src/ui/timers_main_area.ui
This is so that there is no colours to interfere with dark Desktop or Mudlet application themes.
=> Revise: remove colour palettes from timers_main_area.ui

src/dlgTriggerEditor.cpp, src/ui/trigger_editor.ui
The palette settings there do not work well when using a dark theme, removing the previous palette details does not seem to have any other side effects.
At the same time I have also renamed the editor control:
* `(QCheckBox*) dlgTriggerEditor::button_displayAllVariables` ==> `dlgTriggerEditor::checkBox_displayAllVariables`
because it *is* a `QCheckBox` and not the `QPushButton` it once was!
I also managed to simplify the widget structure on the left side of the editor - by removing some container widgets - this should make the layout work better in extreme cases or if some text elements change their needed sizes when the GUI language is changed.
=> Revise: remove colour palettes from editor search area

src/dlgTriggerEditor.cpp, src/ui/system_message_area.ui
Refactor the `system_message_area.ui` file to remove all uses of palettes, for the places where some colouration is required this can be done by a much less verbose stylesheet - which was already being used for one particular widget. Some simplification also removed some unneeded widgets which will make the form layout work better because there are less nested layouts. However an additional vertical spacer is needed so that the whole of the rest of the widget can be made to only be as large as necessary to display the text should there be NO other widgets on display in the splitter. This is a change that is also prompted by the desire to make the notification area be able to expand to show longer messages.
Remove the yellowish colouration of the root items in the `treewidget_XXXX` for …
=> Revise: remove colour palettes from system message area & dlgTriggerEditor

src/TConsole.cpp
Remove unnecessary double-if in selectSection debug
This should not impact https://github.com/Mudlet/Mudlet/pull/2440 by the looks of it.
=> Remove unnecessary double-if in selectSection debug

src/Host.cpp, src/TTimer.cpp, src/TTimer.h, src/XMLimport.cpp, src/mudlet.cpp, src/mudlet.h
This will split up the `QMap` in the `mudlet` class that contains all the `QTimer` & `TTimer` paired up in the `TTimer` class so that when a `Host` instance runs its `resetProfile()` method only the QTimers that are associated with the TTimers in THAT profile get removed from the `mudlet` map.  Previously all of them were nuked in that table.
Cleaned up the `TTimer` class - renamed the `(QTimer*) mpTimer` to be called `mpQTimer` because in some places we refer to instances of this class with a `mpTimer` member variable and sometimes we want to access the `QTimer` within and using the same name can lead to confusion.
This also lead me to discover that there was no need to include the latter in the arguments to `mudlet::registerTimer(...)` as it is already available from the previous …
=> Don't reset other profile's timers with resetProfile()

src/ctelnet.cpp
Remove the single `if (!mNeedDecompression) {` check on top because we already check it a few lines after.
Less confusing code.
Diff looks absolutely horrible...
=> Remove unnecessary if check in ctelnet decompression

src/TLuaInterpreter.cpp
Using the Lua function `setAppStyleSheet` will likely wipe out any local changes that Geyser and user scripts have made to things like labels (and gauges that are based upon them).  It is essential therefore for those to be aware that this has happened - so this PR provides a "sysAppStyleSheetChange" event that will be sent to ALL profiles when it is called from one of them. To allow individual bits of code to trace the origin of the call (in case it was responsible for it and must therefore not respond to it in the same way) an optional second (string) argument to the setAppStyleSheet call will propagate into the event passed by the system as a second argument (will be an empty string if omitted) and the source of the event (the profile name) will be included as a third argument.
At this …
=> Enhance: add Event when application Style-sheet set

src/Host.cpp, src/T2DMap.cpp, src/TConsole.cpp, src/TLuaInterpreter.cpp, src/TMap.cpp, src/TTextEdit.cpp, src/ctelnet.cpp, src/mudlet.cpp
Default-initialise Mudlet event objects before use
Less static analyser warnings? Possibly less side-effects too.
=> Default-initialise Mudlet event objects before use

src/dlgProfilePreferences.cpp, src/ui/profile_preferences.ui
radioButton_userDictionary_none is not used at all, was left over from prototype
We should not confuse translators
Fix #2436
=> Remove "no user dictionary" item

src/Host.cpp, src/TTimer.cpp, src/TTimer.h, src/XMLimport.cpp, src/mudlet.cpp, src/mudlet.h
This reverts commit 8a32c0b411a307f8d22867209cfb4f0614686f4b.
The improvement fixes a small problem that our users aren't really aware of, but it also introduces a bigger problem - Mudlet will crash in a timer after `resetProfile()` is used. We already have a fix for that in https://github.com/Mudlet/Mudlet/pull/2480, but the fix involves completely reworking how timers function - so it is not very safe to put in right before release.
Let's go back to how things were in 3.18 and make all of the changes for 3.20 just to reduce the risk of things going really bad, and us having more stress before&after release attempting to make things good.
=> Revert "Don't reset other profile's timers with resetProfile() (#2257)"

src/TLuaInterpreter.cpp
This was missed in #2467 as it was from a PR that was pending at the time that change was made.
=> Revise: add a change to TEvent usage to new TEvent instance

src/mudlet-lua/lua/DB.lua
i have a database like this:
```lua
local mydb = db:create("combat_log", {
kills = {
killtime = db:Timestamp("CURRENT_TIMESTAMP"),
name = "",
shortname = "",
location = "",
x = 0,
y = 0,
duration = 0,
ep = 0,
player = "",
},
})
```
and i have a trigger on kill with code like this:
```lua
local kill = {
killtime={_timestamp=os.time(os.date("!*t"))},
name=matches[2],
shortname=game.gegnerName,
location=ort,
x=x, y=y,
duration=game.fightTime,
player=playerName
}
--db.debug_sql = true
local succ, msg = db:add(mydb.kills, kill)
if not succ then
cecho("\n<red>"..msg.."<reset>\n")
end
```
and a trigger for EP (which come in on a short delay after the kill) with code like this:
```lua
local mydb = db:get_database("combat_log")
local results = db:fetch_sql(mydb.kills, "SELECT * FROM kills ORDER BY …
```
=> Fix db:add() when adding timestamp fieldsUpdate DB.lua

src/TConsole.cpp, src/TConsole.h, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h
Returns a table containing text attribute names and their values; booleans for: bold, italics, underline, overline, strikeout, and reverse and colour triplet tables for fore- and back-ground colours.
In the future I anticipate adding in the ANSI colour codes (0 to 255) used to produce the fore- and back-ground colours for text from the MUD - with some other special codes for certain other classes of text generated within the Mudlet application...
=> Enhance: add getTextFormat() function to Lua API

src/T2DMap.cpp, src/T2DMap.h
Whilst trying to locate my prototype code for `Z-exit lines` for the 2D Mapper I found this code that I had put to one side and which can go in as an enhancement - it scales the text used for the room numbers so that they fit better into the space available for them...
They now are scaled so that they fit the room symbol square - and are suppressed if they are too small to show.  Importantly this is done on the length of the longest number found in the area so that there will not be truncation - either they will all fit or none will. Also, leading zeros are used so that they are all the same size...
To distinguish between roomId and any user defined symbols for a room that might just be a series of numbers, the room Id numbers are also drawn in bold and with both an under- and an …
=> Enhance: draw RoomId numbers better in 2D Mapper

src/TAction.cpp, src/TAction.h, src/TEasyButtonBar.cpp, src/TEasyButtonBar.h, src/TToolBar.cpp, src/TToolBar.h, src/mudlet.cpp
The `objectName` is used to identify the item in the opaque data that is saved to preserve the size and position these items - so changing it is probably not a good idea.
This PR instead sets and modifies a (dynamic) property "layoutChanged" on each item instead.
It also revises the code used to reset the property on each item when the state details are saved, the replacement code is a bit clearer IMHO as it uses the Qt Java style iterators rather than the STL ones.
=> Revise: avoid changing the objectName of toolbars/docked windows on layout + add titles to toolbars

src/mudlet.pro
Remove `-lglut` from being linked to Windows binaries.
It does not seem it is actually necessary! Everything (including 3D mapper) works fine without it.
=> Remove -lglut for Windows linking

.travis.yml
Our macOS builds seem to be unable to upload their cache as they run into timeouts. We set the timeout to 10 minutes in the hopes to be able to upload the initial cache in that time and subsequent caches don't need as much time.
Speed up our macOS builds eventually.
=> Increase cache timeout

src/TLuaInterpreter.cpp
This is the fix that will close #2543 .
=> BugFix: correct argument cock-up and get permTimer(...) working again

src/ctelnet.cpp
If a package was manually installed and then offered as an update via the server, first time around Mudlet wouldn't know the servers package name and thus not install anything.
Now, instead of trying to uninstall a package named "nothing", it'll use the name of the package from the server as-is.
Fix https://github.com/Mudlet/Mudlet/issues/2394.
=> Fix scenario manually-installed packages not upgradable by servers

src/TLuaInterpreter.cpp, src/TMap.cpp, src/TRoomDB.cpp, src/TRoomDB.h
This will speed up roomID to hash lookups, as well as room
deletions. Added logic to keep them in sync and avoid duplicates.
Split and renamed TRoomDB hashTable.
Speed up roomID to hash lookup, and also deletion by roomID.
=> Split and renamed TRoomDB hashTable.

src/TMap.cpp, src/TRoom.cpp
This will close https://github.com/Mudlet/Mudlet/issues/2558 .
The bug was made in https://github.com/Mudlet/Mudlet/pull/2106/ which has been present since before Mudlet 2.16.0 was released·
=> BugFix: save & load custom line colors in map format version less than 20

src/TBuffer.cpp, src/TBuffer.h
- Change MXP state from being "on/off" to support the line / default modes from the MXP standard
- MXP mode resets to current default mode on newline (but not on <br> tags)
- Slight tweak to <SEND> tag detection by including the opening < in the substring match
Improve MXP support by allowing use of locked mode (to print from the mud without needing to escape < as &lt; etc) and temp secure mode before each tag.  (Muds can work around Mudlet's limitations by manually resetting to locked mode immediately after each opening / closing tag but it's nicer to obey the temporary mode).
Ideally OPEN and SECURE mode would be different (it still allows all tags regardless of if it is in open or secure mode)
=> Proposed mxp fix

src/TRoom.cpp
Fixed off-by-1 error in setSpecialExit
It is now possible to have a special exit that goes to room 1
attached test code. run before and after to see difference
[testSexit1.txt](https://github.com/Mudlet/Mudlet/files/3228671/testSexit1.txt)
**NOTE** This is a new version of #2575 which I messed up... I'm very sorry @LiamLeFey @vadi2
=> Fixed: impossible to add special exit to room 1.

src/dlgConnectionProfiles.cpp, src/dlgConnectionProfiles.h, src/mudlet.cpp, src/mudlet.h
Added Load button to profile selection dialog, which loads profile but does not connect.
Issue #700 
And I wanted it.
=> Add support for opening a profile offline

src/TBuffer.cpp, src/TBuffer.h, src/TLuaInterpreter.cpp
Fix use of unintialised slice.mEchoText when using copy() and rename to something more friendly - "if em echoing text then" reads better than "if em echo text then".
Less Coverity issues.
=> Fix use of unintialised slice.mEchoText when using copy()

src/Host.cpp
Fix the following problem:
```
*** CID 1479659:  Uninitialized variables  (UNINIT)
/home/travis/build/Mudlet/Mudlet/src/Host.cpp: 1747 in Host::setName(const QString &)()
1741         }
1742     
1743         QMutexLocker locker(& mLock);
1744         if (mHostName == newName) {
1745             // Oh, it hasn't changed after all so put the player room back and bail
1746             // out:
>>>     CID 1479659:  Uninitialized variables  (UNINIT)
>>>     Using uninitialized value "currentPlayerRoom" when calling "insert".
1747             mpMap->mRoomIdHash.insert(newName, currentPlayerRoom);
1748             return;
1749         }
1750     
1751         mHostName = newName;
1752         // We have made the change so can unlock the mutex locker and procede:
```
Don't have weird …
=> Fix player's current map location changing when renaming to same Host

src/dlgTriggerEditor.cpp, src/ui/triggers_main_area.ui
This attempts to make the code that shows/hides the controls to the right and bottom of the `triggers_main_area` form/dialogue not depend on hard coded settings but rather on the actual space that various widgets claim they need to be shown correctly (and not to show them if there is not enough).
This should help to address: https://github.com/Mudlet/Mudlet/issues/2548 .
=> Refactor: improve handling of show/hiding some trigger editor controls

src/TConsole.cpp, src/dlgTriggerEditor.cpp, src/mudlet.cpp
The previous code in `(void) TConsole::closeEvent(QCloseEvent*)` assumed the `TConsole` for a user window's `objectName` was what was used as a key in the profile's main `TConsole`'s `<QString, TConsole*> mSubConsoleMap` and `<QString, TDockWidget*> mDockWidgetMap`.
In fact for user windows the object name was never set for the `TConsole` and it would not be a good thing to have both the `TDockWidget` and the `TConsole` have the same `objectName` anyhow.  To further confuse things, the process of constructing the `TConsole` for a user window did not set a `(QString) mConsoleName` so the default of `"main"` was set for that member.
This PR revises the design so that the `TConsole::closeEvent` DOES find the wanted item in the main `TConsole`'s `mSubConsoleMap` and `mDockWidgetMap` so that …
=> BugFix: ensure user windows closure when profile is closed if multi-playing

src/TRoomDB.cpp
Try out fix as suggested in https://github.com/Mudlet/Mudlet/issues/2557#issuecomment-498848656.
Fix crash.
Fix https://github.com/Mudlet/Mudlet/issues/2557.
=> Fix room deletion crashing in a rare case on Windows

src/T2DMap.cpp
As requested in the issue below this converts the room Id numbers when
shown in the 2D Mapper to be padded with leading spaces rather than leading
zeroes.
Note that the numbers are shown only when the longest (most digits) Room
Id number for the displayed area can be displayed at a readable size -
otherwise the mapper switches back to displaying room *symbols* if they
will fit inside the room rectangle/circle.
This closes https://github.com/Mudlet/Mudlet/issues/2560 .
=> Revise: do not pad RoomId numbers with zeros on 2D map

src/ui/profile_preferences.ui
Trim tooltip text. Remove obsolete HTML. Split text in two paragraphs.
Improve readability.
Fix #2601
=> Trim settings tooltip for 'show map errors' even more

src/TLuaInterpreter.cpp
Rephrase info shown for setAreaUserData() and setMapUserData() on old map versions.
Keep info texts to relevant minimum
Found during translation here: https://crowdin.com/translate/mudlet/137/en-de#79941
=> Trim info text for old map versions

src/TLuaInterpreter.cpp
Texts shown when required Lua modules are loaded now parameters for the name of module and an optional more detailed error message.
Combine multiple very alike texts into one, so translators have less work.
Found issue during translation here: https://crowdin.com/translate/mudlet/137/en-de#89862
This whole section seems very repetitive. 
Maybe make another issue to create a function for this?
=> Parametrize texts for Lua modules

CI/appveyor.install.ps1, CI/qt-silent-install.qs, setup-windows-sdk.ps1
Updates the Qt installed by the SDK to 5.12.2 to be even with appveyor again.
In this light, other dependencies are updated on windows as well.
Up-to-date software and a working SDK setup again.
Closes #2536
=> Update SDK setup

src/dlgTriggerEditor.cpp
"New alias" should not loose their name while they are still new
Less empty named items
Fix #2637
=> Keep "New alias" if no regex exists

src/dlgTriggerEditor.cpp
Emphazise special actions at the end of the toolbar
The first buttons let you view and edit created items (and groups) in this very editor window.
The last three buttons are different:
* Error - superimpose error pane in editor window
* Statistics - display numbers in main window (maybe move this elsewhere eventually?)
* Debug - open a new debug window with precious information
Top toolbar has some seperators between different items.
Green line indicates the new seperator on left hand toolbar.
=> Add seperator to editor window

src/XMLexport.cpp, src/dlgPackageExporter.cpp, src/dlgPackageExporter.h, src/mudlet.cpp, src/ui/dlgPackageExporter.ui
The previous code would silently fail when using `zip_file_add(...)` if the item to be added was actually a directory. This commit fixes that by examining each "file" that is to be added to the archive file and deduces all sub-directories that need to be made and arranges for those to be inserted (with `zip_dir_add(...)`) first before populating the archive with the actual files.
It also refactors the code so that a pass/fail message is displayed at the end of the package exportation operation - and so that the dialogue is not closed until the user has clicked on a suitable button ("Cancel" before the package is exported, "Close" if the process failed and "Okay" if it succeeded). The revised success message also retains a suggestion (with a clickable link) to upload the ".mpackage" to the …
=> BugFix: allow packages with sub-directories & get exporter to report result

.travis.yml, CI/travis.compile.sh, CI/travis.linux.after_success.sh, CI/travis.osx.after_success.sh, CI/travis.set-build-info.sh, CMakeLists.txt
This will make it a bit easier to determine the travis builds that are deployed as travis will list the environment variables in the job view. Additionally, deployed builds are less hard coded and we can generalize the deployment bot, see Mudlet/deployment-link-probot#11
A bit more info at a glance and less hardcoding.
Closes #2600
=> Generalize travis deployment jobs

CI/travis.linux.after_success.sh, CI/travis.osx.after_success.sh
Use our own `make.mudlet.org` for deployment instead of `transfer.sh`
`transfer.sh` is not reliable and fails often, messing up our builds and draining energy.
=> Change deploys to make.mudlet.org

src/mudlet.cpp
Remove double-declaration in createMiniConsole - `pC` is declared just a few lines above.
Better code.
=> Remove double-declaration in createMiniConsole

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/mudlet-lua/lua/Other.lua
This creates a key-value "mudlet.translations._language_" table as well as a "mudlet.translations.interfacelanguage" key. The table will hold the translations of normal directions and the key holds the current interface language.
Note that due to limitations in Qt, only one language is ever populated at a time: the current interface language. You cannot load translations from other languages other than the one you're using, not without a lot of work. This means that a Spanish person playing a German game that only accepts German directions for input won't be able to use Mudlets speedwalking - but since we've been stuck on this very rare usecase for the last year without any progress, I think it's an acceptable compromise.
I've added a companion function `translateTable()` which given a …
=> Added translatable directions and a function for scripters to use

src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h
Reduce complexity dlgTriggereditor's fillout_form by splitting out into separate methods. Note that this does not reduce the duplication involved.
Fix https://github.com/Mudlet/Mudlet/issues/2682
The diff is terrible to read - here's the actual method now:
```cpp
void dlgTriggerEditor::fillout_form()
{
mCurrentView = EditorViewType::cmUnknownView;
mpCurrentTriggerItem = nullptr;
mpCurrentAliasItem = nullptr;
mpCurrentKeyItem = nullptr;
mpCurrentActionItem = nullptr;
mpCurrentScriptItem = nullptr;
mpCurrentTimerItem = nullptr;
mpCurrentVarItem = nullptr;
mNeedUpdateData = false;
mpTriggerBaseItem = new QTreeWidgetItem(static_cast<QTreeWidgetItem*>(nullptr), QStringList(tr("Triggers")));
mpTriggerBaseItem->setIcon(0, QPixmap(QStringLiteral(":/icons/tools-wizard.png"))); …
```
=> Reduce complexity dlgTriggereditor's fillout_form

src/dlgTriggerEditor.cpp
Updates edbee-lib to allow custom autoScrollMargin. Sets default margin 12. A better default, or a number dependent on font size can be discussed, or used at a later date. Could probably get away with a smaller one. Also, modifies dlgTriggerEditor to allow edbee to scroll to keep the cursor on-screen again.
It's really irritating when the screen doesn't scroll with your cursor.
Helps to resolve https://github.com/Mudlet/Mudlet/issues/1986
=> Fix code editor to scroll when cursor goes off screen

README.md
=> Modernize README

src/dlgConnectionProfiles.cpp
Remove self-test profile from release build
We don't have adequate documentation to introduce this feature to the users yet - so let's keep it for developers in 3.22 and hopefully present it publicly in the next release after.
Just announcing a feature when there's no documentation for it or examples to copy from isn't very good.
=> Remove self-test profile from release build

src/Host.cpp
This reverts commit fb8e276379d279bdeeb28e0a3690b56aeb6b9d55.
We're going to be stressing out a lot of people by making them update their packages ASAP for the new Mudlet.
We'll announce that we're changing it next release in first week of August 2019 instead.
Also mention that `getCommandSeparator()` exists and players can always adjust the command separator to what they'd like.
=> Revert "Change default command separator to ;; (#1866)"

src/mudlet-lua/lua/Other.lua, translations/mudlet.ts
`translateTable()` would only keep texts it knew about:
```
lua mmp.speedWalkDir
{
"nw",
"nw",
"nw",
"n",
"n",
"enter grate",
"n",
"ne",
"ne",
"up"
}
lua translateTable(mmp.speedWalkDir)
{
"сз",
"сз",
"сз",
"с",
"с",
"с",
"св",
"св",
"вверх"
}
```
With this fix:
```
lua translateTable(mmp.speedWalkDir)
{
"сз",
"сз",
"сз",
"с",
"с",
"enter grate",
"с",
"св",
"св",
"вверх"
}
```
Fix discovered bug while testing and documenting the function.
=> Fix translateTable() losing non-translatable text

.appveyor.yml
Add Appveyor caching of 3rd party dependencies.
It takes a really long while to compile the same version of 3rd party libraries every time :(
And Appveyor only does it one build at a time for the entire project...
Typical Appveyor build takes 14-16 min, with the cache: half a 7-8min.
Look for the nice `Cache 'C:\Qt\Tools\mingw730_32' - Restored` line at the top of the logs :grinning:
=> Speed up Windows Appveyor builds by 2x

.github/main.workflow
Temporarily disable automerge check on status, since Travis tends to spam us with a lot of events, as @keneanung has figured out.
Don't have up to 50 'automerge cancelled' spams in checks.
=> Temporarily disable automerge check on status

src/TLuaInterpreter.cpp
Simple check if the area name given to `deleteArea()` is actually same as `host.mpMap->mpRoomDB->getDefaultAreaName`
Deleting the default area would create all kind of problems when you continue mapping later.
This should fix #2728
=> Prevent deleting the default area

src/mudlet-lua/lua/utf8_filenames.lua
Fix broken io.lines() after Windows utf8 override
Emergency hotfix.
Fix https://github.com/Mudlet/Mudlet/issues/2741.
There's a difference between `callfunction(nil)` and `callfunction()` as far as the Lua C API is concerned and this is one of those cases :(
=> Fix broken io.lines() after Windows utf8 override

src/mudlet-lua/lua/utf8_filenames.lua
Update rest of Lua IO functions to have same behaviour when called without arguments
Most of them read from STDIN, which is not relevant in the context of Mudlet, but it's good to have the functions behave in the same way across all platforms either way.
Consitency
See https://github.com/Mudlet/Mudlet/pull/2756 for the original important fix
=> Update rest of Lua IO functions to have same behaviour when called without arguments

src/mudlet.pro
Update default MinGW path to 7.x, since that's what we use now.
Fix a potential issue.
Perhaps this is why stand-alone Qt Creator builds are failing yet the windows SDK setup script works fine.
=> Update default MinGW path to 7.x

.travis.yml
Cache `brew update` per instructions on https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9 from the Homebrew maintainer.
Remove 5min from every macOS build, which we seem to be especially limited on. Some PRs can take 2h to build because of how delayed our macOS backlog is.
Before
After
=> macOS CI: cache 'brew update' to remove 5min from every build

src/main.cpp
Don't make the super-advanced Qt CLI arguments translatable.
It's a lot, a lot of burden on translators to translate this amount of very technical text and keep the correct formatting for very little to none benefit.
The only people who'd seriously consider using these arguments would also have a decent grasp of English to understand the text.
=> Don't make super-advanced CLI arguments translatable

src/mudlet.cpp, src/mudlet.h
Consolidate package/module manager buttons + add exporter.
Package exporter was always missing from the toolbar, which meant there was a discrepancy in functionality between the menubar and the toolbar. 
Also, having both `Package Manager` and `Module Manager` really blew up the width by a fair bit.
Next I'd like to make it so new Mudlet installations don't have _both_ menu and tool bars enabled by default - it is redundant and takes up screen space!
=> Consolidate package/module manager buttons + add exporter

src/dlgTriggerEditor.cpp
Fix code editor search to scroll to result
Fix broken search from 3.22 release.
It was broken by https://github.com/Mudlet/Mudlet/commit/6f74322433a4691b9aa9c0bdddd83601ae5b5998 which turned off scrolling when you selected a search result (@dicene any reason why?) but also before this commit, scrolling was turned off for _normal_ scrolling, which is why the code editor didn't scroll at all (also strange).
Now everything scrolls as it should.
Fix https://github.com/Mudlet/Mudlet/issues/2724.
=> Fix code editor search to scroll to result

src/dlgConnectionProfiles.cpp, src/dlgConnectionProfiles.h, src/ui/connection_profiles.ui
Add a new button to copy profile's settings only. 
This is great for copying colour schemes and settings such as the command separator, while not having the rest of the scripts that come with the profile.
It's a simpler solution to the default command separator preference we have: people can choose to create a copy of an existing profile instead of having to change the command separator every single time.
It's also a simpler solution to keep colour schemed organised: don't have to create, name them, manage them - just copy from the profile you like.
Fix https://github.com/Mudlet/Mudlet/issues/2737.
=> Add 'Copy profile (settings only)' button

src/TLuaInterpreter.cpp
Test with: `lua feedTriggers("Ты слышишь скрип мачт и крики чаек.\n")` and encoding set to `KOI8-R (Cyrillic)` for example, which is a very real scenario when playing a Russian game. You'll get this jibberish because feedTriggers is trying to interpret the utf-8 encoded text from Lua as `KOI8-R`:
With this fix, input into feedTriggers is independent on the server encoding as it ought to be.
i18n goals.
Fix https://github.com/Mudlet/Mudlet/issues/1946
=> Fix feedTriggers to work no matter what server encoding is set to

src/mudlet.cpp, src/mudlet.pro
Toggle display of text beneath "About" icon as expected
Show text only if players want to see text
Fix #2746
=> Toggle "About" icon text display

.travis.yml
This reverts commit a86b9d6021c892cd546e978e4a8202c66a182d0a.
This broke macOS binary builds, because `brew` is deleted by the time we need it for the packager.
Will be reinstated as part of https://github.com/Mudlet/Mudlet/pull/2781.
=> Revert "macOS CI: cache 'brew update'"

src/dlgTriggerEditor.cpp, src/ui/triggers_main_area.ui
Before:
You can't see the full path to the sound file and the tooltip isn't particularly enlightening in telling the player that they can select `Choose file` to choose a sound file!
After:
Full location to the sound file so you can tell exactly where it came from.
Better usability.
=> Show full path to sound file instead of explanatory tooltip

src/dlgAboutDialog.cpp
Remove "Gitter" from "about" Mudlet 
Gitter is not used anymore
Discussion in #1802 item 16
=> Remove link & mention of Gitter

src/TLuaInterpreter.cpp, src/ctelnet.cpp, src/ctelnet.h
Improve cTelnet::setEncoding argument naming
Less confusing codebase with no names like `isToStore`!
See https://github.com/Mudlet/Mudlet/pull/2791
=> Improve cTelnet::setEncoding argument naming

src/mudlet-lua/lua/Other.lua
permSubstringTrigger() creates a trigger group only if it is passed an empty set of patterns, but we passed it a set with one empty pattern instead by accident.
Fix permGroup() to pass an empty set rather than a set containing a single empty string. 
Have to pass the empty set in order to actually have Mudlet create a group/folder. With the empty string inside it, it was creating an actual substring trigger.
We found and discussed this in discord but then the fix never quite made it into a PR.
=> Fix permGroup for triggers to make a folder

src/TTextEdit.cpp, src/TTextEdit.h
This will close https://github.com/Mudlet/Mudlet/issues/2797.
The setting is for tabs every 8 normal width characters - this could be made adjustable for each `TTextEdit` class instance but that is left for as a future coding option if needed.
Closes https://github.com/Mudlet/Mudlet/issues/2039.
=> BugFix: render tabs correctly

src/Host.cpp, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h
Faster profile load: don't load formatter until needed. Once needed, it's loaded on demand and the user doesn't notice because it is fairly fast (60-200ms)
Shave off 60-200ms from Mudlet's profile load, and also use less memory! It is very possible that a player will never need to format code during their playing session.
... I also fixed a memory leak! We were never calling `lua_close()` on `pIndenterState` like we do on `pGlobalLua` :open_mouth: 
This is why `std::unique_ptr` is good. It'll take care of this for us automatically :)
Detected with the wonderful [hotspot](https://github.com/KDAB/hotspot) tool.
=> Faster profile load: don't load formatter until needed

src/dlgTriggerEditor.cpp, src/ui/triggers_main_area.ui
Reset sound location tooltip when sound is removed
Fix oversight from previous PR.
Note that there is no issue with the tooltip when there is no sound set:
=> Reset sound location tooltip when sound is removed

src/T2DMap.cpp, src/T2DMap.h
No functional changes.
Just create a separate `T2DMap::paintMapInfo` method so `paintEvent` isn't one giant mess and really hard to work with.
This makes it much easier with profiling because we can now see how much painting the map info took in the overall picture:
And we can see how within the method we spend the time:
The overhead of calling the function is negligible when Qt's basic primitive paint functions take most of the time spent.
(credit to [hotspot](https://github.com/KDAB/hotspot) for profling)
Mapper code less scary, so more people are inclined to work with it! :)
=> Factor out drawing map information label into a method

src/TLuaInterpreter.cpp, src/ctelnet.cpp, src/ctelnet.h, src/mudlet.cpp
`reconnect()` and the Reconnect button work fine for reconnecting, however if you connected to an entirely different profile using `connectToServer()` and decided not to save the new parameters, reconnecting would still connect to the profile's address and port, instead of the custom one. If you saved the values, then it would connect just fine.
This makes the behaviour be more intuitive, reconnect always reconnects to whatever you were connected to last.
More intuitive behaviour as one would expect.
=> Make reconnect() and Reconnect button respect custom connectToServer()

src/CMakeLists.txt, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/TTimer.cpp, src/TTimer.h, src/Tree.h
Now can do `tempTimer(1, function() print"yes" end, true)` to get the temp timer to repeat until killed.
Easier porting of MUSHclient scripts to Mudlet.
=> Add a repeating option to tempTimer

src/ctelnet.cpp
When I made 'reconnect' connect to the last parameters connect() from Lua was called with, instead of the profile's address/host, I broke offline+reconnect case: because you haven't connected to anything yet...
Simple fix, if last parameters aren't known, fallback to the profile's.
Bugfix.
This fixes what @maiyannah ran into.
=> Fix reconnect after offline profile load

src/XMLexport.cpp
Remove duplicate mAutoReconnect attribute, which is illegal in XML and breaks profile loading.
Fix profile loading to work.
Broken by the recent proxy saving.
=> Remove duplicate mAutoReconnect attribute

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h
* Review found mostly identical code in all 4 border functions
* Duplicate code moved to new joint setBorderSize function
* Error messages have been upgraded to be more helpful
* Erroneous links to documentation have been corrected
* Renamed ambiguous variable names from `x1` to `size`
* Added a new [setBorderSizes](https://wiki.mudlet.org/w/Manual:Lua_Functions#setBorderSizes) function:
- setBorderSizes()
- setBorderSizes(size)
- setBorderSizes(heights, widths)
- setBorderSizes(top, widths, bottom)
- setBorderSizes(top, right, bottom, left)
* Added the originally requested functions
* [getBorderTop](https://wiki.mudlet.org/w/Manual:Lua_Functions#getBorderTop)
* [getBorderRight](https://wiki.mudlet.org/w/Manual:Lua_Functions#getBorderRight)
* …
=> Refactor & upgrade setBorder* & add getBorder*

src/mudlet.cpp
Probably because of the slightly different includes for FreeBSD (maybe because it does not include any updater code) I need to add an additional `#include` in order to get Mudlet to compile for me.
=> Bugfix: add missing header for FreeBSD

src/TAstar.h, src/glwidget.cpp, src/glwidget.h
Remove unnecessary and outdated boost random which is not needed for compilation.
Fix `error: no member named 'bind2nd' in namespace 'std'` on a strict compiler that removes `std` functions gone in C++17.
=> Remove unnecessary boost/random.hpp

src/Host.cpp, src/ctelnet.cpp
Recent code to support the use of proxys uses classes that do not have some needed `#ìnclude`s to work on FreeBSD which has some slightly different header files usage compared to the standard OS triumverate of Windows/Linux/macOs.
I also spotted a miss-placed opening brace in a recently added method associated with the new ~~poxy~~ *proxy* code. :grin:
=> BugFix: add missing headers for FreeBSD (2)

.travis.yml, CI/travis.linux.install.sh
Downgrade to GCC 7 for official builds
Better compatibility with Linux releases.
I forgot that compatibility for older distros is against using a newer compiler... which is a pretty annoying limitation.
=> Downgrade to GCC 7 for official builds

src/TLuaInterpreter.cpp
Fix tempTimers getting toggled on to repeat randomly because the variable wasnt initialise with a value.
Important bugfix.
Only present in 4.0 development code.
=> Fix new tempTimers getting toggled on to repeat randomly

src/dlgProfilePreferences.cpp
Fix macOS crash when saving settings because the Sparkle updater is not initialised in development builds.
Caused by 861c4af22b70de2790b3cde6231005c83e3244c9 which stopped `updater->checkUpdatesOnStart();` from being run; that method created the Sparkle updater object.
=> Fix macOS crash when saving settings in testing/development builds

CI/appveyor.after_success.ps1, CI/travis.linux.after_success.sh, CI/travis.osx.after_success.sh
This PR fixes the DBLSQD attachment URLs to be HTTPS. It seems that DBLSQD doesn't follow redirects (might want to open that as a bug report with them), but downloads that file instead to create file size and SHA1 sums. With HTTPS, no redirects should be in the way.
Less manual steps for an update.
Fixes #2327
=> Fix dblsqd auto attachment

src/dlgAboutDialog.cpp
Patreon link will now be opened in system's standard browser.
Until now, clicking that link would try (and fail) to open the link internally. 
Thus showing a blank page with no way visible to go back to the supporters list.
Discussed in discord, fix #2920
=> Fix Patreon link in Supporters tab to open browser

src/Host.cpp
Delete unused autosave debug statement
Less spam in stdout.
No longer needed as autosave has been working fine for a long while.
=> Delete unused autosave debug statement

src/T2DMap.cpp
Fix hardcoded spacing in rooms list.
Before:
Now:
Squeeze a bit more out of screen real estate.
See https://github.com/Mudlet/Mudlet/pull/2937 for background.
=> Fix hardcoded spacing in rooms list

src/dlgProfilePreferences.cpp, src/ui/profile_preferences.ui
Fix proxy settings screen for when no profiles are loaded: don't make it so people can enable/disable it when there are no profiles open.
Better user experience.
=> Fix proxy settings screen for when no profiles are loaded

src/mudlet.cpp
Use of Qt's built-in autoHide QTabBar functionality instead of our own.
Less code! :)
It wasn't available when we started Mudlet back with Qt 4 :)
=> Use Qt's built-in autoHide QTabBar functionality

src/TCommandLine.cpp, src/TCommandLine.h
This makes is so you can use Ctrl+1 to select the first open profile, Ctrl+2 the second open profile and so on.
This is specicially designed in a way that if the player has already defined Ctrl+1, Ctrl+# as a custom keybinding - that will still work and take priority over this new keybinding; thus this won't break any profiles and annoy players.
User interest.
Closes https://github.com/Mudlet/Mudlet/issues/2424.
=> Add feature: Ctrl+# tab switching between profiles

src/T2DMap.cpp, src/T2DMap.h
No functional changes - just move the big chunk of the mapper code that paints all exits in the area into its own separate method. 
Make mapper painting code easier to understand.
Same as https://github.com/Mudlet/Mudlet/pull/2857.
=> Factor out drawing exits in the map into a separate method

src/T2DMap.h
The comment despite being 5 lines long does not actually explain what value this field holds! It is also wrong: this field is only ever used once.
More intuitive development, spend less time hunting down things based on wrong information.
I spent 10 minutes double-checking all of the code because of it...
This is why I don't like such long narrative in comments - it forces me to read the comment, it forces me to double-check the code because the comment could be wrong (and in this case, it is), and then I have to spend time reconciling the two and finding out the truth.
I prefer when things are a lot simpler: the comment explains what this field does, and the code explains how this field is used.
=> Fix incorrect explanation for mMaxRoomIdDigits

src/mudlet.cpp, src/mudlet.h
Fix userwindows not going away on profile close - the console they were belonging to was getting removed, but not the dock widget the console was in.
Bugfix.
Fix https://github.com/Mudlet/Mudlet/issues/2916.
=> Fix userwindows not going away on profile close

src/ctelnet.cpp
`QSslSocket::encrypted` was being connected to when it's not actually available :open_mouth: 
Bugfix.
Good thing we can find these things at compile-time thanks to the Qt 5!
=> Don't include TLS code in ctelnet when it's not available

.travis.yml, src/CMakeLists.txt, src/mudlet.pro
Now that Qt 5.11 is available in Debian stable, we can raise the minimum Qt version supported.
New classes and functions available for usage, no more having to remove `<colorrole role="PlaceholderText">` and so on.
Needed by https://github.com/Mudlet/Mudlet/pull/2943.
=> Raise minimum to Qt 5.11

src/TTimer.cpp
Fix Coverity TTimer mRepeating initialiser warning. This constructor isn't used so it didn't have a practical effect.
Less warnings! :)
CID 1415062.
=> Fix Coverity TTimer mRepeating initialiser warning

src/updater.cpp
Fix updateDialog uninitialised in constructor. Should be `nullptr` as creating it triggers an update check - so it is done at a later point.
Less warnings
CID 1415098.
=> Fix updateDialog uninitialised in constructor

src/LuaInterface.cpp
Fix nullptr warning around `curVar` - it's never happened, but it could!
Less possible bugs.
CID 1415098
=> Fix nullptr warning around curVar

src/TLuaInterpreter.cpp
Handle possible crash if we give an invalid roomID to getRoom() while searching for rooms.
Fix possible crash.
CID 1415023.
=> Handle possible crash if we give an invalid roomID to getRoom()

translations/translated/generate-translation-stats.lua
Make translation stats be optional at build time - because all they do is provide information for the gold star and translation %'s in Mudlet. Not having these stats is absolutely fine for Mudlet:
Of course official builds and all releases should have them - but in case the file can't be generated, it should not be a build-breaking issue.
It recently came up as an issue in building Mudlet for on Windows, Raspberry Pi, and it's an issue for analysis checkers like [LGTM](https://lgtm.com/projects/g/Mudlet/Mudlet/logs/languages/lang:cpp).
Less pain when building Mudlet.
=> Make translation stats be optional at build time

src/updater.cpp, src/updater.h
Fix LGTM updater class warnings. The destructor is a trivial thing but good to have anyway.
Less warnings!
See https://lgtm.com/projects/g/Mudlet/Mudlet/latest/files/src/updater.cpp?sort=name&dir=ASC&mode=list#V48
=> Fix LGTM updater class warnings

src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h, src/mudlet.cpp, src/mudlet.h
Currently, the "Script Editor" menu item(which is what Alt+E activates) forces your window to the Trigger View, even if the window is already open. This PR changes the behavior of that menu item to respect whatever view is already open, or was open last time the editor was up.
A very common workflow with any script editor is hopping back and forth between the editor window and whatever the script is running in, testing changes that you make repeatedly until you get a result you like. While this can be done with Alt+Tab, I think it would be valuable to have a means of reliably getting to the editor in one key-combination, rather than having to rely on the editor being the last thing you Alt+Tabbed to, or visually confirming as you tab through whatever other windows you've interacted with …
=> Change "Script Editor" menu entry to respect current view selection

src/mudlet.cpp
Adds a call to `activateWindow()` to all the toolbar Triggers/Aliases/Etc buttons. Currently, they raise the window and show it, but don't activate it, meaning that keyboard presses still go to the main window.
It's obviously not intentional that those actions don't also activate the window.
=> Fix toolbar buttons that open editor to activate editor as well

src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h
Adds a new shortcut of Alt+E to the trigger editor. When activated, it brings the Main Window to the front, activates it, and gives focus to the input widget, so you can hit Alt+E and immediately get back to typing in the main console.
If you use Mudlet a lot, and you are actively creating new triggers/aliases/etc, you're likely jumping between the main window and the trigger editor quite a lot. Having a single shortcut that toggles between the two means less fumbling around grabbing the mouse, and no accidentally Ctrl+Tabbing to the wrong window.
This PR, along with a few others, intends to bring Mudlet closer to being navigable entirely without needing to use the mouse.
=> Add new shortcut to the trigger editor 

src/Host.cpp, src/Host.h, src/TRoom.cpp, src/TRoom.h, src/TRoomDB.cpp, src/TRoomDB.h, src/ctelnet.cpp, src/ctelnet.h
From LGTM:
> A 'const' modifier on a member function return type is useless. It is usually a typo or misunderstanding, since the syntax for a 'const' function is 'int foo() const', not 'const int foo()'.
That's exactly what happened here (misunderstanding).
_actually_ mark readonly functions as readonly.
Fixes this LGTM query: https://lgtm.com/query/1192113587356471581/
=> Fix use of incorrect function const and add a few missing ones

CI/appveyor.set-build-info.ps1
Currently, testing builds on Windows use a bogus commit ID. This should fix the result.
Correct commit SHA-1 ids to cause less confusion.
Discussion on Discord a while ago and can also be seen on make.mudlet.org/snapshots
=> Use correct commit SHA1 for Windows builds

CMakeLists.txt
Clarify verbose compile-time settings. Recent tests with the new 3D mapper toggle showed that the very verbose descriptions don't work - both keneanung and demonnic missed them and tried using the wrong options.
Simpler, more intuitive experience for those compiling Mudlet.
Too much verbosity kind of backfired here.
=> Clarify verbose compile-time settings

src/ctelnet.cpp
**cTelnet::setGMCPVariables** function of **ctelnet.cpp**:
- Now also parses JSON for Client.GUI for example
```json
Client.GUI = {
"version" = "39",
"url" = "https://www.stickmud.com/mudwww/StickMUDv39.mpackage"
}
```
- Continues to parse raw telnet messages for example
```
Client.GUI 39\nhttps://www.stickmud.com/mudwww/StickMUDv39.mpackage
```
- Standardizes format to JSON that is used with other GMCP messages 
This will close Add JSON-friendly version of Client.GUI syntax, closes #2875  
_Note: StickMUD GUI in Windows Mudlet <= 4.0.3 is vulnerable to the Mapper Window sizing issue_
**JSON**
- Shutdown Mudlet
- Delete your StickMUD profile from the backend via CLI
- Start Mudlet
- Pick StickMUD inside Mudlet, login as `vadi` (others could be setup, send me a name before creating the …
=> Implement JSON for Client.GUI (Issue #2875)

src/TLuaInterpreter.cpp
Fix insertPopup and echoPopup to accept "main" as an argument.
More consistency in the API.
Needed by https://github.com/Mudlet/Mudlet/pull/3009.
`insertPopup()`'s code isn't up to our standards - but I'd just like to fix this one issue right now.
=> Fix insertPopup and echoPopup to accept "main" as an argument

src/TLuaInterpreter.cpp, src/TMap.cpp
This PR removes support for saving in the binary map file format of Mudlet 2.1 - i.e. format **16** (retaining the ability to read it) and adjusts the format for new map files to be **20** by default - up from the previous default of **18**. This should speed up map loading a little - as it will remove the need to convert the data to the current forms used internally as well as making some details more robust. It also allows the removal of some warning code that would have fired if area or map user data features were used and format *16* was selected for saving.
* dfce0f01ade0a5e330a699fbe2c747c5eb6b3a5d (PR #2106) - **20** Improved way that custom exit line data was held internally (so that the keys are now the same as the other exit details that are keyed by a string {doors, exit …
=> Update: drop support for saving to Mudlet 2.1 map format & update default

src/mudlet-lua/lua/geyser/GeyserLabel.lua
Currently, Mudlet supports Geyser.Label:echo("message", "optional color", "optional format") and stores the color and format for future use. In the final argument for format, we accept 'c' for center but had no equivalent for 'left' or 'right. This shifts to using the align= in the div tag for text alignment rather than the `<center></center>` tags it was using before, allowing us to easily add support for 'l' and 'r' as left and right alignments.
Someone asked about using 'l' and 'r' for left and right formatting in Geyser.Label:echo() and I was as surprised as they were it wasn't there.
=> Support left and right alignments in format strings for Geyser label echos

CMakeLists.txt, src/ctelnet.cpp, src/mudlet.pro
The code that made the inclusion of the 3D mapper dependent on the OS being Linux, Windows or macOs was misguided as the issue that was to be solved was that Raspberry Pis do not have hardware that can support the ancient *direct* dialect of OpenGL (pre-1.5) that we use.
{They support the OpenGLES form which is a reduced functionality OpenGL for embedded devices but which started off at a level comparable to OpenGL 2.0} These later versions only use the *indirect* form which is expressed in OpenGL ShaderLanguage a.k.a. GLSL.}
It is erroneous to depend on the OS being just those three because the primary OS used with the Raspberry Pi - called Raspbian - is itself a version of Linux - specifically Debian, which has been compiled with some additional support for the Arm 7 hard-fp (with …
=> BugFix: restore 3D mapper to FreeBSD

src/mudlet-lua/lua/geyser/GeyserLabel.lua
Adds 's' format option to Geyser labels for strikethrough
I had someone ask about strikethrough and realized Geyser didn't have a format option for it. So here it is.
=> Adding format option 's' for geyser labels to add strikethrough

src/mudlet-lua/lua/TableUtils.lua, src/mudlet-lua/tests/TableUtils_spec.lua
Adds a handy utility function for filtering table values that return true for a specific condition.
There are times when you'll need to grab specific items out of a table that meet a certain condition. This function simplifies the process. Here's an example:
```lua
function isBigEnough(value)
return value >= 10
end
local filtered = table.n_filter({12, 5, 8, 130, 44}, isBigEnough)
display(filtered) -- {12, 130, 44}
```
=> Add `table.filter` global function

src/mudlet-lua/lua/TableUtils.lua, src/mudlet-lua/tests/TableUtils_spec.lua
Adds a single function to the table class that allows users to flatten deeply-nested lists together.
I was attempting to implement a quicksort function and ran across some limitations with `table.n_union` that didn't allow me to get the result I wished. The example image below shows the limitation I faced, and the solution that adding this function would solve.
```lua
function quicksort(arr)
if #arr <= 1 then return arr end
local pivot = table.remove(arr)
local left = table.n_filter(arr, function(num) return num < pivot end)
local right = table.n_filter(arr, function(num) return num >= pivot end)
return table.n_flatten({quicksort(left), {pivot}, quicksort(right)})
end
quicksort({1, 9, 2, 8, 3, 7, 4, 6, 5})
```
=> Add `table.flatten` global function

src/dlgTriggerEditor.cpp
Fixes error/info block sizing in the trigger editor so that it does NOT expand to take up extra space.
Regression that occurred with 4.0
=> Fix error/info block sizing in trigger editor

src/TTextEdit.cpp, src/TTextEdit.h
This commit should allow the timestamp region on the left of the display in a `TConsole` to appear as if it were selected when the first OR last character in the main text is selected. This is so that selection of one or more lines of text seem to also include the timestamps - as they will be if copied and pasted elsewhere.
This might be (at least part of) the solution to: https://github.com/Mudlet/Mudlet/issues/2978
=> BugFix: allow clicking on timeStamp region of TConsole to select whole line

src/mudlet.cpp
Added code to update the display attributes of any selection as well, as the function setBold and others are intended to do.
setBold, setUnderline, etc were all claiming to update selections, but the function that was updating the formatting was NOT updating selected buffers, when it was being used on anything except for the "main" console.
=> Fix: setBold, setItalics, etc now apply changes to selections when used on named miniconsoles.

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h
Add postHTTP(), putHTTP() to interact with online services.
Functions:
`postHTTP("data to send", "url to send it to", (optional) {a_table="of headers to send"}, (optional) "file to upload")`
`putHTTP("data to send", "url to send it to", (optional) {a_table="of headers to send"}, (optional) "file to upload")`
`deleteHTTP("url to send it to", (optional) {a_table="of headers to send"})`
The syntax is similar to `sendGMCP`, `sendATCP`, `sendMSDP`.
Events:
`sysPutHttpDone`, `sysPostHttpDone` `sysDeleteHttpDone` - URL and response body are the event arguments. Response body is only added if it's less than 10k characters in length, because some responses were all on one line and line wrapping 100k character line takes... a while.
`sysPutHttpError`, `sysPostHttpError`, `sysDeleteHttpError` - …
=> Add postHTTP(), putHTTP(), deleteHTTP() to interact with online services

src/TLuaInterpreter.cpp
Log URL accessed with downloadFile() in Debug console
More transparency for the user - this can't hurt.
Same as https://github.com/Mudlet/Mudlet/pull/3020, but for the existing `downloadFile()`.
=> Log URL accessed with downloadFile() in Debug console

src/TConsole.cpp, src/mudlet.cpp
Adds manual updates to the functions that modify the formatting of a selection, so you don't need to add an extra `echo("")` or click on the buffer to get formatting changes to show.
If you're use `setBold`, `setFgColor`, or other similar selection format modifying functions, you then have to either click somewhere in the console, or `echo` to the console to update it, visually. This change causes these functions to update the console, because that's how it should work.
=> Enhance: Update consoles immediately when formatting is changed.

src/dlgConnectionProfiles.cpp
Changed comparison operator in dlgConnectionProfiles::fillout_form() to prevent a divide by zero exception when deleting all profiles. (Deleting default profiles on firstMudletLaunch)
Fixing crashbug.
Closes #3044
=> Corrected a divide-by-zero error (fixes #3044)

.gitmodules, .travis.yml, CMakeLists.txt, src/CMakeLists.txt, src/dlgAboutDialog.cpp, src/dlgConnectionProfiles.cpp, src/dlgConnectionProfiles.h, src/main.cpp, src/mudlet.cpp, src/mudlet.h, src/mudlet.pro
Store character's login passwords securely (the ones in the connection screen).
While it's very unlikely that a hacker who gets access to someone's machine will specifically go after their MUD characters password - there are many more valuable things to go after - it's still a good idea!
1. the password field in Mudlets connection window should still have your password
1. the `password` file in your profile's directory should be gone
1. your OS's credential manager should list the passwords instead:
Close https://github.com/Mudlet/Mudlet/issues/1917.
Note that once you use this test version of Mudlet which migrates passwords to secure storage - normal Mudlet which doesn't have support for secured passwords, obviously, won't be able to read them. Keep this in mind: if you notice your …
=> Store character's login passwords securely

src/TDebug.cpp
Fix error messages printed regardless if error console actually exists - which doesn't anymore until you open it :wink: 
Fix a crashing issue.
=> Fix Mudlet 4.1 crash with getLastLineNumber("invalid console")

src/mudlet-lua/lua/geyser/GeyserContainer.lua
The flash() function was checking for the wrong field to see if it needed to set a click callback during the flash. Since we have double click callbacks, right click callbacks etc now, I opted to instead enable clickthrough on the label created by flash()
Was keeping me from clicking through to the tab on EMCO.
=> Make flash label clickthrough so it doesn't prevent callbacks

src/mudlet-lua/lua/geyser/GeyserGauge.lua
This changes Geyser.Gauge:echo() to pass along all arguments to the text label of the Gauge, so you can format your text, color it, etc the same way you would a normal Geyser Label.
It also causes it to respect the 'message' constraint the same way Geyser.Label does, by echoing it out to the text label.
Someone mentioned it wasn't working in the Mudlet discord, and I thought it made the most sense to give the normal label echo functionality to the gauges, and allow setting a message on instantiation.
Handles https://github.com/Mudlet/Mudlet/issues/3077
=> Geyser Gauge echo and message constraint improvements.

src/mudlet-lua/lua/generic-mapper/generic_mapper.xml
- add a link to Mudlet discord that opens the webpage, and consequently support for <urllink>
- delay `map basic` by 3s to send a `look` first, so...
- room name/exits are captured and shown in the help, if possible.
New look'n'feel:
So a first-time player has a clear idea of what to do to get the mapper going - which is `start mapping`, and if it doesn't work, `find prompt`, and if that doesn't work - well, figure out how to tune the mapper ask for help.
=> Improve generic mapper scripts 'map basic'

src/mudlet-lua/lua/generic-mapper/generic_mapper.xml
You start the generic mapper script for the first time, turn on `map debug`, start walking around and see this:
Why isn't it found... ? The room name and exits are detected fine.
What the script is really trying to say:
Because my map database is empty. Now it makes more sense :)
More intuitive mapper.
=> Clarify 'room not found' in generic mapper

src/T2DMap.cpp
A less ugly default for rooms without a known environment? A calm blue.
The generic mapper doesn't pick up environments so all rooms are red, and it's not a very appealing red.
Better first time player experience.
=> Render the default room colour as a more pleasing blue

src/mudlet-lua/lua/DB.lua, src/mudlet-lua/lua/TableUtils.lua
Bring table.is_empty() error message up to standard, and remove the duplicate definition.
Fix this really confusing error message you can see even though the are 0 databases involved:
```
DB.lua:28: bad argument #1 to 'next' (table expected, got nil)
```
=> Bring table.is_empty() error message up to standard

src/mudlet-lua/lua/generic-mapper/generic_mapper.xml
When you do 'clear moves' right now you don't know if you had any clogged up or not... now you do.
Better player experience.
=> Give a bit of comfort to 'clear moves' in generic mapper

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/ctelnet.cpp, src/ctelnet.h
Add getConnectionInfo()
So game-specific tweaks can be applied out of the box, and scripts don't have to trigger on login screens and etc to know what game you're playing.
This isn't enough to know what game you're playing, but it's a start. Perhaps we could have some Lua-side functions that come with a mapping of hostnames and IPs to the game name?
=> Add getConnectionInfo()

src/discord.cpp
Remove Discord game deduction warning
We're seeing it all the time and... there's nothing to do about it? It's not adding value.
Close https://github.com/Mudlet/Mudlet/issues/2813.
=> Remove Discord game deduction warning

src/Host.cpp
Filter invalid Discord invite of "0", because one game is sending it and it doesn't make much sense.
Remove `Game using a custom Discord server. Invite URL: "0"` from console output.
The game shouldn't send it, but lets filter it in our end too.
=> Filter invalid Discord invite of "0"

src/TLuaInterpreter.cpp, src/TMap.cpp, src/ctelnet.cpp, src/mudlet.cpp, src/mudlet.h
Allow GUI.Client URLs to follow redirects
So games' http to https redirects work.
Moved the common request to enable redirects into `mudlet.cpp` for re-usability.
=> Allow GUI.Client, Client.Map URLs to follow redirects

CI/travis.osx.install.sh
Cocoapods added a new dependency of concurrent-ruby which the gem does not install yet. It should be added in a soon to be published future version, but until then, we'll need to manually install it.
Fix macOS compilation.
=> Fix macOS compilation

src/main.cpp
Add missing newline in `--version` command line flag..
Fix this output:
```
$ ./Mudlet.AppImage --vaaaarsion
mudlet 4.1.2 
Qt libraries 5.12.3 (compilation) 5.12.3 (runtime)
Copyright © 2008-2019  Mudlet developers
Licence GPLv2+: GNU GPL version 2 or later - http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.vadi@volga:~/Programs/Mudlet$ 
```
=> Add missing newline in --version

src/dlgTriggerEditor.cpp, src/dlgTriggerEditor.h, src/ui/system_message_area.ui, src/ui/triggers_main_area.ui
Fix the grey area in the triggers section.
The feedback on it is that it's pretty annoying and a waste of space - which it is!
Fix https://github.com/Mudlet/Mudlet/issues/2631.
Note that the change that added the splitter also added the grey area to the aliases and keys sections - I'll fix that in follow-up PRs after this one is done. Better to do it one at a time.
Thanks to Thorbjørn Lindeijer of [Tiled](https://www.mapeditor.org/) for giving the stretching hint.
=> Remove grey area after error box in triggers

src/Host.cpp, src/TConsole.cpp, src/TMap.cpp, src/ctelnet.cpp, src/dlgConnectionProfiles.cpp, src/dlgIRC.cpp, src/mudlet.cpp, src/mudlet.h, src/updater.cpp
In other words - fix https://github.com/Mudlet/Mudlet/issues/3088 ...!
This forces the binary file format to be that which is used for Qt 5.12 if the **run-time** version of the Qt libraries are Qt 5.13 or later. This is needed to handle a change in the format that `QFont`s are saved/loaded in a binary form in a `QDataStream` but it also clamps the binary format to be equivalent to `QDataStream::Qt_5_12` everywhere I could see it used so that future Mudlet versions do not suffer further issues going forward when Qt revise the `QDataStream` format for the classes it handles.
This should also close https://github.com/Mudlet/Mudlet/issues/785 !
NOTE: THIS WILL BREAK THINGS TEMPORARILY FOR USERS OF MUDLET VERSIONS AFTER 4.0.1 OR THOSE WHO HAVE MANUALLY SET THE FILE FORMAT ON THEIR MAP TO BE …
=> BugFix ameliorate Qt changes to binary formats for QDataStream

src/TMap.cpp, src/mudlet.h
Load Mudlet maps from Client.Map as well
People expect to be able to export a Mudlet map and load it via `Client.Map`
We need a MUD server on `mudlet.org` so we can test these things ourselves.
Also fixed a bug that in the case the Host was unavailable, the reply would not be properly disposed of... though I've yet to see a case where the Host wasn't available.
=> Load Mudlet maps from Client.Map as well

src/TTextEdit.cpp, src/TTextEdit.h
Refactor the big `TTextEdit::mouseMoveEvent()` - extract 3 functions out of it and rename variables to make more sense. This lays the foundation for working on it easier.
Fix single-character selection where Mudlet would only start selecting from 2+ characters:
Part of fixing selection to work.
Instead of making a giant PR that "fixes" everything there is to fix with selection, I'll do it bit by bit. This means it's much easier to test and bugs are easier to find. This also means the faster the PR is approved, the faster I'll be able to work on the next bit.
=> Fix selection to select one character OK

src/mudlet-lua/lua/generic-mapper/generic_mapper.xml
Fix generic mapper config - can't set an option to true after setting it to false
Bugfix.
Once the fix is applied, configuration starts working again:
=> Fix generic mapper config - can't set an option to true after setting it to false

.travis.yml, CMakeLists.txt, src/mudlet.pro
This PR upgrades our macOS build environment to 10.13 High Sierra.
Homebrew doesn't provide bottles (precompiled binaries) for new versions of software anymore. That means that dependencies will slowly but surely start to require compiling, which will make our builds time out.
This means that we have to drop support for Mudlet on macOS 10.12 Sierra.
=> Upgrade macOS builds to 10.13 High Sierra

src/TLuaInterpreter.cpp
#2976 did a reasonable check for a non-null `TRoom` pointer but it was being performed in the wrong place. This commit moves the test to a better place (before it is first dereferenced) in the `TLuaInterpreter::searchRoom(...)` method.
=> BugFix: correct PR#2976

src/mudlet-lua/lua/GUIUtils.lua
Sort the colors by hue if not asked to sort alphabetically.
If asked to sort alphabetically, group equal colors together and ignore case sensitivity
Discussion in discord which led to https://github.com/Mudlet/Mudlet/issues/3138 being opened. 
The ability to sort was included, but defaulted to default table.sort behavior. Added function to sort by name which makes the snake case and camel case versions of the same colors = in the sort, so they're grouped next to each other.
Also, sorting by hue is more visually appealing. 
I have tested it in 4.1.2 and in the testing version from https://github.com/Mudlet/Mudlet/pull/3124 and it works in both.
=> Sort colors by hue by default.

src/TLuaInterpreter.cpp
In #2516 I had not spotted that I had made a couple of copy/paste errors when I created some error texts for bad argument types in a couple of stopwatch related functions...
Signed-off-by: root <slysven@virginmedia.com>
=> BugFix: fix function names in a couple of copy/paste errors in error texts

src/TTextEdit.cpp
This should close #3064 and close #3083 and also close #3097 !
It does mean that clicking and then dragging from a point beyond the end of the line will select the **last** grapheme on the line as the start point for the selection - which might not *quite* what is wanted (which could be to start the selection at the start of the *next* line if it becomes a *downward* drag) but it does clear up all those other issues...
=> BugFix: handle end of line better for selection by mouse

src/mudlet-lua/lua/generic-mapper/generic_mapper.xml
Initialise generic mapping script config on profile open, not connect
Bugfix.
This didn't matter before, but with Offline now being an option, the generic mapping script doesn't initialise its configuration until you load.
=> Initialise GMS config on open, not connect

src/CMakeLists.txt
This is a minor change to avoid a little code duplication for windows.
Less code
Relates to #1392
=> Move win32 executable flag to avoid code duplication

src/mudlet-lua/lua/generic-mapper/generic_mapper.xml
I previously changed the `sysConnectionEvent` to a `sysLoadEvent`, but never registered the event handler for it.
Also handle `currentExits()` being `nil` in `map help` and `map basic` display.
Fix script to work right when used before rooms are seen.
=> Fix initialisation of generic mapper

src/mudlet-lua/lua/generic-mapper/generic_mapper.xml
Add a 'show moves' alias for debugging what the mapper thinks your move command queue is.
Easier debugging.
=> Add a 'show moves' alias for debugging

src/mudlet.h
Both `(void) mudlet::layoutModules()` and `(void) mudlet::startAutoLogin()` are normal `public:` methods and do not need to be processed by Qt's `moc` {Meta-Object Compiler} so should not be declared as *slot* methods.
I spotted this whilst trying to find why my builds were all failing after PR #3182 had gone in when I was working on #3191 . This nice and short PR should pass the *non-complex* PR criterion with ease! :rofl:
=> Refactor: remove two `mudlet` non-SLOT methods from `public slot:` part

src/mudlet.cpp, src/mudlet.h
As the definition of `(void) mudlet::slot_report_issue()` is contained within `#if defined(INCLUDE_UPDATER)` ... `#endif` preprocessor directives the method is not defined when the updater code is exclude and was causing failures at the link stage of building.  This PR corrects this so that
the option to "report an issue" will only be available for "Public Test" versions that do have the updater code present - as they will do - but it will be disabled for other builds (release or general PR testing) from the official site and will not be present in the code when compiled with the environmental variable `WITH_UPDATER` set to `NO`.
=> BugFix: allow builds without updater code to compile/link

src/TLuaInterpreter.cpp
Following a discussion about this in the TinTin++ Discord channel I can see that there are strong reasons to believe Scandum's assertion that we have used a snippet of code that he produced to support MSDP (which is his creation) and which is present in the TinTin++ product which he maintains.
It is not entirely clear whether the code concerned was released as public domain or GPL but if it was the latter then it is not entirely unreasonable to mention where we got the code from - and avoid any confusion by third parties as to who came up with the code, which does seem to have arisen.
In placing a comment in the position I have, I am attempted to restore: "the in-source mention above the function that Heiko didn't include." that Scandum requests.
Signed-off-by: Stephen Lyons …
=> Licensing: add acknowledgement of TinTin++ MSDP code

.appveyor.yml, CI/appveyor.functions.ps1, CI/copy-non-qt-win-dependencies.ps1, CI/qt-silent-install.qs
Don't use Qt 5.13 for Windows builds, go back to latest LTS available.
It's the cause for https://github.com/Mudlet/Mudlet/issues/3211 😒
Fix https://github.com/Mudlet/Mudlet/issues/3211.
Perhaps newer Qt fixes it, but we're pretty limited in what we can select on the 2017 image, need to upgrade to 2019!
=> Don't use Qt 5.13 for Windows builds

.appveyor.yml
Use older image for Qt 5.12.3
Qt 5.12.3 is no longer available and 5.12.5 had issues in our testing.
=> Use older image for Qt 5.12.3

src/dlgNotepad.cpp, src/dlgNotepad.h
Add simple 2min autosave for notepad contents. Right now, notepad is only saved when the profile is closed.
In the rare case that Mudlet or computer crashes.
Only autosave if content was changed, to prevent laptop battery drain every 2min for no reason.
=> Add simple 2min autosave for notepad contents

src/AliasUnit.cpp, src/AliasUnit.h, src/Host.cpp
This PR causes aliases created with `tempAlias` to be reset upon calling `resetProfile()`, similar to `tempTrigger`, etc.
It makes it a lot easier to enable a development flow where your aliases are defined in external source files and required via `require`/`dofile`. You can create triggers, aliases, etc. with `tempAlias`/`tempTrigger`/etc, and simply call `resetProfile` when you want to reload changes. Currently this isn't the case, since aliases are not reloaded, causing old aliases to hang around.
=> Remove temporary aliases when calling resetProfile()

src/mudlet.pro
This was coming from mishandling the `XDG_DATA_DIRS` environmental variable - as environmental variables have to be converted to qmake variables before they can be used easily in the qmake profile file.
=> BugFix: revise to remove qmake project file error

src/Host.cpp, src/Host.h, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/XMLexport.cpp, src/XMLimport.cpp, src/XMLimport.h, src/mudlet.cpp
This commit is a rework of the original PR #2516 squash-and-merged with the bugfix that I proposed as PR #3162 but which became difficult to apply when the original PR was eliminated from the development branch because it has been reverted from the 4.2.0 release and then that had been merged into the development branch!
This PR allows stopwatches to be stopped and read at any time afterwards, for any number of times. It also:
* allows stopwatches to be destroyed - so ID numbers WILL get reused - with a Lua `(bool) destroyStopWatch((int) id)` function.
* allows them to be marked as persistent so that they are saved with the profile and reloaded again - if they were running then they will continue to increment when the profile is not loaded so they can be used to real time events outside of …
=> Enhance: overhaul stopwatches redux

src/TLabel.cpp, src/TLuaInterpreter.cpp, src/TTextEdit.cpp, src/TTextEdit.h
This applies to the main console window for a profile and now reports all mouse button presses and releases in the `sysWindowMousePressEvent` and `sysWindowMouseReleaseEvent` instead of only the first three (left, right, middle).
The code for the same things in Labels was checked and I found that we were generally okay there already except that we were fabricating native Qt mouse events for the mapper where it overlaid a label but we were using an older (Qt4 compatible) event that only handled one mouse wheel at a time and we were assuming it was for a vertical mouse wheel. As the owner of a mouse with two wheels that assumption is misplaced so I have rejigged `(bool) TLabel::forwardEventToMapper(QEvent*)` so that it can pass horizontal and vertical mouse wheel events in the future.
This …
=> Enhance add support for more than 3 mouse buttons

src/TConsole.cpp
Forgot this when I was producing #2621 as I tend to use the other form of the map in a floating/dockable window.
This might eliminate the CodeFactor suggestion that was being addressed by #3256 as then the members should always be initialised before use which they are not *without* this commit in place.
=> BugFix: ensure TMap members controlling 2D player room mark are initialised

src/dlgIRC.cpp, src/mudlet.cpp
This was reported on Discord by user Highope#9700 and I confirmed that when an IRC session is opened for a single profile (NOT multi-playing) and then the Mudlet application is closed the IRC session and the window are not closed. Whilst the `/quit` command will terminate them a seg. fault then immediately occurs because the `dlgIRC` destructor tries to save the settings but needs to use the `mudlet::self()` pointer which is a dangling one by that time.
This commit ensures that the IRC window is closed when the single profile is closed along with the Mudlet application. If this is not required then the change in the `mudlet.cpp` file could be omitted in which case the other changes in the `dlgIRC.cpp` file prevent a segment fault from using a mudlet` pointer that is no longer valid. …
=> BugFix: close IRC window when single profile session ends

src/TLuaInterpreter.cpp
Fix createStopWatch crash because not all variables were passed to the printf-like function.
Mudlet should never crash!
Also "name as string or autostart as boolean are optional, got nil!" sounds pretty confusing to me, so I've edited out the optional part, like with other messages. If it's optional, then don't complain that you got nil...
=> Fix potential createStopWatch when given nil crash

src/dlgAboutDialog.cpp, src/main.cpp
We do this manually so as to avoid offending those looking for "reproducible builds" - and thus we do not define the year as a value determined at compilation time (typically by manipulation of the `__DATE__` value)!
=> Update: revise displayed Copyright year to 2020

src/dlgProfilePreferences.cpp
Due to some internal differences when `WITH_MAPPER` is defined to `NO` the forward reference to `QPainter` in `qwindwsdefs.h` is not resolved in our `dlgProfilePreferences.cpp` - this PR corrects that issue.
This was brought to my attention by the user `lol#1046` on Discord who found this issue when trying to build Mudlet on a Raspberry Pi 4.
=> BugFix: allow compilation to complete when 3D Mapper is disabled

src/TConsole.cpp, src/TConsole.h, src/TLabel.cpp, src/TLabel.h, src/mudlet.cpp
Removes a `Host` pointer argument from several methods as it is cleaner to get the information when a `TLabel` is instantiated.
Also remove unused:
* `(bool) TLabel::mouseInside`
* `(bool) TConsole::createButton(const QString&, int, int, int, int, bool)`
TODO: migrate the `mudlet::setLabelXxxx(...)` methods to the individual profiles main `TConsole` instance.
=> Refactor: simplify some TLabel stuff

src/TMap.cpp
There is a  bug when downloading a map via the gmcp server request or by going to options and clicking download the map.  If the map directory doesn't exist, it fails to download the map.  This isn't a problem for XML maps since they're not stored in the map directory (for some unknown reason.)  I would have changed that, but I'm not sure if there would be other effects by doing so.
Fix a failure to download mudlet .dat map files.
Fixes  #3295
=>  When downloading a map, ensure map directory exists.

src/TLuaInterpreter.cpp
Used a for loop to iterate through ALL the arguments in sendMSDP, instead of just checking the first one, and throw an error if ANY are not strings.
sendMSDP currently crashes Mudlet if a nil value is passed on the 2nd+ argument
Applies to issue #3311
=> Change check for arguments to apply to ALL sendMSDP arguments

src/Host.cpp
setModulePriority() now works when called from install event - it previously didn't because the map holding priorities didn't have the module name inserted into it as it should have.
Bugfix.
Fix https://github.com/Mudlet/Mudlet/issues/3324
=> setModulePriority() now works when called from install event

src/TConsole.cpp, src/TConsole.h, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h
Note that this may require Geyser and the like to rethink how they handle labels so that they can remove their label metadata (e.g. for parent containers so that the data on labels that get destroyed from them gets cleaned up).
=> Enhance: add the ability to destroy labels without resetting a profile

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/mudlet.cpp, src/mudlet.h
Add getImageSize(). Use it like this:
```lua
local width, height = getImageSize("image location here")
```
So you can size a label appropriately when you download an image from the Internet. This is also necessary for an important script on the pkuxkx game.
Close https://github.com/Mudlet/Mudlet/issues/813.
I used a new thing here - std::optional, instead of the usual std::pair<bool, result> pattern - because we have access to it now, and it's much cleaner! See https://www.bfilipek.com/2018/05/using-optional.html about it.
=> Add getImageSize()

.appveyor.yml
The new image upgrade as of yesterday is giving a `Could not find qmake spec 'win32-g++'.` error.
Fix AppVeyor builds.
=> Fix AppVeyor builds due to image upgrade

src/mudlet-lua/lua/geyser/GeyserContainer.lua
When using container:show()  hidden elements also will appear.
With this change the elements which have the property hidden will stay hidden.
Especially when using the GUIFrame with anitimer or other elements which use hide()
it can cause a mess to show everything. The problem appeared on Discord
for example:
Brax Last Sunday at 10:12
I am playing with anitimers in the drag and drop framework, if I drag a container all the 'dead' timers reappear ? What am I doing wrong hehe
=> Geyser:show only unhidden children

src/TConsole.cpp, src/TConsole.h, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/mudlet-lua/lua/GUIUtils.lua, src/mudlet-lua/lua/LuaGlobal.lua, src/mudlet-lua/lua/geyser/GeyserContainer.lua, src/mudlet-lua/lua/geyser/GeyserGauge.lua, src/mudlet-lua/lua/geyser/GeyserGeyser.lua, src/mudlet-lua/lua/geyser/GeyserLabel.lua, src/mudlet-lua/lua/geyser/GeyserMapper.lua, src/mudlet-lua/lua/geyser/GeyserMiniConsole.lua, src/mudlet-lua/lua/geyser/GeyserReposition.lua, src/mudlet-lua/lua/geyser/GeyserUserWindow.lua, src/mudlet.cpp, src/mudlet.h
…in them
Add Labels, MiniConsoles, Gauges to the UserWindow.
Allow resetProfile() to reset also UserWindows (for testing)
createLabel([windowname],...) --new optional first parameter windowname (UserWindow Name)
createMiniconsole([windowname],...) --new optional first parameter windowname (UserWindow Name)
createGauge([windowname],...) --new optional first parameter windowname (UserWindow Name)
Geyser.Container:new({windowname="UserWindow"}) --new optional variable windowname which adds the Container to the UserWindow
New event: sysUserWindowResizeEvent -> Used to make Geyser reposition work
New function: getUserWindowSize(windowname) -> Used to get the UserWindow size (also for Geyser)
Every other day there are request for adding more functionality to the UserWindows. 
One of the mods …
=> Allow Geyser in userwindows

src/mudlet-lua/lua/GUIUtils.lua, src/mudlet-lua/lua/geyser/GeyserMiniConsole.lua, src/mudlet-lua/lua/geyser/GeyserUserWindow.lua
Some changes in Geyser.UserWindow to allow settings at creation.
addition for createConsole and bugfix for Geyser.MiniConsole
- Some settings like color, fontSize, wrapAt... were not included to work at creation of the UserWindow. 
- createConsole couldn't handle UserWindows. 
- Found a wrong function name in Geyser.MiniConsole
=> UserWindow Settings at creation

src/TLuaInterpreter.cpp, src/TLuaInterpreter.h
Add `unzipAsync(path, location)`, an asynchronous and better version of unzip().
Returns `true` if unzipping was able to start, or `nil+msg` if unzipping wasn't able to start. Once the unzip process is finished, either `sysUnzipDone` or `sysUnzipError` is raised with the zip location and the extract location as the arguments.
Documenting `unzip()` was a mistake as it's synchronous and freezes Mudlet - bad for the user experience. 
Close https://github.com/Mudlet/Mudlet/issues/3350.
Big thanks to `QtConcurrent::run()` for making async very simple.
=> Add unzipAsync()

src/mudlet-lua/lua/GMCP.lua
By changing gmod.reenableModules() execution time to after GMCP is enabled, this PR prevents the built-in Core.Supports.Set (https://github.com/Mudlet/Mudlet/blob/573eaaba4789fe3f541e73cbc1fb0f640b7f45e0/src/ctelnet.cpp#L1028-L1034) from overriding the gmod.reenableModules() Core.Supports.Add list.
Without this PR, every connection except the first may not enable gmod's registered modules, as the built-in Core.Supports.Set overrides them. This is the cause of #2970.
Alternatives:
* Replace the built-in Core.Supports.Set with Core.Supports.Add (I'm fine with implementing this one)
* Make gmod.enableModule() always send Core.Supports.Add (This shouldn't be necessary if gmod.reenableModules() works correctly)
Fixes #2970
=> Re-enable GMCP modules from gmod when GMCP is enabled rather than at connection time.

src/dlgProfilePreferences.cpp
Found this whilst working on something else that involved multiple active profiles and one of them being closed whilst their profile preferences dialogue was open - under those circumstances the Host specific data is cleared and disabled on the dialogue but clicking on the editor tab - which should have presenting a tab with no data on it instead caused Mudlet to crash because `Host::updateProxySettings(QNetworkAccessManager*)` was being called...
Although this causes a fatal crash, it is a rather *corner* case so I am only assigning it a **medium** priority whereas I would normal go *high*! :wink: 
=> BugFix: prevent crash if editor theme tab clicked without a Host anymore

src/Host.cpp, src/TLuaInterpreter.cpp
Fix module priorities not to get lost on saving, while still keeping `setModulePriority()` working if called during the module installation event.
Bugfix.
Fixes https://github.com/Mudlet/Mudlet/issues/3345.
I took a different approach to solving it this time - since it seems a few things down the pipeline rely on the presence of a module as a flag for something. Instead of adding every module at priority 0, the `setModulePriority()` function will instead set the value as needed.
=> Fix module priorities not to get lost

src/ui/connection_profiles.ui
Pressing `Tab` before navigated in this order:
Now it will be this:
Better a11t.
Not sure if this is a lot better, I have not actually tried it with a screenreader yet.
=> Improve tab order in the connection screen

src/ui/connection_profiles.ui
Give input elements a name so they can be read out. Other elements already have a name.
Better ayy1.
> This is the primary name by which assistive technology such as screen readers announce this widget. For most widgets setting this property is not required. For example for QPushButton the button's text will be used.
> It is important to set this property when the widget does not provide any text. For example a button that only contains an icon needs to set this property to work with screen readers. The name should be short and equivalent to the visual information conveyed by the widget.
=> Label input fields which require an accessibile name

src/TMedia.cpp, src/TMedia.h
A minor change to bring the Client.Media package more in line with the GMCP specification. The functionality tied to Client.Media is obsoleted and moved to Client.Media.Default.  Mudlet wiki updates will be published.
Before:
```
Client.Media { "url": "hxxps://example.com/" }
Client.Media.Load { ... }
Client.Media.Play { ... }
Client.Media.Stop { ... }
```
After:
```
Client.Media { "url": "hxxps://example.com/" } // Obsolete!
Client.Media.Default { "url": "hxxps://example.com/" } // Added!
Client.Media.Load { ... }
Client.Media.Play { ... }
Client.Media.Stop { ... }
```
See also:
- [Mud Client Media Protocol](https://wiki.mudlet.org/w/Manual:Scripting#MUD_Client_Media_Protocol) (MCMP)
- [Mudlet Documentation of MCMP](https://wiki.mudlet.org/w/Manual:Scripting#MUD_Client_Media_Protocol) …
=> Client.Media to Client.Media.Default

src/dlgNotepad.cpp, src/dlgNotepad.h
Without this, at least on Windows, a `local8Bit` encoding is used which breaks,  for instance, on Emoji characters in the notepad. As it happens I discovered this when working on a separate PR to ensure better behaviour with using Emoji characters in parts of Mudlet other than the main console window for each profile.
Note that the argument to `QTextCodec::codecForName(...)` is a `QByteArray` rather than a `QString` so does not need wrapping in `QStringLiteral(...)` AFAICT.
=> BugFix: force UTF-8 coding for notepad so that all languages work

src/TConsole.cpp, src/TConsole.h, src/TLuaInterpreter.cpp, src/TLuaInterpreter.h, src/mudlet-lua/lua/GUIUtils.lua
Adds the functionality of setLabelToolTip(labelname, tooltiptext, [duration])
This PR adds the functionality of adding a ToolTip to a Label
Lacking of this functionality
ToolTips are highly customizable as they are html. And they are also customizable by the StyleSheet option for example:
changing the ToolTips (from Label "testlabel") background and text color by
```lua
setLabelStyleSheet("testlabel", "QToolTip{background: yellow; color: blue; border:none;}")
```
=> add setLabelToolTip

src/mudlet-lua/lua/geyser/GeyserGauge.lua, src/mudlet-lua/lua/geyser/GeyserLabel.lua
Small refactor around how Geyser.Label stores formatting, and some functions to set different aspects of the formatting without having to build and pass in your entire formatting string.
Maintains compatibility with previous functionality by reparsing the entire format if a format string is passed in to echo or setFormat. 
Geyser labels (and by extension Gauges) do not have a convenient way to change the format without having to set the entire thing at once. This changes that.
Started because someone asked me how to set the font size on an anitimer, and I realized there was not a proper method to access that and other formatting options individually.
Adds formatTable property to Geyser.Labels, which contains a key for each viable option in the format string. This property is the one …
=> Extend geyser label formatting

src/dlgProfilePreferences.cpp, src/ui/profile_preferences.ui
Allow setting variable width font from the menu, instead of only via `setFont()` as before.
Font rendering seems to be able to handle weird fonts OK - except when the font is too weird, and then it's on the font.
=> Allow setting variable width font from the menu

src/mudlet-lua/lua/geyser/GeyserLabel.lua
Adds font property to Geyser.Label objects, adds setFont method to change the font for the label. 
Geyser.Label:echo() now reads the font property and adds the appropriate `<font face="font name">` tag for the user.
Came up that Geyser Labels didn't have a method for this as it stands without managing it via CSS. This makes handling fonts in Geyser Labels more like other Geyser objects.
=> Adding font management for geyser labels without needing to use css

src/dlgNotepad.cpp
Fixes buiding when fonts and updater are exclued.
=> Fix missing include for buiding with WITH_FONTS=NO WITH_UPDATER=NO

src/Host.cpp
This small change updates the Console if a command is sent to the Mud (only for macos)
to prevent the flickering caused by QOpenGLWidget
flickering in macos caused by QOpenGlWidget
Please someone with mac os test it.
I could only test it in virtualbox but it seems to fix the issue.
=> Fix for MacOS flickering caused by QOpenGLWidget

src/mudlet.pro
GeyserUserWindow.lua is a new file that was added in the 4.6 release, but it was not mentioned it mudlet.pro among Geyser files, thus _make install_ does not know that it is supposed to install it.
Simple one liner.
(ofcourse I typoed and had to correct it)
=> Add GeyserUserWindow to Mudlet.pro

src/ctelnet.cpp, src/ctelnet.h, src/dlgComposer.cpp, src/dlgComposer.h
* Added closeEvent to Composer window which clears pointer to itself in cTelnet when it gets closed other than using save/cancel button (such as clicking X or right-click and close), so that the parent object will know that it is gone
* Added to cTelnet destructor saying to close Composer window, so that there won't be an orphaned composer window
Allows you to open an editor window again after closing an earlier editor window by clicking the X instead of cancel/save.  Avoids segfault that currently happens if you click cancel on the composer window after closing the profile that it was associated with.
This should solve issue #3300 
In addition to not being able to open a new editor after closing it, there is also problem where if you leave the composer window open and close your profile …
=> Fix problems with Composer window closing

CI/appveyor.functions.ps1, src/mudlet.pro
Update Boost to 1.71 in Windows builds, because that's what is available in the 2019 image we use.
Decrease Windows build times to something more sane.
See https://www.appveyor.com/docs/windows-images-software/#boost for available versions.
=> Update Boost to 1.71 in Windows builds

src/TLuaInterpreter.cpp
The wiki had `tempComplexRegexTrigger("anyText", "^(.*)$", [[echo("Text received!")]], 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)` as an example of a trigger.
Try running it and nothing will work, neither will you get any error messages... :)
So the wiki was wrong and it was really frustrating to use. Turns out because the extra 0's (why were the now extra?) were causing the if to error out. It's pretty easy to add an extra 0 to that train of 0's, so - make it easier for the user and ignore it, instead of ambushing them with a silent error (which should have been a lua_error as it's an API parameter error).
Better user experience.
=> Don't error out if trigger expiration is given as 0
