src/dlgTriggerEditor.cpp

Fix for new issue described here:
https://bugs.launchpad.net/mudlet/+bug/1377401

bug fix for losing old trigger/key/etc content with new item addition

---

src/T2DMap.cpp
src/TArea.cpp
src/TArea.h
src/TLuaInterpreter.cpp
src/TMap.cpp
src/TMap.h
src/TRoom.cpp
src/TRoom.h
src/TRoomDB.cpp
src/dlgRoomExits.cpp

This implements #219 in this branch - had to resolve a merge conflict in the second commit.

(release 30)fix area exits

---

src/TTextEdit.cpp

Fix for:
https://bugs.launchpad.net/mudlet/+bug/1408198

Crash on doubleclicking timestamps

---

src/ui/main_window.ui

Applies #253 to the release_30 branch.

Fixed #1371444, random resizing on OSX

---

mudlet.svg
src/T2DMap.cpp
src/TArea.cpp
src/TArea.h
src/TLuaInterpreter.cpp
src/TMap.cpp
src/TRoom.cpp
src/TRoom.h
src/TRoomDB.cpp
src/TRoomDB.h
src/src.pro

This extends #250 with a few small bug fixes for code that I pushed in Chris's direction.  At the point that this PR was created *that* PR had not been merged into the release_30 branch so at this time it incorporates all of that PR as well but when that PR is merged this should get _much_ smaller :confounded: ?
The combination should be the bare minimum that we need for at least __3.0.0-epsilon__ or did we come to the conclusion that we should publish it as the actual 3.0.0 release and be damned :smiling_imp:  ?
Anyhow, whoever updates the BUILD value in the src.pro qmake project __needs to update the corresponding value in the top level *CMakeLists.txt* file as well as that still says *beta*!__

(release 30 try4 a)exit map fix

---

src/TLuaInterpreter.cpp

When porting the code in Pull Requests #237 and #245 into a different
branch I spotted that TLuaInterpreter::setAreaName() would NOT handle
a new non-ASCII area name.  Also the code to update the area selection
widget in the mapper was being updated BEFORE the new area was added
in TLuaInterpreter::addAreaName() so it was not showing the new area until
another change was made that causes the widget to be updated.
In fixing the new area name handling I have imposed a new check that strips
off leading and trailing spaces from any argument given as a new area name
for both the above functions - this is to avoid breakages that might result
from an area name that is just a load of spaces - which would be confusing
in the area selection widget if permitted (it would be hard to
differentiate …

bugFix: errors in Duplicate Area Issues Fix

---

src/Host.cpp
src/Host.h
src/T2DMap.cpp
src/T2DMap.h
src/TAstar.h
src/TLuaInterpreter.cpp
src/TLuaInterpreter.h
src/TMap.cpp
src/TMap.h
src/TRoom.cpp
src/src.pro

This fixes several things with route finding - including a recently discovered crashing issue with maps with all rooms locked.

Bug fix and enhance problems with route finding

---

src/Host.cpp
src/Host.h
src/T2DMap.cpp
src/T2DMap.h
src/TAstar.h
src/TLuaInterpreter.cpp
src/TLuaInterpreter.h
src/TMap.cpp
src/TMap.h
src/TRoom.cpp
src/src.pro

This implements the same changes to this branch that https://github.com/Mudlet/Mudlet/pull/266 does in the development branch - as such it should fix the recent problems mentioned in bug [1263447](https://bugs.launchpad.net/mudlet/+bug/1263447).
_\*Ahem\*  I perhaps could have worded the title a_ little _better._ :stuck_out_tongue_winking_eye:

(release 30)bug fix and enhance problems with route finding

---

src/Host.cpp
src/T2DMap.cpp
src/T2DMap.h
src/TArea.cpp
src/TArea.h
src/TConsole.cpp
src/TConsole.h
src/TLuaInterpreter.cpp
src/TLuaInterpreter.h
src/TMap.cpp
src/TMap.h
src/TRoom.cpp
src/TRoom.h
src/TRoomDB.cpp
src/TRoomDB.h
src/XMLimport.cpp
src/ctelnet.cpp
src/dlgMapper.cpp
src/dlgMapper.h
src/dlgProfilePreferences.cpp
src/dlgProfilePreferences.h
src/dlgRoomExits.cpp
src/glwidget.cpp
src/glwidget.h
src/mudlet.cpp
src/mudlet.h
src/src.pro
src/ui/profile_preferences.ui

I've finally ported the code across from #301 to the release_30 branch.  I think I got everything cloned (apart from the differences) correctly.  I squashed a couple of bug-fix commits into the prior commits that caused the bugs that they fixed (so this branch has a few less commits in it).  Whilst testing I became aware of a minor cosmetic bug in the form for the map save/load/copy actions which the last commit fixes that was also appended to the 301 branch.
I'd suggest given this one a good going-over/testing to see if there is anything that I haven't caught - with the audit code you may get quite a few (fixed) items when loading in an existing map - hopefully the presented information will be enough to work out what was found and then done to fix it. :grinning:

(release 30)enhancement: move TArea::rooms to QSet (updated)

---

src/TForkedProcess.cpp

Bugfix for spawn() in TForkedProcess.cpp
Same as #322 under the development branch.

(release_30)bugfix for spawn() in TForkedProcess::slotRecievedData()

---

CMakeLists.txt
src/src.pro

Would like to see #326 for release_30 merged first - as soon as that's in, we'll make the epsilon release. Hopefully in the next couple of days.

Update version to epsilon

---

src/TLuaInterpreter.cpp

When I introduced area and map user data storage I also revised the room user data code - specifically `TLuaInterpreter::getRoomUserData(...)` to provide informative error messages on various failures, unintentionally though, this introduced an incompatibility with the documented behaviour for this function in that, as of commit-https://github.com/Mudlet/Mudlet/commit/79a8905c391d33ee3a7756a4b20afbe99cdf75c3 it was expected to return an empty string if the given room id (first argument) number did not exist or the data key (second argument) string was not found for that room.
As it happens the past and current code DOES allow an empty string to be stored against a given key but the past code did not allow the user to differentiate it from the case where the room didn't exist (though that …

compatibilityHack restore empty string response on no room user data

---

CMakeLists.txt
src/src.pro

Fixing a critical bug where Mudlet would crash during creation of a new profile.

Tagging Mudlet 3.0 zeta snapshot

---

src/src.pro

This links the correct libraries for windows, and removes external
links/includes

src.pro corrections for windows

---

src/TLuaInterpreter.cpp
src/TTrigger.cpp
src/mudlet.cpp
src/mudlet.h

Reverts Mudlet/Mudlet#359 - I forgot that there are issues still being mulled over in #358 on the development branch which equally apply here on the release_30 one.
I am not waiting for approval for this PR as it needs to immediately undo changes __I__ introduced into the branch by prematurely merging #359...

Revert "(release_30) sound updates - bugfix and enhance"

---

CMakeLists.txt
src/src.pro

New release primarily to have working SQL in 3.0.0 previews again.

Change version from iota to kappa

---

src/TConsole.cpp
src/TConsole.h
src/TLuaInterpreter.cpp
src/TLuaInterpreter.h

raiseWindow is working fine, but lowerWindow is presently pushing
whatever label/console you use it on below the main console.

Added: raiseWindow/lowerWindow

---

src/mudlet-lua/lua/LuaGlobal.lua
src/mudlet-lua/lua/Other.lua
src/mudlet-lua/lua/geyser/GeyserLabel.lua

Need another sync as a complement to #414. Has a couple of bugfixes that have happened to mudlet-lua since then.

Sync mudlet-lua to 9f9248fdb2900f695cb6df7a99bbcbd2135dab55

---

src/mudlet.cpp

Fixes https://bugs.launchpad.net/mudlet/+bug/1670393.

(release_30) Fix Alias/Trigger/Script/etc button not bringing up script editor again

---

src/mudlet-mapper.xml

Latest from https://github.com/IRE-Mudlet-Mapping/ire-mapping-script/blob/gh-pages/downloads/mudlet-mapper.xml.
Fixes an issue with 'rl' showing 'nil' for areas.

(release_30) Update mapper script

---

src/mudlet-mapper.xml

Latest from https://github.com/IRE-Mudlet-Mapping/ire-mapping-script/blob/gh-pages/downloads/mudlet-mapper.xml.
Fixes an issue with 'rl' showing 'nil' for areas.

(dev) Update mapper script

---

src/TLuaInterpreter.cpp
src/TLuaInterpreter.h
src/mudlet-lua/lua/LuaGlobal.lua

This is a common Pull Request from cherry-picking #429, #421, and #414

(dev) Lua search path adaptions

---

.travis.yml
CI/travis.set-build-info.sh

This is the first step towards https://gitter.im/Mudlet/Mudlet?at=58c7d7567ceae5376ab7f4ab, but I kept the `dev` in the name until we decide what we really want.

(dev) Add short commit SHA1 to version for the build

---

CMakeLists.txt
src/src.pro

Finally! 4 years worth the wait :)

3.0 final!

---

CMakeLists.txt

First baby step to resolving a conflicting file.
1 down, 50 to go!

(the_merge) Resolve conflicts in CMakeLists.txt

---

src/TMap.cpp
src/TMap.h

In a choice between `Host *` and `QPointer<Host>` choose the latter.

Resolve nearly all conflicts in TMap.cpp and TMap.h

---

src/T2DMap.cpp
src/T2DMap.h

Leaving the TEvent stuff until I can find out about which way to go.

Resolve nearly all conflicts in T2DMap.cpp and T2DMap.h [ci skip]

---

src/mudlet.cpp
src/mudlet.h

QString const plus keeping AC's memory leak fixes.

Resolve all conflicts in mudlet.{cpp,h} [ci skip]

---

CMakeLists.txt
src/src.pro

Reverts Mudlet/Mudlet#441
Sorry, I got confused, ``master`` should stay latest release. ``development`` is latest point where we work from - will send a PR to change version there (https://github.com/Mudlet/Mudlet/pull/445)

Revert "Version: advance master to form start point for future work"

---

src/mudlet-lua/genDoc.sh

Resolved all conflicts in genDoc.sh [ci skip]

---

CI/travis.linux.install.sh

Resolved all conflicts in travis.linux.install.sh

---

CI/travis.linux.before_install.sh

Resolved all conflicts in travis.linux.before_install.sh

---

src/TLuaInterpreter.cpp

Not finished resolving everything yet.

Started resolving TLuaInterpreter [WIP] [ci skip]

---

src/ui/main_window.ui
src/ui/profile_preferences.ui

Actually only `main.ui` and `profile_preferences.ui` are affected and it is quite easy to pick out the wanted bits.

Resolve conflicts in all .ui files [ci skip]

---

src/TAlias.cpp
src/TAlias.h
src/TTrigger.cpp
src/Tree.h

Incorporates AC's PCRE memory leak fix of:
https://github.com/Mudlet/Mudlet/commit/fd9fcb9e1738be53a64a2f86375f30eb40e00912
a.k.a. commit-fd9fcb9e1738be53a64a2f86375f30eb40e00912

Resolve c'flicts in TAlias class, Tree.h + one in TTrigger.cpp [ci skip]

---

src/T2DMap.cpp
src/TConsole.cpp
src/TLuaInterpreter.cpp
src/TLuaInterpreter.h
src/TMap.cpp
src/ctelnet.cpp
src/dlgTriggerEditor.h

Fixes up some `TEvent` related conflicts, choosing ones generated locally within a function - AC fix was in: https://github.com/Mudlet/Mudlet/commit/4548001faca2e33d97f29ee11ae18931249f325f
a.k.a. commit-4548001faca2e33d97f29ee11ae18931249f325f
which made the relevant function `Host::raiseEvent(TEvent &)` which thus needs to be supplied with an actual `TEvent` instance rather than a pointer to a `new TEvent` instance.
Also resolves un-TEvent related conflicts in `dlgTriggerEditor.h`, `TMap.cpp`, `TLuaInterpreter.h` to clear those particular files of remaining issues.

Resolve some c'flicts: T2DMap/TMap/cTelnet/dlgTriggerEditor/TLuaInterpreter [ci skip]

---

src/dlgTriggerEditor.cpp

Resolve remaining conflicts in: dlgTriggerEditor [ci skip]

---

src/TLuaInterpreter.cpp

There seemed to be multiple duplicate functions but I think this came about because some of the Room/Area/Map user data functions got put into the file in different locations for the two parents for the merge. (Or because the development version did not have quite the same number of functions as the release_30 branch???)  Generally I have removed the later duplicates.
Also I think the `clearSpecialExits(...)`, `getSpecialExits(...)` and `getSpecialExitsSwap(...)` functions took some damage from a prior incomplete merge conflict resolution attempt, I have repaired them I think.

Resolve remaining conflicts in: TLuaInterpreter.cpp

---

src/TMap.cpp

Fix crash when you copy a map to a profile that doesn't have any yet

---

src/TLuaInterpreter.cpp
src/TRoom.cpp
src/dlgTriggerEditor.cpp
src/ui/aliases_main_area.ui
src/ui/color_trigger.ui
src/ui/profile_preferences.ui
src/ui/triggers_main_area.ui

All usages here are referring to the present, not past tense.
Yeah... I don't know how did this happen.

Fix chose typos

---

src/TMap.cpp

This fixes CID 1415071 and 1415058.

Fix 2 memory leaks when copying a map to another profile

---

src/TArea.cpp
src/TRoomDB.cpp
src/ctelnet.cpp
src/mudlet.cpp

This debug information hasn't been used for years and isn't actively used by anyone right now - if needed, it can be pulled up from Git history again.

Removed some unused debug application output

---

src/dlgTriggerEditor.cpp
src/mudlet.cpp

Ported QSettings fix to release 3.0.1
Tagging @Mudlet/infrastructure for review

Release 30 ported qsettings fix

---

src/T2DMap.cpp
src/TConsole.cpp
src/TEvent.h
src/TLuaInterpreter.cpp
src/TTextEdit.cpp
src/XMLimport.cpp
src/dlgProfilePreferences.cpp
src/dlgTriggerEditor.cpp
src/glwidget.cpp
src/mudlet.cpp

We now enforce 5.6 in build definitions already.

Removed redundant Qt version checks

---

src/Host.cpp
src/T2DMap.cpp
src/dlgRoomExits.cpp

See https://bugreports.qt.io/browse/QTCREATORBUG-12424 for background information.

Fix QStringLiteral("") anti-pattern

---

src/CMakeLists.txt

Don't use QT5_ADD_RESOURCES before finding Qt5.

Fix cmake issue on windows.

---

src/TLuaInterpreter.cpp

BugFix: correct error message from TLuaInterpreter::startLogging(bool)

---

CONTRIBUTING.md

I figure it's best to have this inside contributing guidelines than on our wiki because it'll be closer to the source - when someone wants to contribute, they'll see the guidelines right here and then without having to go on the wiki.
Plus, this'll also enforce team agreement for new guidelines.

Start on coding guidelines

---

src/TLuaInterpreter.cpp

Needed to allow some testing of other work related to I18n.  `feedTriggers` did pass Utf-8 as it used (and still does) `std::string` to convey the data without any conversion - however it needed a bit of an overhaul to conform to the coding styles we now use.
The lua command `echo` is actually mapped to the `TLuaInterpreter::Echo` function and had poor error messages - it also did not pass Utf-8.

I18n: ensure Lua echo and feedTriggers commands pass Utf-8

---

CONTRIBUTING.md

This is based on feedback we have already collected at:
https://github.com/Mudlet/Mudlet/pull/900
http://forums.mudlet.org/viewtopic.php?f=7&t=19499
Just writing down the knowledge gained from those conversations so we don't get into loops about this. Should be pretty straight-forward.

Added internalisation do's and don't

---

src/mudlet.cpp
src/mudlet.h

Added a long-overdue `sysSoundFinished`.
It's a primarily a Lua API thing so tagging @Mudlet/lua-interface for review, but all reviews are always welcome.

Added sysSoundFinished

---

CONTRIBUTING.md

This should be pretty straightforward as I've discussed and reached agreement on this with everybody.
These guidelines apply to core contributors _only_, not interested in raising the bar for new contributors at this point.
Tagging @Mudlet/owners for review.

Added PR merging guidelines

---

src/TCommandLine.cpp

Implementing Stephens review from #966.
@SlySven keep reviews on topic please! Will not be doing this again.

Implementing Stephens comments from #966

---

src/mudlet.cpp
src/mudlet.h

This should address Issue #852

Fix About Dialog opening unlimited instances of itself.

---

src/mudlet.cpp

Fix UserWindows using Main Console border settings.

---

src/TConsole.cpp

Also made the strings translateble.

Fix save profile question to include a question mark

---

CONTRIBUTING.md

I've already updated all of our codebase to be more optimised in https://github.com/Mudlet/Mudlet/issues/1018.

Updated code style - note on .arg chaining

---

src/ui/profile_preferences.ui

You could already do this from the Lua API but not from the settings window.
Fixes https://github.com/Mudlet/Mudlet/issues/527.

Allow negative borders to be set from preferences

---

src/XMLexport.cpp

The Coverity scanner had a bit of a whinge about it
CID 1437885

Add missing return statement

---

src/mudlet-mapper.xml

Updating scripts in preparation for release.
This should really be a submodule I suppose. 
Tagging @Mudlet/lua-interface for review.

Update IRE mapper script to latest

---

src/LuaInterface.cpp
src/T2DMap.cpp
src/TAlias.cpp
src/TBuffer.cpp
src/TCommandLine.cpp
src/TConsole.cpp
src/THighlighter.cpp
src/TLuaInterpreter.cpp
src/TMap.cpp
src/TRoom.cpp
src/TRoomDB.cpp
src/TTrigger.cpp
src/XMLimport.cpp
src/ctelnet.cpp
src/dlgPackageExporter.cpp
src/dlgProfilePreferences.cpp
src/dlgRoomExits.cpp
src/dlgTriggerEditor.cpp
src/mudlet.cpp

Making use of the C++11 raw string literals feature to have more readable code.

Improved code readability by getting rid of quote escaping

---

src/ui/source_editor_area.ui

Before:
After:
@itsTheFae or @SlySven please tick :smile:

Added a frame to edbee so it looks nicer

---

src/dlgTriggerEditor.cpp

Exactly what the title says. Uses OS's default DELETE shortcut.

Added: shortcut for delete action in editor

---

src/TMap.cpp
src/TRoom.cpp
src/TRoomDB.cpp
src/dlgProfilePreferences.cpp
src/mudlet.cpp
src/mudlet.h

43 letter variable names don't sit right with me. Brevity is the soul of wit.

Cut down on the length of some variable names

---

src/dlgProfilePreferences.cpp
src/dlgProfilePreferences.h

That's a 5 year old bug #525 out of the way!
This is targetted for 3.3 so no rush on reviewing...

Fixed "reset map colors" button to work

---

src/mudlet-lua/lua/geyser/GeyserLabel.lua

Fixed typo in GeyserLabel.lua

---

src/Host.cpp
src/TArea.h
src/TMap.cpp
src/TMap.h

See https://github.com/Mudlet/Mudlet/issues/1053 for background & screenshots.

Re-enabled map load on profile load

---

CONTRIBUTING.md

Given feedback that the current guidelines [are confusing](https://github.com/Mudlet/Mudlet/pull/1087#discussion_r122562634), I've attempted to clarify them and provided examples.

Clarified use of QLatin1String

---

src/ui/profile_preferences.ui

Improved layout of IRC preferences

---

src/TLuaInterpreter.cpp

Fix get map events

---

src/dlgTriggerEditor.cpp

I think this is the patch needed for Issue #1157 to be resolved.   I'm starting to nod off so I could be wrong..

Add missing call to set Editor as editable.

---

src/dlgTriggerEditor.cpp

Fixes https://github.com/Mudlet/Mudlet/issues/1113.

Fixed tab indent to be two spaces again

---

src/Host.cpp
src/ui/profile_preferences.ui

Addresses 7 year old wishlist item https://github.com/Mudlet/Mudlet/issues/618.

Fixed blank command separator to not separate as people expect

---

src/mudlet-lua/lua/geyser/GeyserGauge.lua

Haven't done a PR in github in particular in a while, let me know if I'm missing something for this one.

fixes #1210 adding third label to Geyser gauges

---

src/TLuaInterpreter.cpp

See https://forums.mudlet.org/viewtopic.php?f=9&p=43181#p43181 for the bug report.
I tested the solution with [the attached file](https://github.com/Mudlet/Mudlet/files/1154019/11.txt) and `cat ~/Downloads/11.txt | nc -l 8080 &` then connecting to localhost:8080 with mudlet.

Fix multiple MSDP arrays inside an array

---

src/TBuffer.cpp

The `char` type is neither explicitly a signed or an unsigned type which means that bitwise operations on each byte can go wrong unless it is explicitly forced to one or the other.  In some cases modern compilers will spot and warn about this and a couple of cases were detected in prior code.
This commit provides the missing forcing cast (to the Qt `quint8` type) which can be used for the bit-operations needed to process UTF-8 encoded bytes required to remove the warnings and ambiguities that the (Clang) compiler on Travis CI was moaning about.
I have also inserted codes to prevent clang-format from relaying-out the codes where I have to use long, multi-part condition expressions as the layout has been manually tweaked to try and group the terms in a more readable structure which …

Revise: insert some missing casts to handle ambiguous un/signed char types

---

src/ui/about_dialog.ui
src/ui/connection_profiles.ui
src/ui/custom_lines.ui
src/ui/custom_lines_properties.ui
src/ui/room_exits.ui
src/ui/system_message_area.ui

It seems that some forms/dialogues still have references to a file that was renamed a few months back...

BugFix: fix usages of mudlet_alpha.qrc to correct mudlet.qrc

---

src/mudlet.pro

Some of the `LIBS` and `INCLUDEPATH` setting in the QMake project file need to be tweaked to allow building on the FreeBSD OS - fortunately there is a test-variable `freebsd` that is true when `qmake` parses its project files which can be used to detect and allow for that platform.
It is my intention of "porting" Mudlet to FreeBSD and, as Mudlet is a GPLed project it can not be included in the BSD licenced "core" of that OS but should be submitted to https://www.freebsd.org/ports/ for inclusion in the `/usr/ports/` hierarchy of the project (should this be successful then `/usr/ports/games/mudlet/` on any FreeBSD system will contain a platform specific `Makefile` and some other files which means that a system administrator {`root` user} can go to that sub-directory and run the command …

Enhance: enable building on FreeBSD

---

src/HostManager.cpp
src/T2DMap.cpp
src/TRoomDB.cpp
src/ctelnet.cpp

We don't use them = we don't need them. If we need them, it's trivial to put them back.

Cleaned up unused debug messages in last 2+ months

---

src/TAction.h
src/TBuffer.cpp
src/TBuffer.h
src/TCommandLine.cpp
src/THighlighter.cpp
src/THighlighter.h
src/TKey.h
src/TLuaInterpreter.cpp
src/TRoomDB.cpp
src/TTrigger.cpp
src/dlgConnectionProfiles.cpp
src/dlgProfilePreferences.cpp
src/dlgTriggerEditor.cpp

Also added QStringLiteral in places where I saw raw string literals.

(Issue #1054) Replace QRegExp with QRegularExpression

---

src/mudlet-lua/lua/GUIUtils.lua
src/mudlet-lua/tests/GUIUtils.lua

See https://raw.githubusercontent.com/keybase/client/1d41ead7d6b2abc9e5242e94bf54bf7966d91240/packaging/linux/crypto_squirrel.txt on how it uses them

Adds support for [00m which is a valid reset code

---

.appveyor.yml
CODEOWNERS

I added another gitter notification about success or failure of appveyor builds and added the .appveyor.yml to the codeowners

Further improvements to appveyor builds

---

src/TLuaInterpreter.cpp

Fix LUA log error inconsistency in main display

---

src/Host.h
src/TTextEdit.cpp
src/TTextEdit.h
src/XMLexport.cpp
src/XMLimport.cpp
src/dlgProfilePreferences.cpp
src/dlgProfilePreferences.h
src/ui/profile_preferences.ui

Not limited to the error window. Save and load both works but I'm not sure it's done according to the project standard. I tried to mimic as much as I could.
Features Google, Bing and DuckDuckGo.
Issue #1059

Add "search online" right-click option to the console. #1059

---

src/mudlet.cpp

I know not all of them make sense anymore like the IRC one - this PR is just updating the transport system.

Update http URLs to https

---

README.md

https://github.com/Mudlet/Mudlet/issues/1322

Added AppVeyor build status badge in the README.md file.

---

src/XMLimport.cpp
src/dlgTriggerEditor.cpp
src/dlgTriggerEditor.h

I have replaced the ints with an enum class in ` src/dlgTriggerEditor.h` and removed its initializations in the `src/dlgTriggerEditor.cpp` file.

Replace ints for tracking current view with a C++11 class enum

---

.github/PULL_REQUEST_TEMPLATE.md

Learning from the experience at https://github.com/Mudlet/Mudlet/pull/1358, I've modified the PR template with some comment text for the submitter to clarify that small PRs are good, make people happy, and improve the quality of life.
So newcomes don't have to waste their time closing PRs and redoing them again.

Specify one topic per PR in pull request template

---

src/T2DMap.cpp

Fixed a potential memory leak with the action that's created a few lines above at 2635.

Fixed potential memory leak

---

src/mudlet.cpp

BugFix: correct an idiotic error I made in (#1386)

---

.travis.yml

Update Qt PPA in Travis from 5.9.1 to 5.9.3.
This might help us get a more native look in AppImages - see https://github.com/probonopd/linuxdeployqt/commit/e129d347bf0d26ba9fa49d616c9da7ef3ccc41f3

Update PPA to latest Qt 5.9 minor patch

---

CMakeLists.txt
src/mudlet.pro

Use `ccache` if it's available on the users sytem.
Must faster builds when you're switching between branches.
Don't know how to do the qmake equivalent yet.

Use ccache if available

---

src/mudlet.pro

We're using Qt 5.9 in macOS builds and 10.10 is the minimum that's supported.
It might get rid of all those linker warnings we get at the end of the build.
See http://lists.qt-project.org/pipermail/interest/2017-November/028714.html for background.

Up min macOS version to 10.10

---

src/TConsole.cpp
src/TConsole.h
src/TLuaInterpreter.cpp
src/TLuaInterpreter.h
src/mudlet-lua/lua/geyser/GeyserMiniConsole.lua
src/mudlet.cpp
src/mudlet.h

Adds a function to set scroll bars for miniConsoles to visible or invisible (setScrollBarVisible(windowName, bool))
Adds Geyser.MiniConsole method to do the same, as well as the scrollBar key to the :new() function
#1424

Mini console scroll bars

---

src/mudlet.cpp

autoShutDownOnAppExit() is redundant with autoInit, so just use init instead
Fix an outdated comment
Don't repeat edbee 5 times on one line
Better looking code.

Trivial improvements to initedbee

---

.travis.yml
CI/travis.osx.after_success.sh

This adds another command that fixes the stalling signing on macOS Sierra (the current default image)
Make signing work on the latest and greatest.
Fixes #1431

Fix osx signing on sierra

---

src/XMLexport.cpp

Set the device properly so there's somewhere to write. The XML commands to write require the device to be set in order to work.
Fixes the important regression https://github.com/Mudlet/Mudlet/issues/1440 which people have been giving feedback about.

Fix copy/paste regression in 3.6.0

---

src/TRoom.cpp

We're not actively working on the mapper atm and it's kind of spammy. Can always find it in Git or re-add it in 10min if need be.
Clean up stdout

Remove ~TRoom() debugging code

---

src/updater.cpp

Fixed one last case where the automatic update check was missing a complementary development version check.
Fixes https://github.com/Mudlet/Mudlet/issues/1445.

Don't show changelog if running a development version

---

src/dlgConnectionProfiles.cpp
src/mudlet.pro

Set it to focus on the input line in the Delete Profile Dialog.
Fix for #1452

Focus on input for profile delete (#1452)

---

src/LuaInterface.cpp
src/TLuaInterpreter.cpp

Issue#714.
I believe the proper place to do it is the Interface since we are changing a variable set and use by the LUA environment.

Prepend getMudletHomeDir() to package.path and package.cpath #714

---

src/dlgConnectionProfiles.cpp

Allow deletion of default MUDs. I have a feeling this'll be a welcome feature.
It's about time.
They can be re-created if needed by creating a new profile with the same name.

Allow deletion of default MUDs

---

CI/appveyor.after_success.ps1

Squirrel has a bug atm where it scales down the image by 2x - so we give it a 2x bigger image to get a normal one out.
Normal-sized Windows installing icon.

Use a normal-sized image

---

src/TLuaInterpreter.cpp

Fix the check to work right after `lua_remove(L, 1);` was added.
This breaks a lot of GUIs - people are not going to like 3.7.0. Need to get this approved asap.

Fix setLabelCallback to not error when a function has no arguments

---

src/HostManager.cpp
src/T2DMap.h
src/TArea.h
src/TAstar.h
src/TBuffer.cpp
src/TEasyButtonBar.cpp
src/TLuaInterpreter.cpp
src/TMap.cpp
src/TRoom.cpp
src/TToolBar.cpp
src/TTrigger.h
src/TriggerUnit.cpp
src/dlgAboutDialog.cpp
src/dlgConnectionProfiles.cpp
src/dlgProfilePreferences.cpp
src/dlgRoomExits.cpp
src/dlgTriggerEditor.cpp
src/dlgTriggerEditor.h
src/glwidget.cpp
src/main.cpp
src/mudlet.cpp

Just went through the comments and fixed typos. No technical changes done.
Well, less typos, why not

Fix minor typos in comments.

---

src/Host.cpp

Allows installation of packages with non-Latin names.
**Before** PR:
**After** PR:
4.0 goals.

Allow installing packages with non-Latin names

---

src/TLuaInterpreter.cpp

i18n-ised and modernised `installPackage()` and `uninstallPackage()`
i18n
This will need to be tested after https://github.com/Mudlet/Mudlet/pull/1500 is merged as it's not possible to test before.

i18n and modernize installPackage, uninstallPackage

---

src/mudlet-lua/lua/Other.lua

It's very possible that a file might not open as desired.
Better error messages, happier scripters.

Improve table.save in case of saving failure

---

src/mudlet-lua/lua/geyser/GeyserLabel.lua

appears to be a typo / copy-paste error

small fix to label's storing of its message

---

.github/ISSUE_TEMPLATE.md

Small tweak to issues template - we don't use svn to have 'revisions' and branches get comments in their respective PRs.
A bit more relatable issue template

Take out unrelated references

---

src/TMap.cpp

Fixed a typo in a user-facing message.
Typos are unprofessional.

Fix typo in 'map too new' error message

---

CI/travis.linux.after_success.sh
src/TLuaInterpreter.cpp

Copy Linux formatter into the binary.
Fix https://github.com/Mudlet/Mudlet/issues/1498

Copy Linux formatter into official binary

---

src/dlgTriggerEditor.cpp
src/dlgTriggerEditor.h
src/dlgVarsMainArea.cpp

Fix booleans getting converted into strings when viewed in the variables view.
Fix https://github.com/Mudlet/Mudlet/issues/1590

Fix booleans turning into strings

---

src/send-text-to-all-games.xml

Allow `:` to run aliases as well.
Remove arbitrary limitation that you can't run aliases with it too.

Tweak : to use expandAlias

---

.travis.yml

Don't hardcode two cores, instead use the available ones reported by the system (currently still 2).
In case we update Travis images and the number of cores changes, we won't have the possibility of forgetting to manually up the used core count.

Future-proof parallization of Mudlet build on Travis

---

src/mudlet-lua/lua/Other.lua

Added creplaceLine function
replaces line from MUD with colour-tagged string
I use it all the time, just a little shorthand QoL function

creplaceLine function

---

CI/appveyor.install.ps1
CI/copy-non-qt-win-dependencies.ps1
src/mudlet.pro

This updates the Windows dependencies for Mudlet to the currently latest version.
Let's stay up-to-date to avoid bugs and security issues.

Update windows dependencies

---

.travis.yml

- This PR is for tests about the stalling travis macOS builds.
- Hopefully, we find and commit a fix with this PR.
Fix our infrastructure.

Tests and hopefully fix for stalling CI builds

---

src/T2DMap.cpp

Fix not member not initialised in constructor error
Fix coverity 1415094

Fix not member not initialised in constructor error

---

src/mudlet.pro
src/updater.cpp
src/updater.h

Show changelog for the versions we upgrade from.
Fix https://github.com/Mudlet/Mudlet/issues/1514

Fix blank changelog on upgrade

---

src/AliasUnit.cpp
src/AliasUnit.h
src/T2DMap.cpp
src/TAlias.cpp
src/TLabel.cpp
src/ctelnet.cpp
src/dlgAboutDialog.cpp
src/dlgColorTrigger.cpp
src/dlgComposer.cpp
src/dlgComposer.h
src/dlgConnectionProfiles.cpp
src/dlgConnectionProfiles.h
src/dlgMapper.cpp
src/dlgScriptsMainArea.cpp
src/dlgSourceEditorArea.cpp
src/dlgTimersMainArea.cpp
src/main.cpp
src/ui/composer.ui

Went through a few files and fixed up a few clazy warnings.
Biggest ones were:
1. https://github.com/KDE/clazy/blob/master/src/checks/level2/README-qstring-allocations.md
1. https://github.com/KDE/clazy/blob/master/src/checks/level2/README-old-style-connect.md
I haven't fixed them everywhere though, it's too much.
More efficient Mudlet!
Should be no functional changes whatsoever.

Fixed up a few clazy warnings

---

src/XMLexport.h

Removed a few redundant header includes left over from https://github.com/Mudlet/Mudlet/pull/1629.
Less cruft.

Remove redundant xmlexport includes

---

src/TLuaInterpreter.cpp

Removed debug echo left in downloadFile.
It gets really spammy when you use `downloadFile()` a lot!

Removed debug echo left in downloadFile

---

src/TLuaInterpreter.cpp
src/mudlet-lua/lua/geyser/GeyserMiniConsole.lua
src/mudlet.cpp
src/mudlet.h

Improved calcFontSize to take a window parameter as well since miniconsoles can have custom fonts now and added a corresponding Geyser function.
Fix https://github.com/Mudlet/Mudlet/issues/1697.

Improved calcFontSize to take a window parameter as well

---

translations/mudlet.ts

Added a translation file. Once it's merged, I'll update crowdin to point to `development` branch to start translation.
4.0 goals!
Generated with lupdate -recursive ./src/ -ts ./translations/mudlet_en_US.ts
It would be nice for Travis' builds of `development` branch in the Mudlet repo to just force-update it with new strings when PRs are merged.

Added translations file for crowdin to translate

---

src/mudlet.pro

WITH_UPDATER and WITH_FONTS are not actually case-insensitive, see: https://paste.ubuntu.com/p/svkjk3ySYz
I don't want to wrack my brain figuring out that scripting language so I've just updated the instructions. Other packagers have already figured this out (ie [Arch](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mudlet#n30)).
Correct instructions

Fix WITH_UPDATER, WITH_FONTS instructions

---

.github/CODEOWNERS

Updated codeowners file to add the new UI review team
Automatic review tagging

Update Codeowners for UI review team

---

.github/CONTRIBUTING.md

Allow blanket approval of translation PRs - content should be approved in crowdin instead.
Smoother translation workflow

Update contribution guidelines for translation PRs

---

src/Host.cpp
src/TLuaInterpreter.cpp
src/dlgTriggerEditor.cpp
src/updater.cpp

Add context to singleShot timers lacking one.
Less possibility of a crash.

Added context to singleShot timers

---

CI/travis.osx.install.sh

Should fix the arugmenterror string we're getting in https://api.travis-ci.org/v3/job/391094292/log.txt due to https://github.com/CocoaPods/CocoaPods/issues/7765
Fix macOS updater https://github.com/Mudlet/Mudlet/issues/1766

Update cocoapods to latest

---

src/TLuaInterpreter.cpp

Only compute .size() once per for loop instead of every iteration
Better tools showed an opportunity for quicker code

Optimise for loops in GMCP/MSDP code

---

src/ctelnet.cpp

Remove commented-out code as suggested in PR #1750.

Remove commented-out code.

---

src/TLuaInterpreter.cpp
src/TLuaInterpreter.h

Added getGridMode()
Close https://github.com/Mudlet/Mudlet/issues/494
I had spare time on the plane flight.

Added getGridMode()

---

.appveyor.yml
CI/appveyor.after_success.ps1

This adds code signing to the creation of releases with Squirrel.
Hopefully avoid getting flagged as viruses et al. by anti virus programs.

Add windows code signing

---

src/TBuffer.cpp
src/TBuffer.h

Added a response to MXP `<SUPPORT>` query.
Fix ancient bug https://github.com/Mudlet/Mudlet/issues/475.
I aimed for code readability, let me know what you think about that.
Flights are conductive to concentration.

Add mxp supports response

---

src/Host.cpp
src/Host.h
src/dlgConnectionProfiles.cpp
src/dlgTriggerEditor.cpp
src/dlgTriggerEditor.h

Added profile autosave to Mudlet.
People's computers can crash, lose power, or people can crash Mudlet with infite loops - all of which result in a loss of work and frustration. Prevent this by making their stuff just "not get lost" :)
Fixes https://github.com/Mudlet/Mudlet/issues/1759, fixes https://github.com/Mudlet/Mudlet/issues/734.

Add profile autosave

---

src/TLuaInterpreter.cpp

Fixed a few function's poor error messages.
Better error messages!
It's not all of them by far, but it's a start. Had time on the plane flight.

Fixed up a few error messages and poor variable names

---

src/Host.cpp
src/TBuffer.cpp
src/TBuffer.h
src/ctelnet.cpp
src/dlgProfilePreferences.cpp

This is a re-submit of the big5 encoding support pull request, with a more descriptive branch name.

Big5 support

---

src/TBuffer.cpp

Actually iterate the when a blank MXP SUPPORTS is requested.
Fix a major issue affecting a lot of players.

Fix crash with MXP in 3.11

---

src/ActionUnit.cpp
src/XMLexport.cpp

Delete old Qt version checks in code
Less cruft.
Not needed with Qt 5.7 minimum.

Delete old Qt version checks in code

---

src/T2DMap.cpp

Tag the text the user sees when creating a new label visually in the mapper for i18n.
i18n so Crowdin can see the text.
Salvaged work from https://github.com/Mudlet/Mudlet/pull/1334.

i18n-ise GUI label creation

---

src/Host.cpp
src/XMLexport.cpp
src/XMLexport.h
src/dlgPackageExporter.cpp

Added a syncronous method for it to use
Fix package exporter to work
Fix https://github.com/Mudlet/Mudlet/issues/1790.
Added a syncronous method for it to use, like it did previously.

Fix package exporter to work with async save

---

.travis.yml
CI/travis.linux.after_success.sh

This will create and upload release tarballs after generating the generic Linux AppImage.
Less manual maintenance burden when creating a new release.
Closes #1827

Upload release tarballs

---

src/dlgProfilePreferences.cpp
src/ui/profile_preferences.ui

Change the user-visible URL to the new one since the project changed it.
No dead page shown to users if they manually follow the link.
Actual theme downloading was always done from Github and never affected.

Update URL shown to the new one

---

src/TLuaInterpreter.cpp

* publish ttsGetState() to userspace
* link to documentation in wiki, instead of having inline comments before function definition in code

Give users ttsGetState() & wiki documentation

---

.travis.yml
CMakeLists.txt
src/CMakeLists.txt
src/HostManager.cpp
src/HostManager.h
src/TLuaInterpreter.cpp
src/TLuaInterpreter.h
src/mudlet-lua/lua/LuaGlobal.lua
src/mudlet-lua/lua/TTSValues.lua
src/mudlet.pro

Revert recent TTS additions until we can fix the discovered issues.
There are a lot of issues with it, see https://github.com/Mudlet/Mudlet/issues/1881.
We'll concentrate on fixing the issues and getting the features back in for the next release.

Revert TTS

---

translations/mudlet.ts

Updated input translation strings for Crowdin to see.
So people can translate on the latest content.
```
Updating 'translations/mudlet.ts'...
Found 1377 source text(s) (9 new and 1368 already existing)
Kept 4 obsolete entries```

Updated input strings for translation

---

src/LuaInterface.cpp
src/TTabBar.cpp
src/TTrigger.cpp
src/XMLexport.cpp
src/dlgTriggerEditor.cpp

No functional changes to code, just modernize it for with modern C++ for readability.
Better readability.

Modernize code (range loops, old headers)

---

src/ui/composer.ui

Simplify HTML for the Composer window's `Save` button tooltip.
Easier time for translators.

Simplify HTML in the composer save button tooltip

---

src/TLuaInterpreter.cpp

Fix the room not found message.
Consistent and clear error messages.
Found some incorrect use in getRoomName() as well.

Fix error message for room not found

---

CI/travis.linux.after_success.sh

This will fix the automated upload of release tarballs
Let's fix this step once and for all! (Less manual chores)
Closes #1891

Fix upload of release tarballs

---

src/dlgPackageExporter.cpp
src/dlgPackageExporter.h
src/ui/dlgPackageExporter.ui

Show a link to https://forums.mudlet.org/posting.php?mode=post&f=6 upon creating a package.
More packages in Mudlet forums.

Add a small nudge to upload exported package to Mudlet forums

---

src/TTrigger.cpp

Highlight i18n text using the "highlight" checkbox properly.
Before:
After:
Better i18n support.

Highlight i18n text using the "highlight" checkbox properly

---

src/Host.cpp
src/Host.h

Fix module sync between active profiles to work again - by syncing the modules after the asynchronous save has completed.
Fix https://github.com/Mudlet/Mudlet/issues/1799

Fix module sync

---

src/TLuaInterpreter.cpp

Fix selectSection not accepting main and returning wrong value, as well as bring the error messages up to modern standards for Mudlet.
Better user experience
Fix #1999

Fix selectSection not accepting main and returning wrong value

---

translations/mudlet.ts

Updated input translation strings for Crowdin to see.
So people can translate on the latest content.
see #1900 for comparison

Update strings for translation

---

src/T2DMap.cpp
src/T2DMap.h

Adds a right-click option to create a new room.
More visual map editing.
How it works:

Add feature: visual room creation

---

src/main.cpp

Print debug information to console just like mac and Linux do by default.
Easier debugging on Windows for the once-off things.

Print to stdout running from console in Windows too

---

translations/mudlet.ts

Latest strings for translation

---

src/mudlet-lua/lua/GUIUtils.lua

Fixed the suffix function so it will now always write at the end of the line, will properly write to windows other than the main window, will apply foreground and background colors, and use alterative functions. For consistency with prefix, echo-type functions are replaced with insertText-type functions.
Suffix function wasn't always writing at the end of the line, and upon inspection also wasn't using alternative functions or windows properly.

Update GUIUtils.lua to fix suffix function

---

src/mudlet-lua/lua/GUIUtils.lua

Fixed prefix function to work properly with designated writing functions, foreground and background colors, and windows. Written assuming certain functions will be fixed to allow "main" window arguments (insertText and getLineNumber).

Update GUIUtils.lua to fix prefix function

---

src/mudlet-lua/lua/GUIUtils.lua

Added a "sort" boolean option to showColors, which will sort the colors that are displayed, rather than showing them in a random order. Also changed the way arguments are handled so that they can be given in any order. Default behavior remains unchanged, and is equivalent to showColors(4, "", false)
I didn't like the order the colors were displayed in, and wanted a way to sort them.

Updated showColors function in GUIUtils.lua

---

src/mudlet-lua/lua/geyser/GeyserLabel.lua

Fixed Geyser Label <center> closing tag

---

src/mudlet-mapper.xml

Update the default IRE mapper to the latest version.
So users don't have to upgrade right away when creating a new profile.

Update default IRE mapper to latest version

---

src/mudlet.cpp
translations/translated/qm.qrc

Add Portuguese as an available interface language.
It's getting translated on Crowdin.

Added Portuguese as an interface language

---

src/mudlet-lua/lua/DebugTools.lua

Changed display function to accept and handle multiple arguments.
Issue #1996

Update DebugTools.lua to improve display function

---

translations/mudlet.ts

Update translation strings for the 3.15 release.

Update translation strings

---

src/TConsole.cpp

Add translation for "no search results"
Remove translation for debug messages as required in #2010

Adjust translations in TConsole

---

src/TLuaInterpreter.cpp
src/mudlet.cpp
src/mudlet.h

Fix insertText to recognize "main" argument and bring it up to modern error message standards.
More consistency with other UI functions.
Fix https://github.com/Mudlet/Mudlet/issues/2043.

Fix insertText to recognize "main" argument

---

src/T2DMap.cpp

Add missing strings for translation
Adjust capitalisation in right-click menu
Standardize texts to recycle translations

Add missing strings for translation --> T2DMap

---

src/ctelnet.cpp

Quote the value reporting Mudlets version properly in GMCP's `Core.Hello` message.
Send valid JSON.

Quote Mudlet version properly in GMCP Core.Hello

---

src/T2DMap.cpp
src/glwidget.cpp

Xterm256 support for map colors

---

src/send-text-to-all-games.xml

Remember matches[2] in send-text-to-all-profiles
repair using this for aliases
fix #2158

Repair to also send aliases

---

COMMITMENT

Add a `COMMITMENT` file to backport the GPL v3 re-instatement clause to our GPLv2+ license.
https://blog.github.com/2018-11-07-github-joins-GPL-Cooperation-Commitment. Seems okay?

Add COMMITMENT

---

src/dlgProfilePreferences.cpp

Remove unused variable and a bad check.

Fix Coverity SSL warning

---

src/mudlet-lua/lua/geyser/GeyserLabel.lua

Added functions to implement enableClickthrough and disableClickthrough functions for Geyser managed labels.

Add support for enable and disableClickthrough

---

src/mudlet-lua/lua/geyser/GeyserGauge.lua

Added functions to simplify use of enableClickthrough and disableClickthrough functions with Geyser managed gauges.

Added clickthrough support to Geyser gauges

---

src/TMap.cpp
src/dlgProfilePreferences.cpp

Fix https://github.com/Mudlet/Mudlet/issues/2186
Better code!

Fix saving to use version number correctly in 'development'

---

src/dlgConnectionProfiles.cpp
src/dlgProfilePreferences.cpp
src/dlgTriggerEditor.cpp
src/ui/lacking_mapper_script.ui
src/ui/profile_preferences.ui
src/ui/room_exits.ui

Finally got around to visiting CrowdIn and pulled out some source code fixes to go into the mix.

Translations: fixup some details reported by translators.

---

src/ctelnet.cpp

This closes https://github.com/Mudlet/Mudlet/issues/2249 .

BugFix: reset Game Server Echoing flag on disconnect/reconnect

---

src/ctelnet.cpp

Improve some issues found during translation
Decrease burden of l10n

Refactor almost duplicate error message

---

src/mudlet-lua/lua/generic-mapper/generic_mapper.xml

Add a new ignore line from Fierymud.
Better room tracking.

Add new ignore line for generic mapper

---

src/TLuaInterpreter.cpp

Actually fix `echoLink()` to accept `"main"` as an argument.
Generic mapper's help doesn't work right without it.
Fix https://github.com/Mudlet/Mudlet/issues/2270.

Fix echolink main

---

src/ctelnet.cpp

Fix Discord to be processed from GMCP properly.
Discord Rich Presence is not working at all since November.
Broken by subtle changes in mega-PR #1852.
Thanks to the report on Discord about this.

Fix GMCP Discord rich presence

---

src/HostManager.cpp
src/HostManager.h
src/ScriptUnit.cpp
src/ScriptUnit.h
src/TBuffer.cpp
src/TBuffer.h
src/TTrigger.cpp
src/TTrigger.h
src/TVar.cpp
src/TVar.h
src/TimerUnit.cpp
src/TimerUnit.h
src/TriggerUnit.cpp
src/TriggerUnit.h
src/VarUnit.cpp
src/VarUnit.h
src/dlgConnectionProfiles.cpp
src/dlgConnectionProfiles.h
src/dlgTriggerEditor.cpp
src/dlgTriggerEditor.h

Turn read-only arguments into const references.
Less potential copies, slightly quicker Mudlet.

Make read-only arguments const references

---

src/Host.cpp
src/HostManager.cpp
src/T2DMap.cpp
src/dlgIRC.cpp
src/dlgPackageExporter.cpp
src/dlgProfilePreferences.cpp
src/dlgTriggerEditor.cpp

Fix potential sources of Qt container detachment with `qAsConst()` which we can safely use in 5.7+.
Possibly faster Mudlet.

Fix potential sources of Qt container detachment

---

src/mudlet.pro

`_PRO_FILE_PWD_` means the "current project file being parsed" - which may or may not be `mudlet.pro`, it won't be if `mudlet.pro` is included in another project.
`PWD` on the other hand always points to `mudlet.pro`
Easier setup for fuzzing.

Use correct variable for relative paths in mudlet.pro

---

src/mudlet.cpp

Remove a debug echo that was accidentally left in.
Less crap show in console!

Remove stray debug echo for language maps

---

src/TLuaInterpreter.cpp

Improve error messages for `appendCmdLine()`, `getTime()`, `installModule()`, `reloadModule()`, `registerAnonymousEventHandler()`, and `printCmdLine()`.
More clarity for scripters in case they do things wrong.

Improve error msgs for Lua functions

---

src/XMLexport.cpp

From looking at the code, it does not actually seem to affect anything.
Less strange code!
Reported by Coverity.

Fix copy/paste error relating to ignored background colour codes

---

src/TBuffer.cpp

Does not seem to have any effect because the variable is always set to `true` upon initialisation.
Less code!
Thanks to Coverity for reporting it.

Remove dead code for html copy starting in the middle of the line

---

src/ctelnet.cpp

Don't lose text in games that don't enable GA right away when reconnecting to the game.
Better handling of GA.
Fix https://github.com/Mudlet/Mudlet/issues/2286.

Don't lose text in games that don't enable GA asap when reconnecting

---

src/TLuaInterpreter.cpp
src/TTrigger.cpp

No practical changes, just improved and modernised code.

Minor string improvements

---

src/TBuffer.cpp

A recent PR: https://github.com/Mudlet/Mudlet/pull/2365 removed code which was rendered ineffective by an implementation error in: https://github.com/Mudlet/Mudlet/pull/984 however the latter caused an error which has just been raised in: https://github.com/Mudlet/Mudlet/issues/2367
This PR should fix the issue and it also fixes another bug that I can see in that underlines are not being reproduced in the HTML files because of a typo in that part of the style detail for `<span ...>` entries which used "text-decoration: undeline" instead of: "text-decoration: underline"!

BugFix: add missing "</span>" in timestamped copy-to-HTML & log files

---

CI/copy-non-qt-win-dependencies.ps1

Ship the required `.aff` file as well as the `.dic` for Windows dictionary.
Working US English dictionary in Mudlet again.
Fix https://github.com/Mudlet/Mudlet/issues/2398.

Fix US dictionary to show up on Windows

---

src/dlgConnectionProfiles.cpp

Improve profile connection message

---

src/TRoomDB.cpp
src/TRoomDB.h

Speed up getRoom() a little bit.
Slightly faster `getRoom()` which is nice since it's used often.

Speed up getRoom() a bit

---

CI/travis.linux.after_success.sh

Deploy non-zipped version of the AppImage so https://github.com/AppImage/appimage.github.io/ can work with it.
Listing on https://appimage.github.io.
Fix https://github.com/Mudlet/Mudlet/issues/2340.

Deploy unzipped AppImage alongside zipped

---

src/mudlet.cpp
src/mudlet.h

Change a player-visible message right on the screen for what really should be a debug message.
4.0 goals.
Fix #1 of https://github.com/Mudlet/Mudlet/issues/855#issuecomment-451127378.

Fixed raw postMessage

---

translations/mudlet.ts

Updated input translation strings for Crowdin to see.
So people can translate on the latest content.
see #1900 for comparison

Update texts for 3.18 translation

---

src/TLuaInterpreter.cpp
src/TTrigger.cpp

Fix cases where the main window might not exist but triggers are somehow firing (?). Good not to crash anyway.
Less Coverity complaints.

Fix potential issues with the main window not existing

---

src/mudlet.cpp

Fix 'Eypt' typo

---

src/mudlet.cpp

Canadia sounds cool, but it's not a thing.
Less typos.

Fix 'Canadia' typo

---

src/dlgTriggerEditor.cpp

Fix 'to chose' typos
Less typos.

Fix 'to chose' typos

---

src/T2DMap.cpp

Small typo fix.
Less typos.
Noticed during translation.

Typo fix in multi room selection tooltip

---

src/ui/actions_main_area.ui

Shortened text for creating buttons
Easier to read and translate

Shortened text for creating buttons

---

src/ui/keybindings_main_area.ui

Shorten text for keybindings
Easier comprehension for users and translators
Same as https://github.com/Mudlet/Mudlet/pull/2433

Shorten text for keybindings

---

src/TLuaInterpreter.cpp

My attempt at internatiolising the logError function.
4.0 goals.
See #2 in https://github.com/Mudlet/Mudlet/issues/855#issuecomment-451127378.

i18n TLuaInterpreter::logError

---

src/mudlet-lua/lua/GUIUtils.lua

This change adds dreplace(window, text) in the vein of creplace, but to be used with RGB format (<FR,FG,FB:FR,FG:,FB>)
More consistency and ease-of-use for the future

Update to add dreplace(window, text)

---

src/XMLimport.cpp

Remove unnecessary parenthesis in XMLImport
Less parenthesis and less PVS-Studio warnings!

Remove unnecessary parenthesis in XMLImport

---

src/dlgAboutDialog.cpp

Fix an unclosed html header tag in About dialog
Less bad HTML.

Fix an unclosed html header tag in About dialog

---

src/TToolBar.cpp

Check that we have a button before moving it
Less possibilities of a crash.
The null check was too far down.

Check that we have a button before moving it

---

src/TMatchState.h

Add mSpacer to copy constructor of TMatchState
Less possibility of bugs!

Add mSpacer to copy constructor of TMatchState

---

src/TMap.cpp

It `id` will never be less than zero, all we're really wanting is just an infinite loop.
Better code readability.

Improve logic loop readability

---

src/T2DMap.cpp

Add a strategic comma character
Must not confuse users & translators
Fix #2482

Seperate comment from string displayed

---

translations/mudlet.ts
translations/translated/mudlet_en_US.ts

Update translations for new version
Let the translations begin!
We need to automate this :)

New texts for version 3.19

---

src/TRoomDB.cpp

Fix 'then' grammar typo.
Better English.

Fix 'then' grammar typo

---

src/ui/main_window.ui

Simplify notepad tooltip. 'the active profile' raises a question 'which is the active profile?' whereas 'this profile' is dead simple.
Less possibility of people getting confused.

Simplify notepad tooltip

---

src/ui/main_window.ui

Simplify manual tooltip.
I feel that it the current form is pedantic :confused:

Simplify manual tooltip

---

src/dlgProfilePreferences.cpp

Remove strange `if` clause.
Possible bug removed?

Fix logic error(?) in map copy

---

src/T2DMap.cpp

It turns out that the area that had to be (double-) clicked on a room to initiate a speed-walk on the 2D mapper was incorrectly calculated. It was centred on the values returned by `QRectF::x()` and `QRectF::y()` which are actually the top-left (or maybe bottom - I think y values are inverted in the 2D mapper) corner and **not** the middle of the room!
Whilst debugging this I made an interesting discovery in that double-clicking in the area of the coloured arrow that is drawn for an area exit off to one side of a room with an XY-plane exit to another area will do a speed-walk to the room in the other area...
... I also found that a chunk of code that would have implemented this for the case when grid mode was selected - was totally pointless - as it requires the `(QMap<int, QPoint> …

BugFix: target room selection for speed-walking was inaccurate

---

src/dlgTriggerEditor.cpp

Fix a run-on sentence for editor search box option
Better English and more chances of a correct translation.

Fix a run-on sentence for editor search box option

---

src/dlgConnectionProfiles.cpp

Update visible Clessidra URL in connection profiles window
Per game admin request

Update visible Clessidra URL in connection profiles window

---

src/mudlet.pro

The system maintainers have recently updated the Hunspell libraries to 1.7

Update: revision of Hunspell dictionary

---

CMakeLists.txt
src/mudlet.pro

Actually set Mudlet 3.19 dev
Release process.
Release process is way too manual and tedious. Great when I have 6 hours and tons of motivation to do it, not so great when I don't and forget things!

Actually set Mudlet 3.19 dev

---

src/mudlet.cpp
translations/mudlet.ts
translations/translated/mudlet_en_US.ts

Update translations for new version
Let the translations begin!
We need to automate this :)

New texts for version 3.20

---

.travis.yml

Update Linux image to Ubuntu 16.06 LTS
Trusty no longer works in CI.

Update Linux image to Ubuntu 16.06 LTS

---

src/mudlet.cpp

Names of languages will not be translated anymore themselves 
Making it easier for natives to always find their home language
Fix #2526

Show languages' names in their native

---

src/TLuaInterpreter.cpp

Repair link to wiki
Find corrent documentation
Wiki documentation should be written in same PR when adding functionality
Fix #2532

Link to getTextFormat in wiki

---

translations/mudlet.ts

Qt 5.12.2 found more texts :)
Last commit omitted some texts.
Follow up upon #2529, fix #2531

More texts for 3.20

---

src/ui/profile_preferences.ui

Change bit.ly link and use mudlet.org instead
Reduce 3rd party dependencies
Fix #2522

Update URL for translation introduction

---

.travis.yml
CI/travis.linux.install.sh

Theis PR upgrades the Linux Qt version to 5.12.3. Additionally, some other cleanups and speedups are done.
More up to date dependencies and cleaner setup.

Qt 5.12 upgrade and other CI cleanup

---

src/mudlet-lua/lua/GUIUtils.lua

Add in error checking (text == 'string') to produce a more readable error message for users
Upon accidentally supplying a table, ate an error message I was not immediately familiar with

Add in error checking for ansi2decho

---

src/TBuffer.cpp
src/TBuffer.h

Increase max links to 2000
Someone actually ran into the limit and noticed it being a problem (https://github.com/Mudlet/Mudlet/issues/2535).
Still keep a limit for performance reasons

Increase max links to 2000

---

src/TArea.cpp
src/TArea.h
src/TMap.cpp
src/glwidget.cpp

Translated some variable names to English. Specifically Ebene was used
for the zLevel in map in a number of places.
Most of the source is in English, this makes it more uniform.

Translated some variable names to English.

---

src/T2DMap.cpp

Ensure mMaxRoomIdDigits is initialised in constructor
Less Coverity warnings.

Ensure mMaxRoomIdDigits is initialised in constructor

---

src/TBuffer.cpp

Only validate encoding tables for every language in debug builds, not release builds. It's really unnecessary to validate them every time copy() is used or a new console is created. Should be done once at build time, but I'm not familiar enough with `constexpr` to make that happen.
Faster Mudlet!

Optimise copy() and creation of new miniconsoles/userwindows

---

src/dlgConnectionProfiles.cpp
src/dlgConnectionProfiles.h

Fix broken Connect after offline mode introduction

---

src/dlgConnectionProfiles.cpp

Fix icon duplication and inconsistency in the welcome dialog
Before:
After:
See https://github.com/Mudlet/Mudlet/pull/2580/files#r289136909

Fix icon duplication and inconsistency in the welcome dialog

---

translations/mudlet.ts
translations/translated/mudlet_en_US.ts

Update translations for new version
Let the translations begin!
We need to automate this :)

Update texts for 3.21

---

src/TConsole.cpp

Combine two half sentences into one joint.
Help translators with whole sentences.
Noted during translation at https://crowdin.com/translate/mudlet/137/en-de#79920

Align texts for start & end of log files

---

src/TMap.cpp

Remove "loaded/imported/downloaded" details and straighten grammar.
Improve readability
Found during translation here https://crowdin.com/translate/mudlet/137/en-de#79945

Trim message when audit starts

---

src/TMap.cpp

Simple typo fixed in text shown to users
Happy users
Noted during translation here: https://crowdin.com/translate/mudlet/137/en-de#79972

Fix typo it's -> its

---

src/TMap.cpp

No changes to users. Added comments for translators.
There was confusion in Crowdin, how these texts apply.
Thanks to italian translator turin for suggesting these!

Add comments to translation

---

src/TMap.cpp

Remove string ", " from translation.
YAGNI. All languages translated it unchanged. 
Noted during translation here: https://crowdin.com/translate/mudlet/137/en-de#79969

Make list seperator locale independent

---

src/main.cpp

Remove dot from URL. Add translation comments. Outsource whitespace.
Make translation easier. Make URLs unambiguous.
Noted during translation & during creation of this PR, yeah, I made one with creeping scope as well! :)

Remove whitespaces & update translations

---

src/ui/triggers_main_area.ui

Increase allowed 'maximum number of lines' for trigger patterns.
The UI can show more than 2 digits max now, so increase it. Discord has been talking about it lately.

Increase allowed 'maximum number of lines' for trigger patterns

---

translations/mudlet.ts
translations/translated/mudlet_en_US.ts

Update translations for new version
Let the translations begin!
We need to automate this :)

Update texts for 3.21 release

---

src/dlgTriggerEditor.cpp

New triggers were called "New trigger" in each language until now
i18n
Same for trigger groups

triggereditor - translate name of new triggers

---

src/TTrigger.cpp

Make trigger error message translateable
Remove English text in translated versions

translate "No patterns defined"

---

src/dlgTriggerEditor.cpp

More names like "New alias", etc. will be translateable
Continuing the spirit of #2632
Also tackled `random capitalisation syndrome`

Translate more new items' names

---

src/TVar.cpp

Remove qSort deprecation comment
It adds no value whatsoever. Comments should explain the 'why?' question, and one won't really ask it here.

Remove deprecation comment

---

src/ctelnet.cpp

Make error message translateable.
Connect to any game. Press Alt+R for reconnect. See error message in English.

Translate "Socket disconnected" error message

---

src/ui/triggers_main_area.ui

Switch "Background" and "Foreground" texts.
They were indicating the wrong thing.
Fix #2648

Fix labels on color buttons

---

src/ui/trigger_editor.ui

Trying to reduce minimum width of tree-widget.
Too much wasted whitespace possible.
This will try to fix #2652

Shrink tree-view in editor window

---

src/ui/triggers_main_area.ui

Fix typo in fire length delta
Less typos + hopefully clearer text.

Fix typo in fire length delta

---

translations/mudlet.ts
translations/translated/mudlet_en_US.ts

Update *.ts again
Many PR updated texts, bring them to Crowdin
How can we automate this?

New texts for translation

---

src/mudlet-lua/tests/DB_spec.lua
src/mudlet-lua/tests/GUIUtils_spec.lua
src/mudlet-lua/tests/Other_spec.lua
src/mudlet.pro

Fix existing tests

---

src/ctelnet.cpp

Just one whitespace removed
Combine almost similar messages on Crowdin
Created these myself with last PR

Fix typo in socket disconnect message

---

src/dlgPackageExporter.cpp

Just a few updates and omissions in the messages and comments
Make texts more concise and easy to grasp for users and translators
See discussion in #2554 which was merged to gain functionality early
edit: Also update URL to fix #2561

Rephrase package exporter

---

src/dlgPackageExporter.cpp
src/dlgPackageExporter.h

Add link to folder in which the package was exported to
Fix #2563

Add link to package folder

---

CMakeLists.txt
src/ActionUnit.cpp
src/EAction.cpp
src/HostManager.h
src/TAstar.h
src/TCommandLine.h
src/TConsole.h
src/TEvent.h
src/TLuaInterpreter.cpp
src/TLuaInterpreter.h
src/TMap.cpp
src/TRoomDB.h
src/TToolBar.cpp
src/XMLexport.cpp
src/XMLexport.h
src/XMLimport.cpp
src/ctelnet.cpp
src/discord.cpp
src/dlgTriggerEditor.h
src/mudlet.h
src/widechar_width.h

Remove unused header includes
Faster compiles
Done with https://blog.jetbrains.com/clion/2019/06/clion-2019-2-eap-msvc-debugger-unused-includes-check-and-more

Remove unused header includes

---

src/ui/profile_preferences.ui

Update tooltip, more than IRE now provide maps
More than IRE games support MMP map download via https://wiki.mudlet.org/w/Manual:GMCP_Extensions#Automatic_map_download

Update tooltip, more than IRE now provide maps

---

src/Host.cpp

Remove unnecessary assignment when reading package/module config.
Less dangling code.

Remove unnecessary assignment when reading package/module config

---

src/dlgConnectionProfiles.cpp
src/dlgConnectionProfiles.h

New profiles are now saved correctly right when they're created.
Fix a really, really annoying bug.
Fix https://github.com/Mudlet/Mudlet/issues/2352

Fix new profiles to be saved correctly when created

---

src/mudlet-lua/genDoc.sh

Fixed shellcheck warnings in genDocs.sh
Better script.
Fix https://github.com/Mudlet/Mudlet/issues/2681.

Fixed shellcheck warnings in genDocs.sh

---

CI/travis.linux.after_success.sh

Fix comment typo in Linux publish script

Fix comment typo in Linux publish script

---

src/dlgTriggerEditor.cpp
src/dlgTriggerEditor.h

Split up `dlgTriggerEditor::slot_searchMudletItems` into smaller search functions.
More readable and approachable code.
Fix https://github.com/Mudlet/Mudlet/issues/2683

Splitup monolith search function

---

.github/main.workflow
translations/mudlet.ts

This should update translations on PRs whenever needed.
Less manual work.
Fixes #2660

Add workflow to update translations

---

README.md
translations/mudlet.ts

Discord image with member count

---

src/mudlet-lua/lua/utf8_filenames.lua
translations/mudlet.ts

Fix io.exists() and other LFS functions on Windows with non-ASCII usernames
4.0 goals
Fix https://github.com/Mudlet/Mudlet/issues/2708
First PR authored in https://gitpod.io... trying out to see how much, if at all, it's better than Github's default interface.

Fix io.exists() and other LFS functions on Windows with non-ASCII usernames

---

.github/main.workflow
.github/pr-labeler.yml

This changed workflow will automatically create a PR, label, approve and automerge translation texts, if CPP files are changed on development.
Less stress on CI jobs through commits on PRs without CPP changes.
As discussed on Discord.

Improve translation updates

---

src/TRoom.cpp

Although https://github.com/Mudlet/Mudlet/pull/2559 fixed a problem with custom exit line colour handling, it did not do anything to fixup maps that were generated prior to that fix being inserted into the code-base.
This PR does so by converting any missing or empty (no colour components) to have a default RED colour.
It closes #2701.

BugFix: prevent loading crash on maps with buggy custom line colors

---

src/TLuaInterpreter.cpp

Just a few fixes to two new texts about LuaGlobal and utf8_filenames
Follow up to #2694 and SlySven's comments about broken texts there

Update error messages in TLuaInterpreter

---

src/Host.cpp

This reverts commit 74eb2fe4285a71027d80cd0393121a4c0b0acc15.

Revert "Revert "Change default command separator to ;; (#1866)" (#2711)"

---

translations/mudlet.ts

Add updater and Edbee texts to translation
More complete translation of Mudlets entire interface.
Discovered by SlySven over at https://github.com/Mudlet/Mudlet/issues/2732#issuecomment-509853868.
Fix https://github.com/Mudlet/Mudlet/issues/2732.

Add updater and Edbee texts to translation

---

src/main.cpp
src/mudlet.cpp
src/mudlet.h
src/ui/main_window.ui

Replace IRC with Discord as the main help method.
IRC has not been the main method of assistance for a couple of years - relegate it to a secondary role after Discord
Fix https://github.com/Mudlet/Mudlet/issues/1387
Livestreamed this work at https://youtu.be/wPi_C5Qmgeg and https://youtu.be/xHylgH2JJTo.

Replace IRC with Discord as the main help method

---

.github/main.workflow

Adds more directories to scan for translatable texts.
More l18n
See #2732

Scan dblsqd and edbee for translatable files as well

---

CI/travis.compile.sh
CI/travis.linux.after_success.sh

This part of the process was never really used and we moved the `lupdate` call to GitHub actions so it's not used here anymore.
Make CI process less complex

Remove legacy translation update

---

src/Host.cpp

Fix package installation for Linux packages with config.lua
Bugfix.
Fix https://github.com/Mudlet/Mudlet/issues/2788
The extra '/' was making Qt not rename the folder as intended.

Fix package installation for Linux packages with config.lua

---

src/TTextEdit.cpp

As far as I can tell this should be a binary OR, not a bitwise OR?
Fix a (possibly) broken condition.

Typo fix in TextEdit::mouseMoveEvent

---

src/mudlet.cpp
src/mudlet.h

Add Disconnect dropdown button to the Connect one
Consistency with the menubar.

Add Disconnect dropdown button to the Connect one

---

src/ctelnet.cpp

Remove stray debug echo only echoing name of profile
Less clutter in debugging output.
Always wondered where it came from and it was kind of hard to find without any identifying information.

Remove stray debug echo only echoing name of profile

---

src/mudlet.pro

Remove 'temporary testing' code from qmake build
It adds no value and the temporary part has been there for quite a long while!

Remove 'temporary testing' code from qmake build

---

src/dlgTriggerEditor.cpp

Add a few line breaks and highlights in the intro texts shown in code editors.
Improve readability
Follow up to #2750

Improve upon editor introduction layouts

---

.travis.yml
CI/travis.linux.after_success.sh

Add Chinese input method to Linux AppImage.
So Chinese Linux users can type in their native language
Fix https://github.com/Mudlet/Mudlet/issues/2290.

Add Chinese input method to Linux AppImage

---

src/TLuaInterpreter.cpp

Just a few links to the wiki which have been missing in source
Keep documentation ready to hand
Follow-up to #1707

TLuaInterpreter update links to documentation

---

translations/mudlet.ts
translations/translated/mudlet_en_US.ts

Update Crowdin texts to latest

---

src/mudlet.pro

Fix 'FreeFSB' typos in mudlet.pro
Less typos.

Fix 'FreeFSB' typos in mudlet.pro

---

translations/translated/CMakeLists.txt
translations/translated/updateqm.pri

Always produce English feedback from `lrelease` to use for translation stats
Fix broken `mudlet.pro` in other locales

Gain translation stats in English

---

.appveyor.yml

Don't upload artifacts to appveyor, https://make.mudlet.org/snapshots is working out fine.
Faster Windows CI builds.

Don't upload artifacts to appveyor

---

src/TLuaInterpreter.cpp

Fix qmake and Qt Creator builds in Windows to load all Lua modules once again.
Necessary for coding on Windows!

Load Lua modules in Windows qmake builds

---

.travis.yml
CI/travis.linux.install.sh

Update from GCC 5 to 9 in PPA builds
So we can build with C++17! :)

Update from GCC 5 to 9 in PPA builds

---

src/TBuffer.cpp
src/TLuaInterpreter.cpp
src/TMap.cpp
src/TRoom.cpp
src/TTextEdit.cpp
src/dlgTriggerEditor.cpp

Replace clang extension with C++17 standard fallthrough attribute
Use new standard attributes available to us!

Replace clang extension with C++17 standard fallthrough attribute

---

src/TLuaInterpreter.cpp

Small experiment to replace 3 lines and `std::tie` with a structured binding! It works!
Less code is better code! :grin: 
Read this very nice and simple overview: https://skebanga.github.io/structured-bindings/

Use a structured binding isntead of std::tie

---

src/ui/triggers_main_area.ui

Typo fix in multi-line tooltip for triggers
Less typos.

Typo fix in multi-line tooltip for triggers

---

src/mudlet-mapper.xml

Update to latest 19.7.1 IRE mudlet mapper
Release checklist... also I haven't done this in a long while as I should have.

Update to latest 19.7.1 IRE mudlet mapper

---

CI/travis.linux.install.sh

Update coverity download link to recommended one
Coverity builds have been failing for the last few days because not enough files are compiled - I suspect because of the C++17 change. I did notice that we're using and outdated builder from 2017, perhaps the 2019 one will fix the problem. If no, we'll investigate further.
See https://scan.coverity.com/download: Linux (for Travis CI)

Update coverity download link to recommended one

---

src/TLuaInterpreter.cpp
src/TTrigger.cpp
src/TTrigger.h
src/XMLimport.cpp
src/dlgTriggerEditor.cpp

Don't show an error when creating a new group, and don't show the error (but still mark as ladybug) when creating a new trigger.
Better user experience.

Fix errors when creating new triggers

---

CI/travis.linux.install.sh

Fix the download of the coverity scan tool.
Make coverity work again!

Download coverity securely

---

src/ui/connection_profiles.ui

Fix copy button size to be equal to others.
Perfection 👌
Fix https://github.com/Mudlet/Mudlet/issues/2800.

Fix copy button size to be equal to others

---

src/TCommandLine.cpp

Remove left over debug statement for command line
Less spam in stdout.

Remove left over debug statement for command line

---

src/TLuaInterpreter.cpp

Fix permGroup for aliases and timers. It already worked for triggers thanks to @demonnic's work on this.
Better quality.
Fix https://github.com/Mudlet/Mudlet/issues/2882.

Fix permGroup for aliases and timers

---

src/TLuaInterpreter.cpp

Same as https://github.com/Mudlet/Mudlet/pull/2886 but for the 4.0 release branch.
Bugfix.

Fix permGroup for aliases and timers (4.0 branch)

---

CI/travis.linux.install.sh

Unpack and remove the correct file from coverity

---

src/ui/profile_preferences.ui

Don't mark : and port mask for translation in proxy settings
This should not be translated.

Don't mark : and port mask for translation in proxy settings

---

src/mudlet-lua/lua/StringUtils.lua

Update string.trim to only return trimmed string as intended.
Fix case with `table.insert()` not working with the output of `string.trim()`

Update string.trim to only return trimmed string as intended

---

src/TTrigger.cpp

Fix triggers patterns getting erased, because none were set to begin with due to a logic flaw.
Very important bugfix.
Fix https://github.com/Mudlet/Mudlet/issues/2883.
Caused by a logic flaw in https://github.com/Mudlet/Mudlet/pull/2868.

Fix triggers patterns getting erased

---

CI/appveyor.after_success.ps1

* extract before this change: /mudlet/release/mudlet.exe
* extract after this change: /mudlet/mudlet.exe
Less clicks, quicker test results
As discussed in discord

Remove "release" folder from .zip

---

src/TLuaInterpreter.cpp
src/TTrigger.cpp
src/TTrigger.h
src/XMLimport.cpp
src/dlgTriggerEditor.cpp

Revert trigger editor changes that make error messages not show for new triggers or groups.
Apparently this makes triggers go crazy and always fire.

Revert trigger editor changes

---

.appveyor.yml
CI/appveyor.set-environment.ps1
CI/qt-silent-install.qs

Update Qt to 5.13.0 on Windows.
Appveyor removed the 5.12.2 Qt Installation, so our builds don't work anymore. This will fix them.

Update Windows Qt - 4.0 edition

---

.appveyor.yml
CI/appveyor.set-environment.ps1
CI/qt-silent-install.qs

Update Qt to 5.13.0 on Windows.
Appveyor removed the 5.12.2 Qt Installation, so our builds don't work anymore. This will fix them.

Update windows qt

---

src/mudlet-lua/lua/TableUtils.lua

Adds a table.keys utility function
I've added it to many of my profiles, it's a handy convenience method that I'm honestly surprised we haven't added long since. This way we also provide a more performant function than those new to lua scripting or unused to optimizing such things may come up with on their own.

Add table.keys utility function

---

CI/appveyor.install.ps1
CI/copy-non-qt-win-dependencies.ps1

This should fix secure connections (both TLS over Telnet and HTTPS) on Windows.
Make Mudlet secure again!
Fixes #2921 and fixes #2922

Use OpenSSL 1.1.1 on Windows

---

src/mudlet-lua/lua/Other.lua

Fixes mudletOlderThan() so it will correctly  decipher if the current version of mudlet is older than what is requested.
It broke Svof

mudletOlderThan fix

---

CI/appveyor.after_success.ps1
CI/travis.linux.after_success.sh
CI/travis.osx.after_success.sh

Fix the attachment of dblsqd releases for the 4.0 branch as well.
Less manual work.

Fix dblsqd auto attachment

---

src/mudlet-lua/lua/Other.lua

Copy https://github.com/Mudlet/Mudlet/pull/2925 to the 4.0 branch for the hotfix 4.0.2.
This breaks svof and other systems too, I imagine.

Fix mudletOlderThan() in release-4.0 branch

---

src/dlgAboutDialog.cpp

Fix Patreon link to work
So people who'd like to support can do so!
(cherry picked from commit 5647fe9628317f5e59fab845f2e191e88bb62dcb)

Fix Patreon link in Supporters tab to open browser (#2927)

---

.appveyor.yml
CI/appveyor.set-environment.ps1
CI/qt-silent-install.qs

Use Qt 5.12.3 for Windows Mudlet
Possibly fix the editor crashing issue related to scrolling / using it in general.
Fix https://github.com/Mudlet/Mudlet/issues/2926.

Use Qt 5.12.3 for Windows Mudlet

---

CI/appveyor.install.ps1
CI/copy-non-qt-win-dependencies.ps1

This reverts commit 4127624fee124bdac5324d7b2a5c11cc13a81ec1.
Restore TLS/SSL connection support for 4.x series.

Revert "Use OpenSSL 1.1.1 on Windows (#2923)"

---

src/TCommandLine.cpp

Remove debug code for input line fallback
Less debug spam.

Remove debug code for input line fallback

---

README.md

Same gif but sourced from current repository
Migrating away from launchpad
Compare #2935

Gif from github not launchpad

---

src/ui/profile_preferences.ui

Triggers and aliases now work with i18n.

Update encoding tooltip for better i18n status

---

.gitmodules

Use our own https://github.com/Mudlet/edbee-lib fork instead of @dicene's since the autocompletion changes aren't really going upstream and we've been stuck in this limbo for a few years where we need to badger dicene for any improvements we want to do to edbee.
C++17 compilation on strict compilers that have deleted outdated C++ functionality finally removed in C++17 like `std::auto_ptr`.

Use our own edbee with updated QsLog

---

CI/travis.linux.install.sh

This fixes the URL of the coverity package to retrieve it.
Fix our cron jobs to get statics analysis working again!

Use correct URL to download the coverity software

---

src/T2DMap.cpp
src/TLuaInterpreter.cpp
src/TMap.cpp
src/dlgTriggerEditor.cpp
src/main.cpp

Remove < Qt 5.11 workarounds
Less cruft!

Remove < Qt 5.11 workarounds

---

src/TLuaInterpreter.cpp

Replace a couple of cases of std::tie with auto
So when new people copy/paste code, they copy/paste the better version.
Note that I left one `std::tie` in place as this seems to be a legitimate case to keep it: https://github.com/Mudlet/Mudlet/blob/development/src/TLuaInterpreter.cpp#L1911

Replace a couple of cases of std::tie with auto

---

src/T2DMap.cpp

Fix a possible nullptr dereference if the room wasn't found for some reason. 
Less theoretically possible crashes.
CID 1472988.

Fix a possible nullptr dereference if the room wasn't found

---

.github/main.workflow

It hasn't been working yet, and it either stalls (see latest commits on `development`) or sometimes fails builds - so not adding a positive value, just yet.
Lets disable it until it's good to go again.
Less false errors/stalls in build status.

Disable Github workflow for the time being

---

CPPLINT.cfg

The [CodeFactor](https://github.com/marketplace/codefactor) app we've got seems pretty neat - but it complains about things we don't really care about. Remove the louder warnings that I don't see as being useful.
Less noise.
CodeFactor uses cpplint (https://pypi.org/project/cpplint/)

Adjust cpplint settings

---

CMakeLists.txt
src/CMakeLists.txt
src/T2DMap.cpp
src/TConsole.cpp
src/TLuaInterpreter.cpp
src/TMap.cpp
src/TMap.h
src/ctelnet.cpp
src/dlgMapper.cpp
src/dlgMapper.h
src/mudlet.cpp
src/mudlet.pro
src/ui/mapper.ui

Add 3D Mapper compile-time toggle; see `mudlet.pro` on how to enable it.
Mudlet compile for Raspberry Pi.
Close https://github.com/Mudlet/Mudlet/issues/2968

Add 3D Mapper compile-time toggle

---

src/mudlet.qrc

Remove duplicate aliases in resource file
No duplicate warning when running qmake.
Must have snuck through recently as a bad merge.

Remove duplicate aliases in resource file

---

.appveyor.yml
.travis.yml

This commit will stop all branches except the default branch (`development`), release branches (starting with `release-`) and tags from building. PRs that target any of those branches will be still be built.
This will hopefully avoid clogging up our build jobs until the point the branches need building for the PRs.
Closes #3006

Avoid building random branches

---

src/TTextEdit.cpp

Fixes timestamp selection regression in 4.0

---

src/TLuaInterpreter.cpp

Improve calcFontSize function to spit numbers out for any given font size and name.
Useful for sizing labels around miniconsoles without jumping through a ton of hoops.
Similar to https://github.com/Mudlet/Mudlet/pull/3004 but in the C++ core.

Added calcFontSize(window_or_fontsize, optional_font_name)

---

src/TBuffer.cpp

The empty (no parameter) case is the same as the one with a single `0` which is the reset attributes case. Mudlet was not handling it as that but it will do after this commit.
This will close issue #2993 .
Also clean up some tabs used for spaces in the same method: `(void) TBuffer::translateToPlainText(...)`

BugFix: handle empty SGR...m sequences so they are treated as SGR0m

---

src/mudlet-lua/lua/GUIUtils.lua
src/mudlet-lua/lua/geyser/GeyserMiniConsole.lua

adds the c/d/h versions of the insertLink, echoPopup, and insertPopup functions. Already have echo, insertText and echoLink so I figured I should add the rest when I went to use cechoPopup and discovered it didn't exist yet.
True up API. Surprised nobody has asked for these before (that I could find with a brief search)

Adding c/d/h variants of insertLink, echoPopup, and insertPopup

---

src/Host.cpp
src/Host.h
src/XMLimport.cpp
src/dlgProfilePreferences.cpp

Fix font size not getting loaded, and the 'invalid font' label showing at start.
Fix issues introduced by https://github.com/Mudlet/Mudlet/pull/2865.

Fix up font loading issues

---

3rdparty/cocoapods/Empty.xcodeproj/project.pbxproj
src/Host.cpp
src/Host.h
src/TLuaInterpreter.cpp
src/TLuaInterpreter.h
src/XMLexport.cpp
src/XMLimport.cpp
src/ctelnet.cpp
src/ctelnet.h
src/dlgProfilePreferences.cpp
src/mudlet-lua/lua/LuaGlobal.lua
src/ui/profile_preferences.ui

Enable negotiation of the MSSP out-of-band telnet protocol with Mudlet. Store the values in an `mssp` Lua table accessible for scripting in Mudlet.  Toggle the protocol on and off via the Settings tab in the Mudlet UI.
-Tamarindo@StickMUD
1. There are hundreds of games supporting the MSSP protocol. Check the [MSSP Mud Crawler](https://tintin.sourceforge.io/protocols/mssp/mudlist.html) for examples.
2. The data exposed by the MSSP protocol is structured data that could be of use for common scripts shared among Mudlet users. The game name and website are two examples of content (more below). Typically, MSSP data is sent only once by servers at the player login.
3. Mudlet's support of MSSP provides games additional motivation to implement this standard protocol and register with the crawlers …

Negotiate and store MSSP data in Lua table

---

cmake/FindHUNSPELL.cmake

Allow Mudlet to build with Hunspell 1.7.

Detect hunspell 1.7

---

src/mudlet-lua/lua/GUIUtils.lua

Fix 'lumosity' typo in showColors().
More professional with less typos.
Nothing was affected because the typo was consistent.

Fix 'lumosity' typo in showColors()

---

src/TCommandLine.cpp

Fix the switch to fallthrough to normal key processing if the Ctrl+# combination doesn't match.
Fix https://github.com/Mudlet/Mudlet/issues/3057.

Fix broken Alt+# keybindings

---

src/TCommandLine.cpp

Fix Ctrl+# going off many times in 4.1.1
Bugfix.

Fix Ctrl+# going off many times in 4.1.1

---

src/mudlet-lua/lua/geyser/GeyserGauge.lua

Currently if you feed setValue non numbers it throws errors that are unhelpful. These should be much more helpful.
Someone in #help ran into this earlier

Throw errors that make sense if we get nonnumbers for setValue

---

src/mudlet-lua/lua/generic-mapper/generic_mapper.xml

Make "No current area name" error message more friendly.
Better first-time player experience

Make "No current area name" error message more friendly

---

src/TLuaInterpreter.cpp

Bring setRoomEnv's error messages up to standard
Better experience for scripters when things go wrong!

Bring setRoomEnv's error messages up to standard

---

src/dlgProfilePreferences.cpp
src/dlgSourceEditorArea.cpp
src/dlgTriggerEditor.cpp

Indent with spaces in code editor instead of tabs when pressing enter.
[Demonstration](https://streamable.com/pbvv7)
A lot of people want it this way.

Indent with spaces in code editor instead of tabs when pressing enter

---

src/TTextEdit.h

Default-initialise TTextEdit values that aren't yet, see https://github.com/Mudlet/Mudlet/issues/3101#issuecomment-533341820 for background.
Possibly fix a crash - it's pretty hard to reproduce so can't be certain, but this can't hurt.
Fix https://github.com/Mudlet/Mudlet/issues/3101.

Default-initialise TTextEdit values

---

.gitmodules

Update QtKeychain to the version we use
Upstream can be slow with merging PRs. We'll still submit them, but we can at least apply them to our fork quicker!
Strange that CI was quite happy with this...
Close https://github.com/Mudlet/Mudlet/issues/3122.

Update QtKeychain to the version we use

---

src/Host.cpp
src/Host.h
src/ctelnet.cpp

Load autologin password from secure storage as well
Fix autologin to work in `development` again.

Load autologin password from secure storage as well

---

.travis.yml
CI/travis.linux.after_success.sh

This will deploy updates to the Geyser LDoc documentation when a new tag is created.
More up-to-date documentation with less manual work.
Closes #1050

Deploy geyser docs on tag

---

src/TLuaInterpreter.cpp
src/TLuaInterpreter.h
src/TMap.cpp
src/TMap.h

This will remove some not documented, not used and not working functionality from code
Less clutter and less confusion
As noted in #1149 2 years ago

Remove obsolete "setMapperView" function

---

src/TLuaInterpreter.cpp
src/TLuaInterpreter.h

This will remove some not documented, not used and not working functionality from code
Less clutter and less confusion

Remove obsolete "solveRoomCollisions" function

---

src/mudlet.cpp

I was forcing the word count in the first line of the file to be 1 even when there was NO words in the dictionary - which was throwing up deceptive debug messages about the dictionary status...
It was also not using a word count of zero initially when asked to scan dictionaries - instead they were set to an incorrect value of 1.
This closes #3106 .
Signed-off-by: root <slysven@virginmedia.com>

BugFix: correct an off-by one error for an empty dictionary file

---

.appveyor.yml
CI/appveyor.functions.ps1
CI/copy-non-qt-win-dependencies.ps1
CI/qt-silent-install.qs

Update Qt on Windows to 5.13.0 to get partially even with macOS.
New features and (hopefully?) more stable basis.
This also updates OpenSSL to 1.1.1d

Update Qt on windows to 5.13.0

---

CMakeLists.txt
cmake/InitGitSubmodule.cmake

This moves the cmake code to initalize git submodules to an own function.
Use the DRY (don't repeat yourself) principle and also cleans our code up quite a bit.
Relates to #1392

Cmake improve git submodule initialization

---

src/mudlet-lua/lua/TableUtils.lua

Clarify table.is_empty's error message
You can't tell which function the error came from right now.

Clarify table.is_empty's error message

---

src/TMap.cpp
src/dlgProfilePreferences.cpp
src/mudlet.cpp
src/mudlet.h
src/updater.cpp

Add dev/release/public test version booleans and update code to use them.
So we can tell public test releases and dev versions apart.
Part of https://github.com/Mudlet/Mudlet/issues/3074.

Add dev/release/public test version booleans

---

src/mudlet-lua/lua/generic-mapper/generic_mapper.xml

Noticed the bracket was misplaced in https://github.com/Mudlet/Mudlet/commit/f8fc66ffe99f67193d8241c3fa68d716c14665ca as I merged it :open_mouth: 
Bugfix

Fix 'show moves'

---

.github/CONTRIBUTING.md

Add git client recommendation, lower barrier for contributions.
Based on our recent experience with line endings in Qt Creator and copy/pasting them as-is into Github's web interface.

Add git client recommendation

---

src/mudlet-lua/lua/GUIUtils.lua

change behaviour of clicking showColors colors to append rather than replace. Makes it more useful in forming cechos and the like.
closes https://github.com/Mudlet/Mudlet/issues/3209

Changing printCmdLine to appendCmdLine in showColors

---

.travis.yml

This enables configuration validation for the `.travis.yml` file
Better messages about configuration mistakes.
See https://blog.travis-ci.com/2019-10-24-build-config-validation for details.

Use Travis config validation

---

src/dlgComposer.cpp

Change font size in composer back down, it's good as a default for the big main window, but not so for the composer.
Close https://github.com/Mudlet/Mudlet/issues/3227

Change font size in composer back down

---

.appveyor.yml
CI/appveyor.functions.ps1
CI/copy-non-qt-win-dependencies.ps1
CI/qt-silent-install.qs

Use latest VS image in Appveyor
More Qt version options, and less change of appveyor removing a Qt version we need under us.
Hopefully we don't get https://github.com/Mudlet/Mudlet/issues/2926 again nor https://github.com/Mudlet/Mudlet/issues/3211.

Use latest VS image in Appveyor

---

src/mudlet.cpp

Add Portugese (Brazil) as a selectable language for Mudlet
We now have a translator who's translating it :D
Close https://github.com/Mudlet/Mudlet/issues/3242

Add Portugese (Brazil) as a selectable language for Mudlet

---

CI/travis.osx.install.sh
src/Host.cpp
src/TLuaInterpreter.cpp
src/ctelnet.cpp
src/dlgTriggerEditor.cpp
src/mudlet.cpp

One was pointed out to me by CodeFactor in a recent commit to a PR and when
I looked I found a few more!

Refactor: remove multiple redundent semi-colons following closing braces

---

src/TTextEdit.cpp

Put in a couple checks for bounds in front of every place I can imagine an out of bounds check is needed.
Fix https://github.com/Mudlet/Mudlet/issues/3239.

Fix selection crash

---

translations/mudlet.ts

Update source text for translators
4.4 release process.

Update source text for translators

---

src/TMedia.cpp
src/TMedia.h
src/ctelnet.cpp

* Adds include files to MSP cpp files
* Resolves harmless cleanup items from a code review.
@slysven and Githzerai had issues building their Linux environments that had WITH_UPDATER set to NO after the initial code for MSP was included in the development branch.
Follow-up to #3132

MSP Includes for WITH_UPDATER set to NO

---

src/mudlet-lua/lua/GUIUtils.lua

Refactors current c/dreplace implementations to be more in line with cecho/etc and to keep code more DRY. adds hreplace
Someone asked me how to suggest additions to Mudlet, then said they thought it would be good to have hreplace. So I looked ended up adding it.
Already added c/r/hreplace to the wiki, they were missing despite c and d already existing.

Refactor to avoid repetition, add hreplace

---

src/mudlet.cpp
translations/translated/qm.qrc

Add Turkish language as an interface option
We have a Turkish translator now!

Add Turkish language as an interface option

---

src/mudlet.cpp

Don't translate the word 'Discord'
It's a company name

Don't translate the word 'Discord'

---

src/dlgMapper.cpp
src/glwidget.cpp
src/glwidget.h

Change the deprecated QGLWidget to QOpenGLWidget
The main motivation is https://github.com/Mudlet/Mudlet/issues/3321 which is solved with this fix
Used this blog for some changes 
https://nils.schimmelmann.us/post/134971073937/migrating-from-qglwidget-to-qopenglwidget

3DMapperBugFix

---

CI/appveyor.after_success.ps1

Create realisify builds for Public Test Builds's properly, because it doesn't right now.
Fix public test builds on windows to actually work.
Continuation of https://github.com/Mudlet/Mudlet/pull/3183

Create realisify builds for Public Test Builds's properly

---

.appveyor.yml

This reverts commit e2b2cdad944fe817b3c68fafa5fa128b31caccab.
AppVeyor fixed the image.

Revert "Fix AppVeyor builds due to image upgrade"

---

CI/appveyor.after_success.ps1

Create dblsqd release before trying to push to it
PTB releases can't be updated right now, since they're never successfully registered with dblsqd.

Windows PTB's: fix dblsqd deployment

---

src/mudlet-lua/lua/GUIUtils.lua
src/mudlet-lua/lua/geyser/GeyserGauge.lua
src/mudlet-lua/lua/geyser/GeyserLabel.lua

Add Geyser (Label/Gauge) Wrapper for setting Tooltips:
Geyser gauge/label:setToolTip(text, [duration]) 
Geyser gauge/label:resetToolTip()
Add Gauge Wrapper for setting Tooltips
setGaugeToolTip(gaugename, text, duration)
resetGaugeToolTip(gaugename)
Better usability

Add Geyser/Gauge Wrapper for setLabelToolTip

---

src/TBuffer.cpp
src/TBuffer.h

Support blinking text as italics instead as a compromise between user desirability and implementation difficulty.
Close https://github.com/Mudlet/Mudlet/issues/3358.
MUSHclient does the same and it works.

Support blinking text as italics instead

---

src/mudlet-lua/lua/geyser/GeyserColor.lua

Adds capability for Geyser.Color.parse to find a color name even if the user has fed it something case incorrect. Adds Geyser.Color.find_color_name which it utilizes internally to do the work.
Someone posted something similar on the Mudlet discord and I felt it was appropriate to add to Geyser.Color

Added Geyser.Color.find_color_name and utilize it to harden Geyser.Color.parse

---

translations/mudlet.ts

Update translation strings to latest for Mudlet 4.6
So translators can translate the newly introduced text.

Update translation strings to latest for Mudlet 4.6

---

src/TLuaInterpreter.cpp
src/TLuaInterpreter.h

Split the functionality of PR 3367 into two internal functions one create Label in UserWindow and the other in the MainWindow
Only functional change to PR 3367 is that fillbackground is non-optional again
A suggestion to simplify and make the code for createLabel easier to read
made quick test and couldn't find any issue

simplify code for createLabel (suggestion)

---

src/mudlet-lua/tests/Other_spec.lua

Adds 25 new tests against functions from Other.lua. Documents a todo list at the bottom of the spec file for the functions (as of the time of this PR) which are not covered by tests.
Making Mudlet and its releases less fragile. Yay testing.
Also exposed the first bug using the tests, it seems.

Increasing code coverage for Other.lua

---

src/TLuaInterpreter.cpp

Merge release-4.4 into development, part of the 4.4 release process...
Add the fix we did in 4.4 and delete `release-4.4`

Merge release-4.4 into development

---

src/mudlet-lua/lua/TableUtils.lua
src/mudlet-lua/tests/TableUtils_spec.lua

* Adds tests for functions in TableUtils.lua
* Fixes a minor issue with the error message for table.is_empty the tests caught
TEST ALL THE THINGS!

Tableutils tests
